### ISSUE TITLE
Update password with wrong current password gives an incorrect error message 

### ISSUE THREAD

**Issue by harshchitrla** [aws-amplify/amplify-ios#1329] opened 2021-07-19 14:57 UTC
### Describe the bug

I'm trying to update the password using Amplify iOS library.  
As we know, the method accepts a current password and a new password. When we try to send an incorrect current password it gives us an error message "Incorrect username or password".

We are unable to override an error message as we are getting the exception type as nil in this scenario. Please find the error message below. 
  ▿ notAuthorized : 3 elements
    - .0 : "Incorrect username or password."
    - .1 : "Check whether the given values are correct and the user is authorized to perform the operation."
    - .2 : nil

### Steps To Reproduce

```swift
Try to provide an incorrect current password.
```

### Expected behavior

Error message to be relevant to the use case or Exception type should not be nil. 

### Amplify Framework Version

1.9.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

4.50.0

### Xcode version

12.4

### Device

iPhone 11

### iOS Version

iOS 14.4

**Comment by harshchitralaMM** [comment] 2021-09-06 05:21
@lawmicha @royjit Can we get an update on this?

**Comment by royjit** [comment] 2021-09-10 03:58
The error message is the one returned by Cognito User Pool service and Amplify is passing the same error back in the api call. I tried to reproduce the issue and the error I got from server is:

```
{
    "Content-Length" = 79;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Fri, 10 Sep 2021 03:56:38 GMT";
    "x-amzn-errormessage" = "Incorrect username or password.";
    "x-amzn-errortype" = "NotAuthorizedException:";
    "x-amzn-requestid" = "2axxx";
}
```

**Comment by royjit** [comment] 2021-09-21 00:57
I do not think there is a fix for this since we are passing on the service error here.

**Closed by royjit** 2021-09-21 00:57 UTC
Labels: pending-response, auth, question
