### ISSUE TITLE
Amplify Storage Works on Simulator but 403 on a device

### ISSUE THREAD

**Issue by iThink32** [aws-amplify/amplify-ios#978] opened 2020-12-17 09:47 UTC
**Describe the bug**
Hey I have a project that uses amplify to interface with multiple services like lambda ,cognito, storage etc.
But due to some reason storage(s3) always gives me a 403 on a device but works fine on a simulator.
This similar problem occurred with lambda but I solved it by using Cognito as the authorisation type , im assuming the same is the issue with storage but im unable to find out how to change the autorization type from IAM to cognito.

**To Reproduce**
Run on simulator everything works fine
Run on a device Storage gives a 403

**Expected behavior**
Similar behaviour on simulator and device

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.32.0
 - Dependency Manager:  Cocoapods
 - Swift Version :  5.1

A part of my amplifyconfiguration.json is added below

```
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "****",
                            "Region": "****"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": ""****",",
                        "AppClientId": ""****",",
                        "AppClientSecret": ""****",",
                        "Region": ""****","
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": ""****",",
                        "Region": ""****","
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": ""****",",
                "region": ""****",",
                "defaultAccessLevel": "guest"
            }
        }
    }
```

**Comment by royjit** [comment] 2020-12-21 22:39
Hi @iThink32 

Can you please provide a code snippet on what you are trying in S3 and any related logs messages that you see.

**Comment by iThink32** [comment] 2020-12-23 05:36
Hey @royjit im trying to upload a file to s3 bucket , sample code is shown below 

```
       _ = Amplify.Storage.uploadData(key: path, data: data, resultListener: { (result) in
            switch result {
            case Result.success :
                print("ok")
            case let Result.failure(error):
                print(error)
            }
        })
```

post which I always get a 403 error on device , this when executed on a simulator uploades the file specified under the public/filename as expected.

The error which I get on a device is 
```
StorageError: The HTTP response status code is [403].
Recovery suggestion: TODO some status code to recovery message mapper.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
```

Acc to my analysis it is working on a simulator as Amplify CLI uses IAM for auth whereas on device the auth is failing , I faced the similar issue with Lambda functions but I was able to solve it by specifying 

```
"authorizationType": "AMAZON_COGNITO_USER_POOLS"
```

in amplifyconfiguration.json

When I searched for the same for Storage I found this

```
            "awsS3StoragePlugin": {
                "bucket": "******",
                "region": "*****",
                "defaultAccessLevel": "guest"
            }
```

Things ive tried
1) Changing the above to protected
2) using  `StorageUploadDataRequest.Options(accessLevel: .protected)` in the option parameter to the above amplify func but to no avail.

**Comment by wooj2** [comment] 2021-01-14 23:50
Hi @iThink32 ,

1.  Have you tried to increase verbosity in your log level?  For example:
```
            Amplify.Logging.logLevel = .verbose
```
You might be able to get some additional clues about the specific error(s) that is/are coming back from the service.

2.  It is surprising to see that there is a difference between a device and a simulator.  Is your device on the same network as your simulator?  Are there any additional firewalls rules that might be getting in the way?

3.  Are there any known differences between your device and simulator with regards to:
* Configuration
* Code changes
* iOS versions
* etc..

**Comment by iThink32** [comment] 2021-01-15 05:42
@wooj2  no difference at all wrt simulator and device.Sure I will try the above out but this is more of a logging level rather an a conceptual reason , could you please tell me whether 

```
  "awsS3StoragePlugin": {
                "bucket": "******",
                "region": "*****",
                "defaultAccessLevel": "guest"
            }
```

this is expected? via the cli

**Comment by iThink32** [comment] 2021-02-13 14:42
@wooj2 pls provide an update , the SDK is becoming a black box to me now , I am able to upload files via protected access level but not download the same , I get a 403 error

**Comment by iThink32** [comment] 2021-02-13 14:47
even after doing the above that you mentioned I get the following
```
StorageError: The HTTP response status code is [403].
Recovery suggestion: TODO some status code to recovery message mapper.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
```

Moreover I am unable to re-open this issue pls do so.

**Comment by iThink32** [comment] 2021-02-13 15:41
To give you more context the download task is working on simulator by using 
```
let options = StorageDownloadDataRequest.Options(accessLevel: .protected,
                                                 targetIdentityId: "OtherUserIdentityId")
Amplify.Storage.downloadData(key: "userProtectedKey", options: options) { result in
    // handle result
}
``` 
as mentioned In the docs but the same does not work on a physical device.

**Comment by iThink32** [comment] 2021-02-13 15:41
@lawmicha thanks for reopening the issue.

**Comment by lawmicha** [comment] 2021-02-13 16:27
Hi @iThink32,

The protected folder requires an authenticated user to perform the action, just making sure, have your user signed in on the device before attempting to perform the upload/download to protected access level? It is odd that the behavior is different across simulator vs device

**Comment by lawmicha** [comment] 2021-02-13 16:31
Also, when you perform an upload to a protected folder, the storage plugin will internally retrieve the identity id of the user, and prepend it to the key. You can check the S3 bucket to see the path that was uploaded to. Downloading from the protected folder for another user requires some coordination; how are you retrieving the other identity id btw?

**Comment by iThink32** [comment] 2021-02-13 16:39
@lawmicha 
Question one :
Yes I have logged in via cognito before trying to upload or download files from s3

Question Two:
Yes the upload works fine it uploads it to the path `protected/identityid/key` and for downloading the same file I’m assuming by `other identity id` it means the current users identity id who is trying to view the file uploaded by the other for which I extract it from the credentials provider of aws

**Comment by iThink32** [comment] 2021-02-13 16:41
I’m new to this so pls correct me if wrong , moreover the downloading of file by the above approach is successful on simulator but gives me a 403 on device

**Comment by lawmicha** [comment] 2021-02-13 16:45
When you first provisioned the S3 bucket, was it through ‘amplify add storage’? I believe there were some steps that asked how you wanted to allow guest and auth users access to the bucket for creating, reading, deleting. This corresponds to the IAM policies added to the IAM roles. Do you recall which options you have selected there? You can also check the policies by going to your Cognito identity pool, finding the auth role’s IAM role, going to AWS IAM console, finding the corresponding role, and looking at the policies attached. These policies determine the authorization of the calls that the user can perform against your S3 bucket. 

Also, did you say it is still working on simulator but not device or is it not working on both simulator/device?

**Comment by iThink32** [comment] 2021-02-13 17:03
Yes I do recall I have provided access to only authenticated users and after that all operations for authenticated users 
It is working fine on simulator but not on device

**Comment by iThink32** [comment] 2021-02-13 17:04
On simulator only if I give my identity id in the other identity is field can u also correct me on this , I’m supposed to send the current users id right?

**Comment by iThink32** [comment] 2021-02-13 17:07
In short to make things clear
**Upload using protected access:**
Working fine on decide and simulator 

**Download using protected access:**
Works on simulator only if I provide my identityId in the `otherIdentityId` field
Doesn’t work on Device

**Comment by lawmicha** [comment] 2021-02-13 17:57
Thanks for clarifying, for the download, you don’t need to send your own identity id if you are downloading for a file you uploaded from the same user, only when you download from another user, you can pass their identity id as the target. It should still work if you pass your own identity id for the download as that will simply act as an overload of the same value it would have otherwise retrieved. 

You can try removing the identity id when downloading a file uploaded from the same user. When retrieving a file for another user, you should persist the target identity id of the other user somewhere so that you have access to it from your current user. To get the identity id of any user, you can call Amplify.Auth.fetchAuthSession like this https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios

**Comment by iThink32** [comment] 2021-02-13 18:12
Cool thanks for the heads up but can u also guide me on my current problem , I’m unable to access my own files on a device

**Comment by iThink32** [comment] 2021-02-13 18:15
Very good info by the way I think it should be a part of the amplify doc , currently the docs are not very friendly to a person doing it from scratch

**Comment by iThink32** [comment] 2021-02-19 19:03
@lawmicha pls provide an update it’s been over a month since I’ve been stuck on this , a solution would help me a lot

**Comment by lawmicha** [comment] 2021-02-25 01:15
Hi @iThink32, I couldn't reproduce issue where device returned 403 and simulator did not

- I would always get 403 when I am not signed in, and successful when I am signed in. 
- If I am signed in, and the file does not exist, i get 404. 

I'm running Xcode 12.4 and launching the app to the device running iOS 14.4. My provisioning steps are [here](https://github.com/lawmicha/amplifyStorageSample) which creates the S3 bucket and cognito user pool with HostedUI endpoint. 

1. Sign in the user with web UI (https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios)
```swift
Amplify.Auth.signInWithWebUI(presentationAnchor: window)
```

2. Upload to protected (https://docs.amplify.aws/lib/storage/configureaccess/q/platform/ios)

```swift
func uploadTo(_ accessLevel: StorageAccessLevel) {
        let dataString = "Example file contents"
        let data = dataString.data(using: .utf8)!
        Amplify.Storage.uploadData(key: "ExampleKey", data: data, options: .init(accessLevel: accessLevel), progressListener: { progress in
            print("Progress: \(progress)")
        }, resultListener: { (event) in
                switch event {
                case .success(let data):
                    print("Completed: \(data)")
                case .failure(let storageError):
                    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
            }
        })
    }
```

3. Download from protected 
```swift
func downloadForSelf(_ accessLevel: StorageAccessLevel) {
        let options = StorageDownloadDataRequest.Options(accessLevel: accessLevel)
        
        Amplify.Storage.downloadData(
            key: "ExampleKey",
            options: options,
            progressListener: { progress in
                print("Progress: \(progress)")
            }, resultListener: { (event) in
                switch event {
                case let .success(data):
                    print("Completed: \(data)")
                case let .failure(storageError):
                    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
            }
        })
    }
```


Can you try on a different device and see the same behavior to narrow out a device issue?

If you have the device plugged in, you can see more verbose debug logging by adding these lines:
```swift
Amplify.Logging.logLevel = .verbose
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

Are you able to see the issue with `AWSDDLog` logging enabled?

**Comment by iThink32** [comment] 2021-02-27 12:00
@lawmicha thanks for the detailed feedback , i'm going to setup storage again by keeping in mind the steps you mentioned.
Regarding logs , have only used Amplify logging  haven't used AWSDDLog , will use that as well as try on another device to check whether it is a device specific issue.

**Comment by iThink32** [comment] 2021-02-27 16:20
@lawmicha on removing and setting up storage again , both upload and download seems to work fine on device now. Not sure what exactly was the reason but im facing a new problem now, the data that i get from s3 is failing at a UImage(data:...) level anything else to be handled here?

**Comment by lawmicha** [comment] 2021-03-02 17:57
@iThink32 good to know it is working now, i'll close this issue for now. Feel free to open another if you have worked through the new issue you are seeing and have repro steps for us to investigate (such as an example file you are uploading, how you are performing the upload, expected data in S3, how you are performing the download, and expected data from the download). Feel free to join Amplify's [Discord channel](https://discord.com/invite/jWVbPfC) and open up your questions for the community to help in ios-help channel.

**Closed by lawmicha** 2021-03-02 17:57 UTC
Labels: requesting info, storage

**Comment by sangy05** [comment] 2021-11-01 13:28
@iThink32  I am also facing the same issue.. Even for public folder upload / download, the same happens. Once I remove cognito & re setup, everything works fine. But I leave it for one or two days & I get 403 even though  user is logged in.

**Comment by iThink32** [comment] 2021-11-02 11:19
@sangy05 any luck with this anywhere , ive requested help in multiple places with no answer whatsoever

**Comment by iThink32** [comment] 2021-11-05 06:31
@lawmicha pls reopen the issue.We have been stuck for a long time now.Requesting your help

**Comment by lawmicha** [comment] 2021-11-05 13:37
@sangy05 @iThink32  could you open a new issue? Ther reason this will help us collect the latest information regarding the issue you are seeing to investigate into this, and as such if they happen to be duplicate, we can close one for the other. Otherwise, I'd like us to gather as much information from multiple sources to identify the problem

**Comment by lawmicha** [comment] 2021-11-05 13:39
Taking a look over in https://github.com/aws-amplify/amplify-ios/issues/1439

**Comment by iThink32** [comment] 2021-11-19 15:49
@sangy05  please have a look at https://github.com/aws-amplify/amplify-ios/issues/1439#issuecomment-974186636
