### ISSUE TITLE
Resolve Package Graph warnings when using Swift Package Manager

### ISSUE THREAD

**Issue by pierceglennie** [aws-amplify/amplify-ios#1158] opened 2021-04-10 20:09 UTC
**Describe the bug**

After integrating Amplify using Swift Package Manager I get 8 Resolve Package Graph warnings with messages like "found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target".

The first of these refers to a file "~/Library/Developer/Xcode/DerivedData/test-app-ghaxlhcelpjhlaebcjryqedbfrpv/SourcePackages/checkouts/amplify-ios/Amplify/Info.plist"

The rest are shown in the attached screenshot.

**To Reproduce**

1. Create a new iOS app project in Xcode. I'm using SwiftUI
2. Install Amplify using Swift Package Manager, following the [instructions here](https://aws.amazon.com/blogs/mobile/swift-package-manager-support-for-amplify/). I've chosen the Amplify, AWSPluginsCore and AWSCognitoAuthPlugin packages
3. Build the project
4. The warnings will be shown

**Expected behaviour**

No warnings

**Screenshots**

<img width="843" alt="Screenshot 2021-04-10 at 21 05 05" src="https://user-images.githubusercontent.com/8105776/114283198-6f404700-9a40-11eb-9594-bf5e0d13d531.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.8.0
 - Dependency Manager: Swift Package Manager
 - Swift Version: 5.3.2
 - CLI Version: 4.47.1

**Device Information (please complete the following information):**
 - Device: MacBook Pro (Intel)

**Comment by royjit** [comment] 2021-04-13 17:36
Hi @pierceglennie Thank you for reaching out, I was able to reproduce the issue. Here is a PR for the fix - https://github.com/aws-amplify/amplify-ios/pull/1163

**Comment by pierceglennie** [comment] 2021-04-13 20:20
Thanks for looking into it so quickly

**Comment by royjit** [comment] 2021-04-16 16:43
Closing this issue since the PR has been released.

**Closed by royjit** 2021-04-16 16:43 UTC
Labels: build, pending release

**Comment by nmccann** [comment] 2021-04-23 14:16
Thank you for the quick fixes! However, with the latest stable version (1.8.1) there appears to be one file that is still unhandled:

![package-issue](https://user-images.githubusercontent.com/3238769/115884387-da185780-a41c-11eb-9080-bc78b93a554d.png)
