### ISSUE TITLE
"An unknown error occurred" when trying to get tokens 

### ISSUE THREAD

**Issue by hellensoloviy** [aws-amplify/amplify-ios#1907] opened 2022-06-15 17:47 UTC
### Describe the bug

I can't get tokens at all using Amplify.Auth.
It is all working good and returns tokens with the AWSMobileClient, but not with the Amplify.Auth. 

Here is what I'm getting: 

```
Printing description of result:
(Amplify.AmplifyOperation<Amplify.AuthFetchSessionRequest, Amplify.AuthSession, Amplify.AuthError>.OperationResult) result = success {
  success = {
    isSignedIn = true
    userSubResult = failure {
      failure = unknown {
        unknown = {
          0 = "An unknown error occurred"
          1 = domain: "com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper" - code: 0 {
            _userInfo = 0x0000000280fbe6a0 1 key/value pair
          }
        }
      }
    }
    identityIdResult = failure {
      failure = unknown {
        unknown = {
          0 = "An unknown error occurred"
          1 = domain: "com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper" - code: 0 {...}
        }
      }
    }
    awsCredentialsResult = failure {
      failure = unknown {
        unknown = {
          0 = "An unknown error occurred"
          1 = domain: "com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper" - code: 0 {...}
        }
      }
    }
    cognitoTokensResult = failure {
      failure = unknown {
        unknown = {
          0 = "An unknown error occurred"
          1 = domain: "com.amazonaws.service.cognitoidentity.AWSCognitoCredentialsProviderHelper" - code: 0 {...}
        }
      }
    }
  }
}
```

### Steps To Reproduce

```swift
Try using Amplify.Auth.signIn() method. 
Implementation is according to https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#register-a-user . 

The result is the same if I'm trying to get specifically tokens, using Amplify.Auth.fetchAuthSession like here: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios/
```

### Expected behavior

It is expected to receive tokens that can be used. As in the documentation. 

### Amplify Framework Version

1.26.1

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

8.3.1

### Xcode version

13.3.1 (13E500a)

### Relevant log output

```shell
Nothing
```

### Is this a regression?

No

### Device

iPhone 12, 12Pro, 11 and all other tried 

### iOS Version

iOS 15.5

**Comment by thisisabhash** [comment] 2022-06-16 21:45
Hello, Thank you for posting this issue.
Could you please add detailed reproduction steps, `amplifyconfiguration.json` (sensitive information redacted) and  relevant logs (sensitive information redacted) that can help reproduce the issue?

**Comment by royjit** [comment] 2022-06-25 00:25
From the error code it `AWSCognitoCredentialsProviderHelper, code-0" it looks like the error is `AWSCognitoCredentialsProviderHelperErrorTypeIdentityIsNil`. This is similar to the issue reported here - https://github.com/aws-amplify/amplify-ios/issues/1822

Are you seeing this error when you call fetchAuthSession immediately after signIn?

**Comment by royjit** [comment] 2022-07-06 03:05
Closing as duplicate

**Closed by royjit** 2022-07-06 03:05 UTC
Labels: bug, duplicate, auth
