### ISSUE TITLE
DataStore cascading delete when offline doesn't clean up MutationEvent

### ISSUE THREAD

**Issue by bgomberg** [aws-amplify/amplify-ios#1234] opened 2021-05-14 23:45 UTC
**Describe the bug**
Using datastore, if I have a model which has a 1:many relationship to another model, issuing a delete on the parent object can potentially leave dangling entries in the local `MutationEvent` table.

**To Reproduce**
1. Configure Amplify with DataStore and without an API backend
2. Create a `Post` along with a single `Comment`
3. Delete the `Post`
4. The local database no longer contains either the post or comment, as expected, but the `MutationEvent` table still contains the "create" entry for the comment.

**Expected behavior**
I would expect the `MutationEvent` table to be empty.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.9.0
 - Amplify Categories: API + DataStore
 - Dependency Manager: Cocoapods
 - Swift Version: 5.4
 - CLI Version: 4.50.0
 - Xcode Version: 12.5

**Device Information (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 14.5

**Additional context**
Here's an example unit test which reproduces this issue (based on the types from the getting started guide):
```swift
    func testSaveDeleteCascading() throws {
        print("Clearing local DB")
        let clearExpectation = expectation(description: "Clear")
        Amplify.DataStore.clear() { result in
            switch result {
            case .success:
                clearExpectation.fulfill()
            case .failure(let error):
                XCTFail("Error saving post: \(error)")
            }
        }
        wait(for: [clearExpectation], timeout: 10)

        let post = Post(title: UUID().uuidString, status: .published, rating: 5)
        print("Creating post (id=\(post.id), title=\(post.title))")
        let saveExpectation = expectation(description: "Save")
        Amplify.DataStore.save(post) { result in
            switch result {
            case .success:
                saveExpectation.fulfill()
            case .failure(let error):
                XCTFail("Error saving post: \(error)")
            }
        }
        wait(for: [saveExpectation], timeout: 10)

        let comment = Comment(content: "Test Comment", post: post)
        print("Creating comment (id=\(comment.id), content=\(comment.content))")
        let saveExpectation2 = expectation(description: "Save")
        Amplify.DataStore.save(comment) { result in
            switch result {
            case .success:
                saveExpectation2.fulfill()
            case .failure(let error):
                XCTFail("Error saving comment: \(error)")
            }
        }
        wait(for: [saveExpectation2], timeout: 10)

        print("Deleting post")
        let deleteExpectation = expectation(description: "Delete")
        Amplify.DataStore.delete(post) { result in
            switch result {
            case .success:
                deleteExpectation.fulfill()
            case .failure(let error):
                XCTFail("Error saving post: \(error)")
            }
        }
        wait(for: [deleteExpectation], timeout: 10)
    }
```
Downloading the container and inspecting the `MutationEvent` table shows that a row still exists for creating the comment. It seems to me that the cascading delete behavior is entirely built on the foreign key relationship within SQLite and there isn't actually logic within DataStore for handling this (and therefore cleaning up MutationEvent). Does the backend also have similar logic for deleting the `Comment` in response to a deletePost mutation?

**Comment by diegocstn** [comment] 2021-08-04 15:47
Hi @bgomberg, 
thanks for reaching out. I couldn't reproduced the issue you described with both Amplify v1.9.0 and v1.13.0.
Just to clarify my understanding of the issue, here's my reproduction steps and what I observed:
1. setup an Amplify project with `AWSPluginsCore`, `AWSDataStorePlugin`, `Amplify` pods/packages and the following schema
```graphql
enum PostStatus {
  ACTIVE
  INACTIVE
}

type Post @model {
  id: ID!
  title: String!
  status: PostStatus!
  rating: Int
  content: String
  comments: [Comment] @connection(name: "PostComments")
}

type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
2. initialize Amplify 
```swift 
let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
try Amplify.add(plugin: dataStorePlugin)
try Amplify.configure()
```
3. create a new `Post` along with a new single `Comment`
4. observe that the `MutationEvent` table in the local DB contains two "create" entries, one for the new post the other one for the new comment 
5. delete the newly created post
```swift
 Amplify.DataStore.delete(post)
            .sink {
                if case .failure = $0 {
                    print("Failure \($0)")
                }
            } receiveValue: {
                ...
            }.store(in: &reqs)
```
6. observe that the `MutationEvent` table in the local DB contains now zero entries

**Comment by diegocstn** [comment] 2021-08-24 00:48
@bgomberg I'm optimistically closing this as we're not able to reproduce it, but feel free to reopen :)

**Closed by diegocstn** 2021-08-24 00:48 UTC
Labels: pending-response, datastore
