### ISSUE TITLE
DataStore/API get list of associated type by parent id

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#697] opened 2020-08-07 20:03 UTC
for now, regardless of walk depth, we should have support for querying the list of comments with a filter on post.id. Currently I don't think this is possible from DataStore or APi perspective because the coding key used like `post.id = id` does not correspond to postId that is the actual input to the API.

_Originally posted by @lawmicha in https://github.com/aws-amplify/amplify-ios/issues/681#issuecomment-670690205_

**Comment by drochetti** [comment] 2020-08-11 23:42
This is a duplicate of https://github.com/aws-amplify/amplify-ios/issues/698

**Closed by drochetti** 2020-08-11 23:42 UTC
Labels: api, datastore, duplicate
