### ISSUE TITLE
Reduce the amount of log information when no log Amplify.Logging.logLevel is defined when runnign DataStore operations

### ISSUE THREAD

**Issue by rochabr** [aws-amplify/amplify-ios#1094] opened 2021-03-09 05:04 UTC
**Is your feature request related to a problem? Please describe.**
If Amplify.Logging.logLevel is not specified before configuring Amplify, the information logged to the developer is minimal or nonexistent, except in DataStore operations. Currently, a save operation generates 34 log lines that are useless to the developer who is only interested in a success or failed operation.

**Describe the solution you'd like**
Remove the verbosity from the operation log to none, unless the user specifies it before configuring the plugin.

**Describe alternatives you've considered**
Changing the log level. The lowest one(info), generates the same amount of log lines or more.

**Additional context**
N/A

**Comment by palpatim** [comment] 2021-03-09 16:32
@rochabr Can you share some details of your configuration where you see this behavior? In a simple DataStore only app with no configuration beyond adding a DataStore plugin and invoking `Amplify.configure()`, I don't see any log messages at all, which is what I'd expect. In addition to your configuration code snippets and `DataStore.save()` call, please be sure to include the version of Amplify you're using.

**Comment by rochabr** [comment] 2021-03-09 17:28
Init


```
init() {
        do{
            //Auth
            try Amplify.add(plugin:AWSCognitoAuthPlugin())

            //DataStore
            let models = AmplifyModels()
            let dataStorePlugin = AWSDataStorePlugin(modelRegistration: models)
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.add(plugin: AWSAPIPlugin())
            
            //analytics
            try Amplify.add(plugin: AWSPinpointAnalyticsPlugin())
            
            //configure plugins
            try Amplify.configure()
            print("Amplify succesfully configured")
        } catch {
            print("could not initialize amplify", error)
        }
}
```


DataStore.save()

```
func save(){
        
        let deal = Deal(
            name: name,
            category: categories[selectedCategory]
        )
        
        Amplify.DataStore.save(deal) {
            switch $0 {
            case .success(let deal):
                print("Added post with id: \(deal.id)")
                deals.append(deal)
                self.showModal.toggle()
            case .failure(let error):
                print("Error adding deal with Error: \(error.localizedDescription)")
            }
        }
    }
```

Podfile.lock
```
PODS:
  - Amplify (1.6.1):
    - Amplify/Default (= 1.6.1)
  - Amplify/Default (1.6.1)
  - AmplifyPlugins/AWSAPIPlugin (1.6.1):
    - AppSyncRealTimeClient (~> 1.4.0)
    - AWSCore (~> 2.23.0)
    - AWSPluginsCore (= 1.6.1)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.6.1):
    - AWSAuthCore (~> 2.23.0)
    - AWSCognitoIdentityProvider (~> 2.23.0)
    - AWSCognitoIdentityProviderASF (~> 2.23.0)
    - AWSCore (~> 2.23.0)
    - AWSMobileClient (~> 2.23.0)
    - AWSPluginsCore (= 1.6.1)
  - AmplifyPlugins/AWSDataStorePlugin (1.6.1):
    - AWSCore (~> 2.23.0)
    - AWSPluginsCore (= 1.6.1)
    - SQLite.swift (~> 0.12.0)
  - AmplifyPlugins/AWSPinpointAnalyticsPlugin (1.6.1):
    - AWSCore (~> 2.23.0)
    - AWSPinpoint (~> 2.23.0)
    - AWSPluginsCore (= 1.6.1)
  - AppSyncRealTimeClient (1.4.3):
    - Starscream (~> 3.1.0)
  - AWSAuthCore (2.23.1):
    - AWSCore (= 2.23.1)
  - AWSCognitoIdentityProvider (2.23.1):
    - AWSCognitoIdentityProviderASF (= 2.23.1)
    - AWSCore (= 2.23.1)
  - AWSCognitoIdentityProviderASF (2.23.1)
  - AWSCore (2.23.1)
  - AWSMobileClient (2.23.1):
    - AWSAuthCore (= 2.23.1)
    - AWSCognitoIdentityProvider (= 2.23.1)
    - AWSCognitoIdentityProviderASF (= 2.23.1)
    - AWSCore (= 2.23.1)
  - AWSPinpoint (2.23.1):
    - AWSCore (= 2.23.1)
  - AWSPluginsCore (1.6.1):
    - Amplify (= 1.6.1)
    - AWSCore (~> 2.23.0)
  - SQLite.swift (0.12.2):
    - SQLite.swift/standard (= 0.12.2)
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.1.1)

DEPENDENCIES:
  - Amplify
  - AmplifyPlugins/AWSAPIPlugin
  - AmplifyPlugins/AWSCognitoAuthPlugin
  - AmplifyPlugins/AWSDataStorePlugin
  - AmplifyPlugins/AWSPinpointAnalyticsPlugin

SPEC REPOS:
  trunk:
    - Amplify
    - AmplifyPlugins
    - AppSyncRealTimeClient
    - AWSAuthCore
    - AWSCognitoIdentityProvider
    - AWSCognitoIdentityProviderASF
    - AWSCore
    - AWSMobileClient
    - AWSPinpoint
    - AWSPluginsCore
    - SQLite.swift
    - Starscream

SPEC CHECKSUMS:
  Amplify: 4d0c3b0871e1f268c81ce5e9b65532df0a013900
  AmplifyPlugins: 51dfaeafe662cd571c4d4dfd3bdc5987fef2d5a7
  AppSyncRealTimeClient: 04df4dffe57cfbd06da336d0bfcd5641ba9adcb5
  AWSAuthCore: d9f9c418df00f45f399e407dc6c2bce33870b0af
  AWSCognitoIdentityProvider: 8bf316cc96554d4c88ca4b1dcae0589923fb95f5
  AWSCognitoIdentityProviderASF: f9b0d373dfce6d5395f0b69f2301f5db927d9fc8
  AWSCore: 48bf561f5fb3616ef42c1f7f3eeb4b502d11f69d
  AWSMobileClient: ffe1179b9e6d5db7cea3f807df7d47f5d00a5c65
  AWSPinpoint: a89df232548a0634def16dc4963d8493ff07c2a1
  AWSPluginsCore: f41f8a478fe3fd8839ec16278b86dededefb0628
  SQLite.swift: d2b4642190917051ce6bd1d49aab565fe794eea3
  Starscream: 4bb2f9942274833f7b4d296a55504dcfc7edb7b0

PODFILE CHECKSUM: 91f2ac6758af23164fe47719fb5bee4d726c5739

COCOAPODS: 1.10.1
```

**Comment by palpatim** [comment] 2021-03-09 17:44
Thanks. I installed the same plugins and still can't confirm this behavior. What is the actual log messages you are seeing?

I do note that we have some extraneous log output from the AppSyncRealTimeClient as reported on https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/31, but that isn't related to `DataStore.save()` as you report.

**Comment by rochabr** [comment] 2021-03-09 17:56
This is the same issue. It happens to me on any DataStore event, actually, because the real-time sync kicks in. I just used save() as an example.

**Comment by palpatim** [comment] 2021-03-12 15:04
Thanks for clarifying. Resolving this as a dupe of https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/31

**Closed by palpatim** 2021-03-12 15:04 UTC
Labels: datastore, duplicate
