### ISSUE TITLE
Declaration 'resultPublisher' cannot override more than one superclass declaration

### ISSUE THREAD

**Issue by tung-earable** [aws-amplify/amplify-ios#740] opened 2020-08-25 09:00 UTC
**To Reproduce**

Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'AWSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AWSDemo
  pod 'Amplify'
end
```

`pod install` and build

Failed at AmplifyOperation+APIPublishers.swift - line 16

**Comment by palpatim** [comment] 2020-08-25 14:57
Dupe of https://github.com/aws-amplify/amplify-ios/issues/717

Solution: Please upgrade to Xcode 11.4 or greater, or install the Swift 5.2 toolchain in a previous version of Xcode.

**Closed by palpatim** 2020-08-25 14:57 UTC

**Comment by tung-earable** [comment] 2020-08-25 14:59
Thanks so much!
