### ISSUE TITLE
Upload to S3 slows to halt after queueing multiple files

### ISSUE THREAD

**Issue by jamescrowley** [aws-amplify/amplify-ios#1279] opened 2021-06-17 08:12 UTC
**Describe the bug**

I need to queue several thousand images for background upload into S3. However, the more files I add by calling `Amplify.Storage.uploadFile` the slower everything seems to get - after about 20 it essentially seem to be doing little at all (ie hardly get any file progress notifications, and zero completions).

It looks as if there's no queueing mechanism and Amplify is just trying to upload everything at once. I'm not sure if this is a bug or a limitation - but could you confirm how to approach this?

I could use an OperationQueue locally, but then I lose the ability for these jobs to continue in the background. 

I could compress it all into one big zip file and extract on the other end, but then on a slow internet connection they won't receive any of the data until the whole lot has gone up.

**To Reproduce**
1. upload multiple files using Amplify.Storage.uploadFile simultaneously

**Observed Behavior**

The more files I add by calling `Amplify.Storage.uploadFile` the slower everything seems to get. 

**Expected Behavior**

I should be able to queue multiple files for background uploading using Amplify.storage.uploadFile

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

Storage

**Comment by palpatim** [comment] 2021-06-17 14:18
Thanks for reporting this, we'll need to investigate. I haven't reviewed the code in a while, but my recollection is that we submit each upload task to an NSURLSession configured for background operation as soon as Amplify receives the request. The OS should manage parallel tasks transparently, so it's unexpected that we'd see a problem handling multiple tasks.

**Comment by jamescrowley** [comment] 2021-06-18 00:02
@palpatim thanks, let me know if I can do anything to assist

**Comment by jamescrowley** [comment] 2021-06-18 05:08
It looks like these could be getting stuck on getIdentityId. Currently these are being uploaded to using the .public permission with no sign in. I'm due to add auth shortly so I'll see if that has any impact.

<img width="321" alt="Captura de pantalla 2021-06-18 a las 15 07 12" src="https://user-images.githubusercontent.com/509533/122509304-e6004e80-d046-11eb-82a2-5770dff16bea.png">

**Comment by palpatim** [comment] 2021-06-18 23:25
Thanks for the additional context. I think you're getting caught by "Issue 1" as described in https://github.com/aws-amplify/aws-sdk-ios/issues/1691#issuecomment-528079946

The workaround for that behavior is to ensure the system has current credentials cached in memory **before** starting large batch operations. In the legacy SDK, that would mean issuing a call to `[credentialsProvider credentials]`, but in Amplify, you can use the `get` as noted [here](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios):

```swift
import AWSPluginsCore

// Note that this call is asynchronous. Don't start generating Presigned URLs until it has completed
Amplify.Auth.fetchAuthSession { result in
    do {
        let session = try result.get()
        if let awsCredentialsProvider = session as? AuthAWSCredentialsProvider {
            let credentials = try awsCredentialsProvider.getAWSCredentials().get()
            print("Credentials are now cached--presigned URL generation should go much faster now")
        }
    } catch {
        print("Fetch auth session failed with error - \(error)")
    }
}
```

You might also look at the call to `getIdentityId` in the same code snippet in the docs. My recollection is that `getAWSCredentials` will populate the identity ID as well, but I can't remember for sure.

Let me know if that helps.

**Comment by jamescrowley** [comment] 2021-06-19 22:39
@palpatim thanks. This is strange. I've included the getAWSCredentials/getIdentityId call before I send the batch uploads (ensuring I wait for the result). This has helped, in that I can bump the 'max' uploads up to around 100 now, but bump it up to 150 and everything grinds to a halt. 

It's feeling very much like there's a deadlock.

In an 'unhealthy' scenario, I get zero progress updates. I can see 75 threads - one main thread, one uikit eventfetch thread, and the rest stuck are threads stuck on AWSAuthService.getIdentityId, as shown in my original screenshot.

In a 'healthy' scenario, I immediately get progress updates. I can see 65 threads, half of which are '__workq_kernreturn' and the other half are clearly progressed from getIdentityId.

<img width="515" alt="Captura de pantalla 2021-06-20 a las 8 38 31" src="https://user-images.githubusercontent.com/509533/122657013-0513f300-d1a3-11eb-9c98-91f6addfd414.png">

**Comment by jamescrowley** [comment] 2021-07-06 03:45
Ping to keep this issue open

**Comment by royjit** [comment] 2021-09-13 18:11
Related bug ? - https://github.com/aws-amplify/amplify-ios/issues/1418

**Comment by brennanMKE** [comment] 2021-11-08 18:04
@jamescrowley I've prepared a sample project for you which reproduces this problem and provides a solution to prevent the hang. What is happening is many operations run by Amplify make calls to `getIdentity()` which is a blocking function with a semaphore. When many uploads are running what is happening is many DispatchQueues become blocked on this DispatchSempore. These mechanisms operate on top of threads and you will see when this is happening there are many more threads the usual. When a queue wants to run work and there are not enough threads in the thread pool the system will create a new thread for it, but it does have a limit. This hang is caused by this limit. We've identified this problem and we are currently working through a [PR](https://github.com/aws-amplify/amplify-ios/pull/1502).

For now, I recommend using the approach in the sample project below. You will see at the top of `Plethora.swift` there are 3 values that you can change to try out different scenarios. The mode supports `.immediate` and `.queued` where the queued model will allow up uploads to run up to a limit based on the currently available processor cores. For recent hardware models this means there will be many cores available to run threads for many concurrent uploads. For older dual core iPhones it will be limited to 2 concurrent uploads. This queued approach operates reliably and as quickly as possible on hardware with more cores and capacity to run more threads.

Even with the coming changes to make `getIdentity()` a non-blocking function I would encourage using this approach so that you have control of what your app is doing. You could adapt this code to impose limits on any of the operations your app is running.

[1279-upload-many-files.zip](https://github.com/aws-amplify/amplify-ios/files/7498978/1279-upload-many-files.zip)

## About the Code

You will see that `Uploader` is a protocol with an extension which implements functions so it has there is common behavior between `ImmediateUploader` and `QueuedUploader`. The difference is that when `uploadFile(fileURL:)` is run the queued version will add the `fileURL` to an array for pending uploads and then calls `processPending` to start uploads until it reaches the limit. When every upload is completed it will call `processPending` again and once there are no more pending uploads it will finish. The caller is updated with `UploaderEvent` which covers the lifecycle of the uploader which works well with SwiftUI. The UI shows a progress view for every active upload. Once the state goes to `.idle` it sends an event which allows the UI to be reach the end state.

Once all updates have finished there is a cleanup process which removes all files on the device and in the S3 bucket where the suffix is `-Plethora.bin` so it won't take up space after you run many test sequences. You can try out how this code performs with a lot of uploads, small or large files and with the 2 supported modes to observe the behavior. I've included logs which show how the app will hang when threads are blocked and unable to continue.

I hope this helps. Please let us know how it works out for you.

**Comment by jamescrowley** [comment] 2021-11-08 23:26
thanks @brennanMKE , much appreciated - I'll have a dig into the code.

Am I right in thinking however, that this will require the app to remain in the foreground for subsequent uploads to be queued, or is it possible to ensure the app 'wakes' to continue uploading? This was the primary reason I had to make the whole lot queue at once, rather than a more 'controlled' manner.

**Comment by brennanMKE** [comment] 2021-11-09 19:41
@jamescrowley That's a good question. I will update this sample project to include the AppDelegate integration so it can support background transfers. I can run it on a device and put the app into the background while the uploads are running. I will also put in OSLog so that I can observe the activities from the Console app even if I do not have the Xcode debugger connected. That should show if this will be allowed or not.

Either it will just work or if it does not work I could consider doing it as a [background task](https://developer.apple.com/documentation/backgroundtasks) which may be allowed to start a new request with URLSession.

**Comment by brennanMKE** [comment] 2021-11-09 19:50
@jamescrowley You may also be interested in this [gist](https://gist.github.com/brennanMKE/fc0f280ac7c3a8a1150ae6bc0bc21c1d) which builds on top of Apple's OperationQueue which is able to limit the number of concurrent operations. Apple's `BlockOperation` does not support async work so I created this implementation to make it easier to define an operation with a simple closure which can run with async behavior. The limit can still be set using the processor count like in the sample code I shared previously. It would require much less custom code and run on top of Apple OperationQueue which may offer some additional benefits while eliminating custom code.

**Comment by jamescrowley** [comment] 2021-11-09 22:40
@brennanMKE OperationQueue is actually where I first started out with all of this - but couldn’t find a way to enable the app to wake up and continue to queue new uploads as the initial ones completed.

**Comment by brennanMKE** [comment] 2021-11-11 01:06
@jamescrowley I've been digging deeper into the root cause and we are going to be making more updates. The above issue is one of the changes.

I do recommend looking into `BGTaskScheduler` for your needs. I attempted it with this updated sample project which includes a logger which uses OSLog so you can observe this app from the Console app. Just filter to _Plethora_ to see just these logs. To handle the background task properly you'd want to keep track of the work you want the app to do in the background. You can start the work while the app is in the foreground and any network requests which did not get passed onto the OS before the app is put into the background you could submit a request to run a background task later. That task can process additional network requests. You can require the device be on WiFi and power so your app does not contribute to draining the battery.

One technique I know about is detecting when the device is on WiFi and powered while it is in use. You can set a geofence and have it trigger the app to be launched in the background which can trigger work to be done. It can give your app more opportunities to process network requests when it is ideal.

We will work through the improvements to performance so that your app is able to complete more of the background upload requests before the app enters the background.

You could take the change that I prepared for the PR and try it out with your code to see how it performs. If you can observe a noticeable improvement I'd like to know.

[1279-upload-many-files.zip](https://github.com/aws-amplify/amplify-ios/files/7516853/1279-upload-many-files.zip)

**Comment by brennanMKE** [comment] 2021-11-11 01:11
On my dual core iPhone 7 I am seeing these results after running 20 uploads. The very low number of threads shows it is not triggering thread explosion. Before I was seeing many threads being created and running concurrently and remaining after the operations were completed. I also ran this test on the Simulator with 12 cores and it performs even more quickly and with very few threads. Generally fewer than 30 threads is good. I was seeing more than 50 threads before. Now it is under 20.

## Queued Mode

<img width="745" alt="Thread count after queued uploads" src="https://user-images.githubusercontent.com/277419/141218604-15bdfc1b-d8e7-4a17-94de-eb6280c04476.png">

## Immediate Mode

<img width="745" alt="Thread count after immediate uploads" src="https://user-images.githubusercontent.com/277419/141218621-669c412d-2735-4b7f-b270-e4ac2c492288.png">

**Comment by brennanMKE** [comment] 2021-11-11 17:37
What I am observing is that with the recent changes I've made in Amplify Storage and AWSMobileClient the total number of concurrent threads is reduced which prevents thread explosion and the hang being observed before. It also appears that the value below works well for operations. Since threads are typically idle it appears that 2 threads per core does not degrade performance. With 12 cores I was finding the top limit was 64 threads which is 4x the cores on this Mac running the Simulator. This may be close to an optimal factor. Given that other work will be done ti would be best to keep the constraint reasonable. For a dual core iPhone it would allow 4 concurrent operations to be running on an Operation Queue.

```swift
queue.maxConcurrentOperationCount = ProcessInfo.processInfo.activeProcessorCount * 2
```

**Comment by brennanMKE** [comment] 2021-11-11 17:37
What I am observing is that with the recent changes I've made in Amplify Storage and AWSMobileClient the total number of concurrent threads is reduced which prevents thread explosion and the hang being observed before. It also appears that the value below works well for operations. Since threads are typically idle it appears that 2 threads per core does not degrade performance. With 12 cores I was finding the top limit was 64 threads which is 4x the cores on this Mac running the Simulator. This may be close to an optimal factor. Given that other work will be done ti would be best to keep the constraint reasonable. For a dual core iPhone it would allow 4 concurrent operations to be running on an Operation Queue.

```swift
queue.maxConcurrentOperationCount = ProcessInfo.processInfo.activeProcessorCount * 2
```

**Comment by jamescrowley** [comment] 2021-11-22 22:38
@brennanMKE I'll be giving this a go, as we're now hitting intermittent "pmap_enter failed with resource shortage" issues with uploads which I'm guessing could be down to the number of threads. I'll let you know how I get on.

**Comment by brennanMKE** [comment] 2021-11-28 21:38
We are working on multiple updates which will improve performance. Another way to approach this problem is with Combine which [supports back pressure](https://developer.apple.com/documentation/combine/processing-published-elements-with-subscribers). You can limit concurrent processing this way in a more elegant way without creating a complex data structure. With your Subscriber you can control Demand to keep it within the working limits of the runtime. With the current blocking code the hang prevents a lot of transfer requests being started at the same time. It should be a very small time to handle each request, but it just cannot handle them when it uses too many threads.

**Comment by brennanMKE** [comment] 2021-12-07 19:05
#3872

@jamescrowley This update has been merged and will be included in the next release. There are other PRs coming to Amplify which also change from blocking functions to non-blocking functions which eliminates `wait()` calls. These changes should make for a much more responsive runtime.

**Comment by brennanMKE** [comment] 2021-12-13 18:32
[PR #3872](https://github.com/aws-amplify/aws-sdk-ios/pull/3872) has been released with [2.26.6](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.26.6).

**Closed by brennanMKE** 2021-12-13 18:32 UTC
Labels: bug, pending-response, storage

**Comment by jamescrowley** [comment] 2021-12-13 22:39
Many thanks @brennanMKE

**Comment by jamescrowley** [comment] 2021-12-14 02:05
@brennanMKE any chance you can get the release pushed here so it will appear in the Swift Package Manager? https://github.com/aws-amplify/aws-sdk-ios-spm/pull/37 Many thanks

**Comment by harsh62** [comment] 2022-01-21 16:28
@jamescrowley https://github.com/aws-amplify/aws-sdk-ios-spm has released the next version too ..
