### ISSUE TITLE
UIApplication.shared unavailable in application extensions on Xcode 13 beta 4

### ISSUE THREAD

**Issue by alexandru7** [aws-amplify/amplify-ios#1348] opened 2021-07-31 01:17 UTC
### Describe the bug

Looks like since Xcode 13 beta 3, UIApplication.shared can not be referenced directly without marking the referencing code as unavailable in application extensions.
I'm getting the following error when I build:
`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`
Relevant link:
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create new project in Xcode 13 beta 4
2. Add Amplify packages using SPM
3. Add Amplify to project using `amplify init`
4. Build the project
```

### Expected behavior

Project should build.

### Amplify Framework Version

1.13.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.5

### CLI version

5.2.1

### Xcode version

13.0 beta 4 (13A5201i)

### Device

iPhone12-simulator

### iOS Version

15.0

**Comment by chriisong** [comment] 2021-08-06 04:15
the solution is to add `@available(iOSApplicationExtension, unavailable)`. If anyone from @aws-amplify-ops can resolve this issue so we can continue testing with Xcode 13, that would be fantastic...

**Comment by Bersaelor** [comment] 2021-08-10 12:21
I'd like to add that this is not a beta issue but will stay an issue for everyone updating to Xcode 13 in September.

**Comment by cpiro** [comment] 2021-08-10 18:51
To work around this issue, we check out a local copy of `amplify-ios`, override the SPM package dependency by adding that local directory, and apply this [patch](https://gist.github.com/cpiro/893c34bc855653f141f284728fc0a387). You may have to do this for many of your dependencies, but fortunately for us in the weeks since Xcode 13.0b3 introduced this issue, our upstream vendors (except AWS) have already fixed their packages.

One gotcha: it's not possible to add a one-liner `available` when the relevant code is deeper inside a function. Wrapping the logging plugin with `PersistentLoggingPlugin` when `isDevMenuEnabled` in `DEBUG` is an example of this. We don't use the dev menu functionality, so the patch above comments it out rather than restructuring the code so only the relevant bits can be marked unavailable.

**Comment by Bersaelor** [comment] 2021-08-10 18:58
So for now I'm using https://github.com/maianhvu/amplify-ios/tree/patch-uiapp-shared, thanks to @maianhvu :)

**Comment by maianhvu** [comment] 2021-08-11 00:52
> So for now I'm using https://github.com/maianhvu/amplify-ios/tree/patch-uiapp-shared, thanks to @maianhvu :)

Thanks for the mention! It was a quick and dirty fix I made in stealth mode to get my app up and running. Sorry for the insane amount of prop-drilling, I guess I can patch it up a little with environment variables and see if the folks over at AWS appreciate this solution.

**Comment by mangoCARE** [comment] 2021-08-13 15:53
So Xcode 13 beta 5 seemed to have fixed this issue:

```
You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)
```

Not sure if this is going to be a permanent solution to whatever this thread was addressing, or if we should continue to be on the look out for issues around this

**Comment by sparklellama** [comment] 2021-08-16 04:05
This appears to still be an issue if you are making Swift Packages.  My Swift Package project which relies on Amplify compiles under under Xcode 12.  Under Xcode 13 beta 5, Amplify fails to build its Issue Reporter class with: `'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`  This happens in 2 places where `UIApplication.shared` is referenced.

Do I need to rewrite the app using manual API calls and avoid Amplify?  I'm not sure what this error really means.

**Comment by maianhvu** [comment] 2021-08-16 04:19
> Do I need to rewrite the app using manual API calls and avoid Amplify? I'm not sure what this error really means.

That seems like throwing the baby out with the bath water, but tbh Amplify is giving me way too much trouble than it solves my problems as well.

The issue comes from Xcode thinking that we're building the app for App Extensions (e.g. notification handlers, share) where calls to `UIApplication.shared` are prohibited. 

Admittedly, this is a code smell in my opinion and most packages should ideally not call `UIApplication.shared` internally, and instead use dependency injection to let the host app decide what to do in situations requiring such a global singleton access. What I've done in my fork above was to do just that--abstracting the calls to `UIApplication.shared` to an protocol that the host app can implement.

I haven't submitted a PR yet because this seems like an Xcode issue and likely to be resolved in the future. Per @mangoCARE 's suggestion I have downloaded Xcode 13 beta 5 but the issue still persists on my M1 MacBook Pro using Swift Package Manager.

**Comment by sparklellama** [comment] 2021-08-16 04:50
Yes I would agree that it's odd that Amplify does things like using the Application singleton, which you'd expect to be handled by the host app.

**Comment by harsh62** [comment] 2021-09-08 17:28
> This appears to still be an issue if you are making Swift Packages. My Swift Package project which relies on Amplify compiles under under Xcode 12. Under Xcode 13 beta 5, Amplify fails to build its Issue Reporter class with: `'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.` This happens in 2 places where `UIApplication.shared` is referenced.
> 
> Do I need to rewrite the app using manual API calls and avoid Amplify? I'm not sure what this error really means.

It would be nice if you could provide a demo app showcasing the issue when building it in a package. I have tried a couple of times, and it seems to be working fine.

**Comment by alexandru7** [comment] 2021-09-09 17:19
It looks like this change was reverted in Xcode 13 beta 5 according to the release notes:

> You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)

I was able to pull the most recent version of amplify in my project and it compiled/ran without any issues on Xcode 13 beta 5.
I'll leave the ticket open until we get the GM of Xcode 13 in case they change their minds again.

**Comment by everestman27** [comment] 2021-09-09 20:16
I am trying to run tthe IOS Amplify tutorial in Xcode13beta4 and getting a number of amplify package related errors - ex. errror1 .../ios/Amplify/DevMenu/View/IssueReporter.swift:110:23: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.  error2 -...ios/Amplify/DevMenu/View/IssueReporter.swift:110:30: 'open(_:options:completionHandler:)' is unavailable in application extensions for iOS..

**Comment by harsh62** [comment] 2021-09-10 18:16
> I am trying to run tthe IOS Amplify tutorial in Xcode13beta4 and getting a number of amplify package related errors - ex. errror1 .../ios/Amplify/DevMenu/View/IssueReporter.swift:110:23: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead. error2 -...ios/Amplify/DevMenu/View/IssueReporter.swift:110:30: 'open(_:options:completionHandler:)' is unavailable in application extensions for iOS..

Please use the latest beta. It seems that the recent version have reverted the cause of the issue.

**Closed** 2021-09-24 17:13 UTC
Labels: build, closing soon, follow up
