### ISSUE TITLE
How to delete DataStore items correctly?

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#918] opened 2020-11-30 08:55 UTC
We are using DataStore to fetch data, which works pretty well. Now we added a function, where we want to delete data. 
But instead of deleting them, every item gets an time to live entry and its _deleted flag set to true. 
This wouldn't be an issue, when the items with the _deleted flag doesn't get fetched anymore, but they get fetched. 
So the problem is now, when an user deletes an item from a list, refreshes the list, the item still exists.
How can we disable these automatic ttl and _deleted flags, so the item gets instantly deleted or even better, how can we filter items, which has their _deleted flat set to true?

**Comment by drochetti** [comment] 2020-11-30 19:10
@chris-mds can you clarify a few things?

> Now we added a function, where we want to delete data.

Do you mean a Lambda function? If so, are you using the AppSync JS client to do so? If yes, are you including the metadata fields in your selection set?

> This wouldn't be an issue, when the items with the _deleted flag doesn't get fetched anymore, but they get fetched.

When you say _fetch_ do you mean a `DataStore.query`, a GraphQL list operation through the AppSync client or a direct query in DynamoDB?

**Comment by chris-mds** [comment] 2020-11-30 19:46
Hi @drochetti,

both. Lambda and iOS DataStore.

Fetch mean a `DataStore.query`

**Comment by wooj2** [comment] 2020-12-18 18:26
Hi @chris-mds ,

From your lambda, are you accessing the dynamo table directly, or using the AppSync service to delete these items?

Thanks!

**Comment by chris-mds** [comment] 2020-12-29 08:02
Hi @wooj2,

We are using the AppSync service within our lambda. We recently created a new backend and expected nearly the same weird behavior. 
Lets say we have a list of users. Now we delete one user from the list via our Lambda. The user is still in the list, because we are not handling the delete event from our subscription. So far so good. But now we refresh the list with DataStore.query and the user is still there. After this refresh the user should disappear?
After a restart off the app the user finally disappears.

**Comment by palpatim** [comment] 2021-01-11 15:24
@chris-mds 

> The user is still in the list, because we are not handling the delete event from our subscription.

If you're using Amplify DataStore, any deletes processed by the AppSync service would be processed automatically, assuming your current user is authorized to subscribe. Can you clarify what you mean by this statement?

> But now we refresh the list with DataStore.query and the user is still there.

`DataStore.query` always operates on local data, not server data--it relies on the automatically managed subscriptions to keep the local store consistent. If deletes aren't being processed for some reason, then the local store would still have the record.

> After a restart off the app the user finally disappears.

This could be the result of DataStore performing a "sync query" on startup to retrieve all changes since the last successful sync. Assuming your restart is happening within the "sync interval" (default = 24 hours since last sync), then the deletion would be retrieved and applied by that startup sync query.

I think the crux of the problem is related to your statement "we are not handling the delete event from our subscription", so any clarification you can provide there would be helpful.

**Comment by chris-mds** [comment] 2021-01-20 12:48
Hi @palpatim ,

> If you're using Amplify DataStore, any deletes processed by the AppSync service would be processed automatically, assuming your current user is authorized to subscribe. Can you clarify what you mean by this statement?

I mean, that we get the onDelete event in our app, but we don't handle it / coded any action to this. This means it is correct, that the user is still in our list. Now I thought, that after a query we fetch the list of users again and the deleted user should disappear. But as you mentioned now

> DataStore.query always operates on local data, not server data--it relies on the automatically managed subscriptions to keep the local store consistent. If deletes aren't being processed for some reason, then the local store would still have the record.

it makes sense, that the user is still in the list. 
So we need to call `DataStore.delete` , when we received the subscription event? This sounds a bit weird for me, because we are performing the delete request twice? One from backend and one from our app? Could this end in an infinite loop?

**Comment by palpatim** [comment] 2021-01-22 23:29
@chris-mds You definitely should not have to call `DataStore.delete()` twice. DataStore handles record deletion from all of the following cases:

- **Initial query against an empty local data store** - the service will not return a deleted record
- **Sync query against a populated data store** - if the record was deleted since the last full sync, the service returns a tombstone record (one with the `_deleted` flag set). DataStore sync engine recognizes this tombstone record and deletes it locally. A subsequent DataStore query would show the record deleted
- **Delete mutation received on a subscription** - the service sends delete mutations with tombstone flags on its automatically-established `onDelete` subscription, and handles the mutation as above by deleting the record locally
- **Delete mutation initiated locally via `DataStore.delete()` - DataStore immediately deletes the record locally and enqueues a delete mutation for processing by the service. Assuming no conflicts or errors, the service would process the delete and send delete responses and mutations as appropriate, which of course would not apply

Some questions to try to track down this weirdness:
- Is your GraphQL schema appropriately annotated with `@model`? https://docs.amplify.aws/cli/graphql-transformer/model
- Did you provision your API with conflict resolution enabled? https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios#option-2-use-amplify-cli
    > Make sure you respond **Yes, I want to make some additional changes** when prompted for **advanced settings** and turn on **conflict detection**. This setting is **required** when syncing data to the cloud since the conflict resolution strategy is what allows local data to be reconciled with data from the cloud backend.
- When you say:
    > I mean, that we get the onDelete event in our app

    How are you tracking the `onDelete` event? Is this coming from your DataStore.publisher (and thus represents a locally applied change), or on a subscription you've set up somewhere? If the latter, how is that subscription established, since we don't support operating on the API directly when you're using DataStore?
- Is the behavior the same whether you initiate the deletion...
  - From the Lambda?
    - If you see the problem with Lambda-initiated deletes, what selection set are you using for the delete mutation?
  - Locally from DataStore?
    - If you see the problem with DataStore initiated deletes, we fully expect there to be at least a brief period of time where the record disappears locally. Do you confirm that behavior, or are you saying the delete is never processed locally? If not, are you getting any error on your `DataStore.delete()` callback?
  - Manually via the AppSync console?
    - Same question as for Lambda: what selection set are you using if manual deletes aren't being processed?

Obviously we're a bit stymied by the behavior you're reporting, since we've successfully processed deletions in many scenarios without problems. At this point I suspect either a configuration issue (e.g., an incorrect or unexpected config in the AppSync API, model schema, etc), a runtime usage issue (e.g., an invalid or incomplete selection set), or an unhandled error that might shed more light on the underlying issue. But more investigation will help us narrow it down.

**Comment by chris-mds** [comment] 2021-02-06 18:50
@palpatim  Sorry for late response,

> Is your GraphQL schema appropriately annotated with @model? https://docs.amplify.aws/cli/graphql-transformer/model

Yes!

> Did you provision your API with conflict resolution enabled?

Yes!

> How are you tracking the onDelete event?

It is coming from the DataStore.publisher. We don't set up a subscription to this event

>Is the behavior the same whether you initiate the deletion...
> - From the Lambda?

When the delete method is called from our lambda, we successfully receive the DataStore.publisher event. The _deleted flag is also set in the dataset on DynamoDB as expected

> Locally from DataStore?

You mean the` Datastore.delete() `method called directly from our App? 
Yes there was a period of time, but it was about 30 secounds and this would result in a bad user experience. Users are expecting an instant delete instead of see the result of their delete request multiple seconds later. They will try to delete the item again and again, because it doesn't disappear.

> Manually via the AppSync console?

Same behavior like from lambda

I will investigate this weird behavior more next week and provide some more detailed informations..
Thank you so far!

**Comment by palpatim** [comment] 2021-02-08 20:33
Reopening while you gather info. In the meantime:

> You mean the`Datastore.delete()`method called directly from our App?
> Yes there was a period of time, but it was about 30 secounds and this would result in a bad user experience. Users are expecting an instant delete instead of see the result of their delete request multiple seconds later. They will try to delete the item again and again, because it doesn't disappear.

The DataStore delete immediately processes locally, and should remove it from the local store. What are you using to trigger your UI update?

**Comment by palpatim** [comment] 2021-03-05 18:05
I'm adding the "closing soon" label back to this. @chris-mds please feel free to reopen the issue once you get some more detail and we'll continue investigating.

**Closed** 2021-03-13 00:51 UTC
Labels: closing soon, datastore, question, requesting info

**Comment by afern247** [comment] 2021-08-06 20:57
Any updates on this? I'm getting the same thing... I deleted locally on my app with the following code:

```
func deleteWallet(id: String) async {
        Amplify.DataStore.delete(Wallet.self, withId: id) {
            switch $0 {
            case .success:
                print("✅ Wallet deleted!")
            case .failure(let error):
                print("🛑 Error deleting wallet - \(error.localizedDescription)")
            }
        }
    }

and it's removed locally, now... on the cloud it says deleted: true but it still there... How do I completely remove it? I mean... remove is remove...
```

**Comment by maremoto** [comment] 2021-08-24 12:18
Hi,

I am experiencing the same situation, when I delete an item it is deleted in Datastore (AdminUI stops showing it) but remains in DynamoDb with "_deleted: true" flag.

It is ok as far as you are not retrieving the item in any furter SELECT.

The problem arrises when you are trying to INSERT again the same item, with the same id, then despite of a successful response, the item is no longer inserted in Datastore unless you manually remove it from DynamoDB.

So, is there any way of delete an item from both DynamoDB and Datastore at the same time using IOS SDK? 
I mean delete-delete, no trace of it anymore in anyplace.

(*) Yes, we are using custom ID because whe have to check some integrity and duplicity constraints.

Thanks.

**Comment by afern247** [comment] 2021-08-24 12:26
> Hi,
> 
> I am experiencing the same situation, when I delete an item it is deleted in Datastore (AdminUI stops showing it) but remains in DynamoDb with "_deleted: true" flag.
> 
> It is ok as far as you are not retrieving the item in any furter SELECT.
> 
> The problem arrises when you are trying to INSERT again the same item, with the same id, then despite of a successful response, the item is no longer inserted in Datastore unless you manually remove it from DynamoDB.
> 
> So, is there any way of delete an item from both DynamoDB and Datastore at the same time using IOS SDK?
> I mean delete-delete, no trace of it anymore in anyplace.
> 
> (*) Yes, we are using custom ID because whe have to check some integrity and duplicity constraints.
> 
> Thanks.

not only the id, we are consuming space and junk that we don't need..

**Comment by SimonDziak** [comment] 2022-02-01 17:56
Having the same problem. In DynamoDB with "_deleted: true" flag. Why is it not permanantely removed?

**Comment by mrpatrick** [comment] 2022-02-03 14:53
Is there a way to permanently (instantly) remove items?

**Comment by maxfahl** [comment] 2022-02-28 15:07
> Is there a way to permanently (instantly) remove items?

Would really like to know this as well.

**Comment by DanielZanchi** [comment] 2022-03-26 22:21
Same problem here. 
While fetching list of data, it returns even if **_delete = true**

Why is this happening?

Fetching data via DataStore and via GraphQL (same result).
Tried deleting via API and via DataStore is not deleting but only setting it with **_deleted = true**

**Comment by DanielZanchi** [comment] 2022-03-26 22:22
@palpatim  please re-open issue

**Comment by SimonDziak** [comment] 2022-03-27 00:19
> @palpatim please re-open issue

This is done on purpose with Conflict Detection.

You can disable the "_deleted" field by updating this in the CLI using 'amplify update api' and disabling "Conflict Detection".

**Comment by SimonDziak** [comment] 2022-03-27 00:22
From their documentation:

AWS AppSync currently supports versioning on DynamoDB data sources. Conflict Detection, Conflict Resolution, and Sync operations require a Versioned data source. When you enable versioning on a data source, AWS AppSync will automatically:

Enhance items with object versioning metadata.

Record changes made to items with AWS AppSync mutations to a Delta table.

Maintain deleted items in the Base table with a “tombstone” for a configurable amount of time.

[Read more here](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html)

**Comment by DanielZanchi** [comment] 2022-03-27 09:08
Thank you for the reply.
Ok I will try to disable Conflict Detection but I don't see why getting a list of a table entries should give me as output a deleted item. Or better, there's not way to filter the list to ignore deleted items.

**Comment by SimonDziak** [comment] 2022-03-27 17:41
Yes I agree with you. I’ve tried the same process as you and couldn’t
figure it out either. If you do, please reply in this thread for everyone
to know. Disabling conflict will work.
