### ISSUE TITLE
Compile error codegen - Value type 'Category' cannot have a stored property that recursively contains it

### ISSUE THREAD

**Issue by nielsautrata** [aws-amplify/amplify-ios#1039] opened 2021-01-27 11:04 UTC
**There are model files generated by codegen with compile errors in iOS only** 
Error message: 'Value type 'Category' cannot have a stored property that recursively contains it'.

After the creation of the following schema below, adding the api, pushing and running of amplify codegen models the error appears. It seems that the parent property of the Category causes the error. The error doesn't not appear without the parent property.

**Environment:**
Amplify version: 4.41.2
Dependency Manager: Cocoapods
Swift Version : 5.2

iOS Version: iOS 14.3

````
type Category @model
@key(name: "byParent", fields: ["categoryParentId"])
{
    id: ID!
    categoryParentId: ID!
    name:String
    parent: Category @connection(fields: ["categoryParentId"])
    children: [Category] @connection(keyName: "byParent", fields: ["id"])
}
````

**Comment by palpatim** [comment] 2021-01-27 20:54
Hi @nielsautrata 

This is the same issue as discussed in https://github.com/aws-amplify/amplify-ios/issues/504, which is that Swift structs cannot recursively contain themselves because of the way Swift manages memory for structs.

We're still considering options for this, but unfortunately don't have a good solution for now. The best workaround we've been able to come up with is to model recursive constructs via a separate connection as if you were doing a many-to-many connection. In your example, that would look like in child -> connection -> parent.

I'm going to resolve this as a dupe of #504. If you have any other comments or feedback please feel free to chime in on that issue.

**Closed by palpatim** 2021-01-27 20:54 UTC
