### ISSUE TITLE
AWS DataStore - The app is not working as and when steps followed from the portal - https://aws-amplify.github.io/docs/ios/datastore

### ISSUE THREAD

**Issue by aftabahmed1286** [aws-amplify/amplify-ios#349] opened 2020-01-31 12:36 UTC
**Describe the bug**
The app is crashing with a message 
Fatal error: API category is not configured. Call Amplify.configure() before using any methods on the category.: file /Users/aftabahmed/Desktop/PROJECTS/Bala_Try/AWSDataStore_2/Pods/Amplify/Amplify/Categories/API/AmplifyAPICategory.swift, line 18

**To Reproduce**
1. run the project

**Expected behavior**
Supposed to save data in the Datastore and fetch the data from the DataStore.

**Screenshots**
<img width="1392" alt="SS_1" src="https://user-images.githubusercontent.com/15074638/73539753-30822a80-4454-11ea-8c58-ecb6b572a336.png">

<img width="1392" alt="SS_2" src="https://user-images.githubusercontent.com/15074638/73539778-3f68dd00-4454-11ea-94a7-2f004dc9c653.png">
<img width="1392" alt="SS_3" src="https://user-images.githubusercontent.com/15074638/73539779-3f68dd00-4454-11ea-87bd-a07b88165fed.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.15.1

**Additional context**
I tried AWS Storage. It worked fine

**Comment by drochetti** [comment] 2020-03-13 20:51
Thanks for reporting this issue and providing all the details. I'm reviewing our "Getting Started" guide for iOS and will keep you updated with my findings.

**Comment by drochetti** [comment] 2020-03-16 16:53
@patrickridd I tried to reproduce your error and I could only get the *"Storage category is not configured"* when the config files (`amplifyconfiguration.json` and `awsconfiguration.json`) were not added to Xcode, but in that case I could also see the *"Failed to initialize Amplify with \(error)"* message in `AppDelegate`.

When did you create your project? Can you cleanup the local pods (delete both `Pods/` and `Podfile.lock`) and reinstall them?

During this test I was able to identify several improvements we can make to our docs and I'll follow up with the team so we make them before the official release.

**Comment by drochetti** [comment] 2020-03-16 17:23
@aftabahmed1286 @raduoprea I used the attached project and indeed there's a configuration logic problem on Amplify when the `AWSDataStorePlugin` is configured but the `AWSAPIPlugin` is not. Without API, DataStore is meant to be use the local storage mechanism only, however that's not happening.

I'll work on a fix and follow-up with you.

**Comment by Maybelline** [comment] 2020-03-30 22:49
Hi @drochetti , I'm facing the same problem. Have you been able to fix the configuration logic issue in Amplify?

**Comment by drochetti** [comment] 2020-03-30 23:25
> Hi @drochetti , I'm facing the same problem. Have you been able to fix the configuration logic issue in Amplify?

Hi @Maybelline can you share your configuration code with me? Are you configuring both `AWSDataStorePlugin` and `AWSAPIPlugin`?

**Comment by Maybelline** [comment] 2020-03-31 00:08
@drochetti,

Here is some of the code:
<img width="1440" alt="Screen Shot 2020-03-30 at 4 55 29 PM" src="https://user-images.githubusercontent.com/11788745/77973330-ac5bf000-72a8-11ea-8464-260f1dec5417.png">
<img width="1440" alt="Screen Shot 2020-03-30 at 5 00 20 PM" src="https://user-images.githubusercontent.com/11788745/77973336-b251d100-72a8-11ea-96d6-1bebaa92e867.png">



Both awsconfiguration.json and amplifyconfiguration.json files have just empty curly brackets.

Thanks in advance.

**Comment by drochetti** [comment] 2020-05-29 07:48
@aftabahmed1286 @Maybelline @patrickridd @raduoprea 

We just went GA with Amplify iOS, [v1.0.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0) is officially out. Can you try the [new DataStore tutorial](https://docs.amplify.aws/start/getting-started/native_setup/q/integration/ios) and see if the latest version fix things for you?

We also launched a Discord community, feel free to join us there and hit me up if you have feedback, I would love to hear more about your use-cases. https://discord.gg/Px5YVfQ

**Comment by drochetti** [comment] 2020-06-11 18:24
Closing this issue. Feel free to open a new one if you have problems with the stable version of Amplify.

**Closed by drochetti** 2020-06-11 18:24 UTC
Labels: DataStore, Requesting Feedback

**Comment by sai-kante** [comment] 2020-07-04 20:59
idk why this is closed. I  have the same issue right now. 
since setting up the project, I find a different issue all the time.
All I am doing after I set up the project is change models. I am very disappointed. :|

**Comment by Wilsonilo** [comment] 2020-07-06 20:49
Having same problem. "Storage category is not configured."

**Comment by TheRedCamaro30** [comment] 2020-07-23 16:18
I am experiencing the same problem after following [https://docs.amplify.aws/lib/restapi/getting-started/q/platform/ios#configure-api](the rest API) tutorial. Has anyone figured out an solution. None of the amazon ios-SDKs seem to work as advertised right out of the box.

**Comment by sonjameyer** [comment] 2020-08-13 12:10
I only got this working after adding AWSCognitoAuthPlugin

**Comment by Ezra-Black** [comment] 2020-09-29 22:56
Using AWSAmplify tutorial, can confirm still broke.

**Comment by NickOblec** [comment] 2020-11-15 03:21
Why was this closed? It's still clearly not working.

**Comment by adamsadiq7** [comment] 2021-06-18 11:19
Any more news on this?

**Comment by afern247** [comment] 2021-07-19 10:43
This should not be closed... The app crashes when I try to use the online functions using the AppDelegate. Can someone reopen and take a look, this is NOT fixed.

"Thread 1: Fatal error: Authentication category is not configured. Call Amplify.configure() before using any methods on the category."

The only way to not get this error is to create an init() {} on the Main app, which will not allow for background notifications later on.

**Comment by afern247** [comment] 2021-07-19 10:49
> Any more news on this?

It's been fixed

**Comment by hellensoloviy** [comment] 2022-04-13 08:39
Not working for me too. The same issue.

**Comment by ImranRazak1** [comment] 2022-04-26 23:28
I am having the same issue. Can AWS fix this?

**Comment by shami4622** [comment] 2022-06-20 12:21
i am facing the same issue. not working "Storage category is not configured." ?????

**Comment by adpaladines** [comment] 2023-11-01 15:04
Hello guys.
through try and error I found that if we add AWSDataStorePlugin with other plugins, it always stays like not configured.
If you use it alone like in this example, it works but only if it stays as the only plugin.
inside DataStoreCategory.swift, property `isConfigured` is always false.
Hopping it will be helpful to someone else guys.

```swift
let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
    do {
        try Amplify.add(plugin: dataStorePlugin)
        try Amplify.configure()
        print("Initialized Amplify");
    } catch {
        // simplified error handling for the tutorial
        print("Could not initialize Amplify: \(error)")
    }
``` 

Best regards.

**Comment by adpaladines** [comment] 2023-11-02 13:31
Solved.
It was related with well fixed cloud configuration and do `amplify pull --appId xxxxx --envName xxxxx`
