### ISSUE TITLE
Error: Cannot find module 'amplify-frontend-javascript'

### ISSUE THREAD

**Issue by prmacias** [aws-amplify/amplify-ios#350] opened 2020-03-08 21:43 UTC
**Describe the bug**
Creating base Amplify project
Error: Cannot find module 'amplify-frontend-javascript'

I didn't see any new files in the root project (IOS) -
amplifyconfiguration.json, awsconfiguration.json and amplifyxc.config

This issue is linked to 

https://github.com/aws-amplify/amplify-ios/issues/345

when I built this project for first time then I get this error. If I built it again - got a different error - 

Error: Cannot find module 'amplify-frontend-javascript'

**To Reproduce**
I'm following this guide - https://aws-amplify.github.io/docs/ios/start

Step 1: Configure your app
You can use an existing iOS app or create a new iOS app in Swift as per the steps in prerequisite section.

a. From a terminal window, navigate into your Xcode project’s root application directory and run the following commands:

$ cd ./YOUR_PROJECT_FOLDER
`$ pod init`
b. Open the created Podfile in a text editor and add the pods for the core Amplify Framework components.

```
target :'YOUR-APP-NAME' do
    use_frameworks!

    pod 'amplify-tools'

    pod 'Amplify'
    pod 'AWSPluginsCore'
    pod 'AmplifyPlugins/AWSAPIPlugin'

    # other pods
end
```
c. Install dependencies by running the following command:

`pod install --repo-update`
d. Close your Xcode project and reopen it using ./YOUR-PROJECT-NAME.xcworkspace file. Remember to always use ./YOUR-PROJECT-NAME.xcworkspace to open your Xcode project from now on.

e. Build your Xcode project.

Once the build is successful, three files are generated:

amplifyconfiguration.json and awsconfiguration.json: Rather than configuring each service through a constructor or constants file, the Amplify Framework for iOS supports configuration through centralized files called amplifyconfiguration.json and awsconfiguration.json which define all the regions and service endpoints to communicate.

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: pods
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by lawmicha** [comment] 2020-03-09 18:47
may be related https://github.com/aws-amplify/amplify-cli/issues/3300

**Comment by wooj2** [comment] 2020-03-09 18:53
Hi @prmacias,

I tried to reproduce your error, but was unable to do so.  We suspect you might have an older version of node/npm/amplify.  On my box, I have running the following versions:
```
$ node --version
v10.16.3
$ npm --version
6.13.1
$ amplify --version
4.13.3
```
I don't think I have the latest bleeding-edge, but could you check to see which versions of these tools you have on your machine?

**Comment by prmacias** [comment] 2020-03-09 22:25
@wooj2 

See - https://github.com/aws-amplify/amplify-cli/issues/3580#issuecomment-596637253

I think that is my issue. I'll check on it and let you all know soon.

**Comment by kneekey23** [comment] 2020-03-17 18:41
@prmacias were you able to resolve?

**Comment by prmacias** [comment] 2020-03-17 18:47
@kneekey23 not yet, got occupied with something else. I'll try to get it done by tomorrow.

**Comment by prmacias** [comment] 2020-03-19 18:19
@kneekey23 

I managed to install the amplify without any issues but there are errors related to predictions set up. 

No such module 'AWSPredictionsPlugin'

and there are some issues in ConvertConfiguration, and IdentifyConfiguration files

my pod file - 

 ```
 pod 'amplify-tools'

  pod 'Amplify'
  pod 'AmplifyPlugins'
  pod 'AWSPluginsCore'
  pod 'CoreMLPredictionsPlugin'
  pod 'AWSPredictionsPlugin'
  pod 'AWSMobileClient', '~> 2.12.0'
```

**Comment by kneekey23** [comment] 2020-03-20 20:55
hi @prmacias I am not able to reproduce your issue. did you run `pod install --repo-update` and did you add `import AWSPredictionsPlugin` to the top of the AppDelegate file? I tried to go through the getting started guide with the above pods you gave first and then switch to the podfile you just gave and no luck. I created a sample app in my github repo [here](https://github.com/kneekey23/SwiftPredictions), can you try using that to help you get set up?

**Comment by prmacias** [comment] 2020-03-23 13:09
@kneekey23 

I got your repo pulled and I'm having trouble updating the pod -

`pod install --repo-update`

`[!] No podspec found for `AWSPluginsCore` in `~/Projects/Amplify/amplify-ios``

I updated my pod and still getting this error. Something's amiss in my setup. I double checked the - Ensure you have installed and configured the Amplify CLI and library. What do you mean by library? I installed CLI again and configured it but still getting this error.

**Comment by kneekey23** [comment] 2020-03-23 15:16
hi @prmacias two things here. 1. the reason I had that path in my Podfile was because I was locally testing so yes please remove it as you did 2. Delete all the amplify files from the project before running `amplify init` and then try again. Let me know if that works for you.

**Comment by prmacias** [comment] 2020-03-23 15:52
@kneekey23 

It worked - thanks - I will compare your work with my app to see what's going on. Thanks again!

**Comment by kneekey23** [comment] 2020-03-23 16:04
Closing this issue, please feel free to reopen it if you have further issues.

**Closed by kneekey23** 2020-03-23 16:04 UTC
Labels: Build, Requesting Feedback, bug
