### ISSUE TITLE
Many to Many relations are nil

### ISSUE THREAD

**Issue by jeremyscatigna** [aws-amplify/amplify-ios#839] opened 2020-10-19 06:22 UTC
**Describe the bug**
I am trying to use many to many relations on my schema, which are working well on the AppSync Console on AWS website but always return nil on my IOS app

**To Reproduce**
Here is a part of my schema to show how I handle many to many relations:
```
type Tag @model @auth(rules: [{allow: owner, operations: [create, update, delete]}]) 
@key(name: "byUser", fields: ["userId", "name"]){
  id: ID!
  userId: ID!
  name: String
  clothings: [ClothingTag] @connection(keyName: "byTag", fields: ["id"])
  outfits: [OutfitTag] @connection(keyName: "byTag", fields: ["id"])
}

type Outfit @model @auth(rules: [{allow: owner, operations: [create, update, delete]}]) 
@key(name: "byUser", fields: ["userId", "name"]){
  id: ID!
  userId: ID!
  name: String
  url: String
  image: S3Object
  clothings: [ClothingOutfit] @connection(keyName: "byOutfit", fields: ["id"])
  tags: [OutfitTag] @connection(keyName: "byOutfit", fields: ["id"])
  events: [OutfitEvent] @connection(keyName: "byOutfit", fields: ["id"])
}

type OutfitTag @model
  @key(name: "byOutfit", fields: ["outfitId", "tagId"])
  @key(name: "byTag", fields: ["tagId", "outfitId"]){
  id: ID!
  tagId: ID!
  outfitId: ID!
  outfit: Outfit! @connection(fields: ["outfitId"])
  tag: Tag! @connection(fields: ["tagId"])
}
```
Here is the Swift model generated: 
```
// swiftlint:disable all
import Amplify
import Foundation

public struct Outfit: Model, Identifiable {
  public let id: String
  public var userId: String
  public var name: String?
  public var url: String?
  public var image: S3Object?
  public var clothings: List<ClothingOutfit>?
  public var tags: List<OutfitTag>?
  public var events: List<OutfitEvent>?
  
  public init(id: String = UUID().uuidString,
      userId: String,
      name: String? = nil,
      url: String? = nil,
      image: S3Object? = nil,
      clothings: List<ClothingOutfit>? = [],
      tags: List<OutfitTag>? = [],
      events: List<OutfitEvent>? = []) {
      self.id = id
      self.userId = userId
      self.name = name
      self.url = url
      self.image = image
      self.clothings = clothings
      self.tags = tags
      self.events = events
  }
}
```

Here is the ListOutfits query that is generated:
```
query ListOutfits(
  $filter: ModelOutfitFilterInput
  $limit: Int
  $nextToken: String
) {
  listOutfits(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      userId
      name
      url
      image {
        ...S3Object
      }
      clothings {
        nextToken
      }
      tags {
        nextToken
      }
      events {
        nextToken
      }
      createdAt
      updatedAt
    }
    nextToken
  }
}
```

I have tried to update it to have all the tags properties in it like this: 

```
query ListOutfits(
  $filter: ModelOutfitFilterInput
  $limit: Int
  $nextToken: String
) {
  listOutfits(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      userId
      name
      url
      image {
        ...S3Object
      }
      clothings {
        nextToken
      }
      tags {
        items {
          id
          tag {
            name
          }
        }
        nextToken
      }
      events {
        nextToken
      }
      createdAt
      updatedAt
    }
    nextToken
  }
}
```
then I did an `amplify codegen types`

And here is how I query the list of outfits: 

```
return Amplify.API.query(request: .list(Outfit.self, where: predicate))
                .resultPublisher
                .tryMap { result -> [Outfit] in
                    let value = try result.get()
                    return value
                }
                .receive(on: DispatchQueue.main)
                .eraseToAnyPublisher()
                .map(Event.onOutfitsLoaded)
                .catch { Just(Event.onFailedToLoadOutfits($0)) }
                .eraseToAnyPublisher()
```

But I always receive nil for the tags properties in Outfit
The logs in XCode:

``` 
Shyc.Outfit(id: "23538CD2-379A-4DCA-9B1B-AA67C9F0363C", userId: "95c51add-39f9-4200-8fcb-cf96c99fea1e", name: Optional("Leopard"), url: Optional(""), image: nil, clothings: nil, tags: nil, events: nil)
```

The result in AWS AppSync console: 
```
{
          "id": "23538CD2-379A-4DCA-9B1B-AA67C9F0363C",
          "name": "Leopard",
          "tags": {
            "items": [
              {
                "id": "0CC76017-5A93-4418-B451-4AC866B6AB18",
                "tag": {
                  "name": "Summer"
                }
              }
            ]
          }
        }
```

**Expected behavior**
receive tags values instead of nil

**Comment by jeremyscatigna** [comment] 2020-10-26 13:23
@drochetti Any update on this ?

**Comment by drochetti** [comment] 2020-10-26 23:32
Hey @jeremyscatigna,

Currently, the default queries (`.list(Outfit.self)`, `.get(Outfit.self, byId: '')`) do not fetch the *many* side of a relationship by default due to performance reasons. We are currently evaluating solutions to that, so the developers can control which relationships they want to be fetched during a query, in the meantime a workaround is to create your own query:

```swift
// GraphQLRequest+Outfit.swift

extension GraphQLRequest {

    static func listOutfitWithTags(where predicate: QueryPredicate?) -> GraphQLRequest<[Outfit]> {
        let query = """
        query ListOutfits(
          $filter: ModelOutfitFilterInput
          $limit: Int
          $nextToken: String
        ) {
          listOutfits(filter: $filter, limit: $limit, nextToken: $nextToken) {
            items {
              id
              userId
              name
              url
              image {
                ...S3Object
              }
              clothings {
                nextToken
              }
              tags {
                items {
                  id
                  tag {
                    name
                  }
                }
                nextToken
              }
              events {
                nextToken
              }
              createdAt
              updatedAt
            }
            nextToken
          }
        }
        """
        return GraphQLRequest<[Outfit]>(
            document: document,
            variables: ["filter": predicate.graphQLFilter],
            responseType: [Outfit].self,
            decodePath: "listOutfits.items"
        )
    }

}
```

This is a feature request we're tracking here: https://github.com/aws-amplify/amplify-ios/issues/599
We do intend to make this more configurable so you don't have to define your own queries, in the meantime the code snippet I shared above should work and can be used for any query where you want to control exactly the selection set you want from a query. Read more here: https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios#nested-data

**Comment by jeremyscatigna** [comment] 2020-10-27 07:27
Hey @drochetti 
Thanks for your answer, I tried your solution but it doesn't work I receive:
``` The operation couldn't be completed (Amplify.GraphQLResponseError<Swift.Array<Shyc.Outfit>> error 0.) ```

**Comment by drochetti** [comment] 2020-10-27 07:44
> Hey @drochetti 
> Thanks for your answer, I tried your solution but it doesn't work I receive:
> ``` The operation couldn't be completed (Amplify.GraphQLResponseError<Swift.Array<Shyc.Outfit>> error 0.) ```

Hey @jeremyscatigna, can you provide more details of the error? `GraphQLResponseError.error` has an array of error objects (https://github.com/aws-amplify/amplify-ios/blob/8eef5aa9a80f19580247657ebbea8bbc49374fee/Amplify/Categories/API/Response/GraphQLResponse.swift#L20), you should be able to get more insights from it. But it seems there was something wrong with the query.

**Comment by jeremyscatigna** [comment] 2020-10-27 07:54
@drochetti Found the error object, here is what I have:
```GraphQLResponseError<Array<Outfit>>: Failed to decode GraphQL response to the `ResponseType` Array<Outfit> ```

**Comment by drochetti** [comment] 2020-10-28 00:33
> Found the error object, here is what I have now:
> `GraphQLResponseError<Array<Outfit>>`: Failed to decode GraphQL response to the `ResponseType` `Array<Outfit>`

@jeremyscatigna there's still something missing from the error. Just by looking at this I can't tell what's wrong with the response conversion into the type `[Outfit]`.

Can you try increasing the log level? Also, try inspecting the error object for more clues, interpolating the `error` with a string, or just printing `error.errorDescription` might hide a few details about the root cause. There must be some `DecodeError` in your logs/stacktrace.

```swift
// you can use this to increase the log level
Amplify.Logging.logLevel = .verbose
```

**Comment by jeremyscatigna** [comment] 2020-10-28 06:42
@drochetti I increased the log level and dig a bit deeper here is what I have:
```
self	Amplify.GraphQLResponseError<[Shyc.Outfit]>	transformationError
transformationError	(String, Amplify.APIError)	
0	String	"{\"data\":{\"listOutfits\":{\"items\":[{\"id\":\"3bb8c347-0086-4d12-a12e-85e0ad812d9a\",\"userId\":\"95c51add-39f9-4200-8fcb-cf96c99fea1e\",\"name\":\"Daily\",\"url\":\"https://res.cloudinary.com/shyc/image/upload/v1602838869/images/IMG_1869_ph5k2t.jpg\",\"clothings\":{\"nextToken\":null},\"tags\":{\"items\":[],\"nextToken\":null},\"events\":{\"nextToken\":null},\"createdAt\":\"2020-10-16T09:06:37.554Z\",\"updatedAt\":\"2020-10-16T09:06:37.554Z\"},{\"id\":\"79e5fa4c-7d24-4cf2-87ad-35835de8a7d4\",\"userId\":\"95c51add-39f9-4200-8fcb-cf96c99fea1e\",\"name\":\"Fashion week\",\"url\":\"https://res.cloudinary.com/shyc/image/upload/v1602838602/images/IMG_1865_u9mcda.jpg\",\"clothings\":{\"nextToken\":null},\"tags\":{\"items\":[],\"nextToken\":null},\"events\":{\"nextToken\":null},\"createdAt\":\"2020-10-16T09:05:07.365Z\",\"updatedAt\":\"2020-10-16T09:05:07.365Z\"},{\"id\":\"0fa61b8b-2bb0-44cf-bb07-0c3bae7029ec\",\"userId\":\"95c51add-39f9-4200-8fcb-cf96c99fea1e\",\"name\":\"Night out\",\"url\":\"https://res.cloudinary.com/shyc/image/upload/v1602838594/images/IMG_1866_wagjt9.jpg\",\"clothings\":{\"nextToken\":null}"...	
_guts	_StringGuts	
_object	_StringObject	
_countAndFlagsBits	UInt64	17293822569102710966
_object	Builtin.BridgeObject	0x7ff2e714d200	0x00007ff2e714d200 -> 0x00007fff8738b620 (void *)0x00007fff8739a3c0: OBJC_METACLASS_$__TtCs15__StringStorage
1	Amplify.APIError	operationError
operationError	(String, String, Error?)	
0	String	"keyNotFound key CodingKeys(stringValue: \"outfit\", intValue: nil)"	
_guts	_StringGuts	
1	String	""	
2	Error?	<invalid> (0x1)
``` 

![Screenshot 2020-10-28 at 07 38 44](https://user-images.githubusercontent.com/15782436/97401441-201eb380-18f1-11eb-8c97-1795961a8ad8.png)

**Comment by jeremyscatigna** [comment] 2020-10-28 07:20
@drochetti Found the fix ! Thanks a lot for your help !
There were missing fields in the query so it was not decodable due to missing keys

**Comment by royjit** [comment] 2020-11-12 18:04
Glad you fix the issue, closing the ticket. Feel free to reach back if you have further concerns.

**Closed by royjit** 2020-11-12 18:04 UTC
Labels: api, closing soon, duplicate, question, requesting info
