### ISSUE TITLE
Initial sync missing __typename and going to endless cycle.

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1458] opened 2021-10-08 21:58 UTC
### Describe the bug

The initial sync doesn't finish but keeps restarting itself.

I checked the logs and found this:

```
2021-10-08 23:42:58.080660+0200[26690:8867487] [RemoteSyncEngine] DataStoreError: An error occurred syncing Memberships
Caused by:
DataStoreError: failed to process graphqlResponseData
Caused by:
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`
```

It's important to note, that I have not touched my installation, nor have a changed my code. I have no idea why this happens. It must be some new item(s) that's offending, however, I have no idea where to start searching. I did use my app earlier generating some data that was inserted. Now it started doing this. Given that it happened to me, it probably may also happen to other users.

### Steps To Reproduce

I can reproduce it 100%. However, I've no idea how to get DataStore into that condition, as I've no idea which item it has trouble with. All I can tell you is that we're dealing with several dependent items.

Table A: Groups, roughly 300 items
Table B: Items that may belong to the groups, roughly 10000 items
Table C: Links to connect Group to Items, roughly 6000 items.

According to the error message something goes wrong when syncing Table C.

I don't really know where to start. What information do you need?

### Expected behavior

I expected the initial sync to complete.

If that's not possible, I'd like an error message clearly indicating where a problem occurred, i.e. what was the offending item.

### Amplify Framework Version

2339458fc86f6a5d1d866d92146fea1f8b3fadf6

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)

### CLI version

6.1.1

### Xcode version

12.5.1

### Is this a regression? (i.e. was this working before a version upgrade)

Yes. I have seen flawless initial syncs many times. It used to work. I'm completely puzzled what went wrong.

### Device

iPhone 12 Pro Max, Simulator

### iOS Version

iOS 15

### Specific to simulators

no

**Comment by anatomybook** [comment] 2021-10-18 20:29
> hey @anatomybook, sorry for the inconvenience caused

Hi @lawmicha 

> 
> > It was orphaned items again. As I've described above, and item in Table B was deleted and therefore some links items couldn't be built.
> 
> Can you clarify that the scenario is that you had deleted an item from DynamoDB and then the sync process in DataStore pulled in an orphaned item? ie. deleteing item TypeB from DynamoDB and syncing item TypeC which has a typeB (which was never pulled in) failed?
> 

Yes. What you describe is what happened: I believe (not sure, wasn't me who did it, but I've seen it in the past) that a user deleted an item of TypeB and while cascade deletion of TypeC items was in progress, that app got interrupted but putting the phone on standby/killing app or something similar. That led to items of TypeC floating around without their TypeB item. That in turn triggered the above-mentioned problem. At least that what I reconstructed from the evidence, I've gathered. As soon as I manually deleted the orphaned TypeC items from DynamoDB, everything went back to working order.

> > The error array contains helpful information. I believe it should be shown somewhere. Or did I overlook something?
> 
> We can definitely look into hydrating this information from API to DataStore and decide how to handle this. If DataStore send the error on the DataStore's errorHandler, then you could at least log the problem items.

That sounds great. I believe that would help many people, should they ever come across similar issues.

> > More importantly: Why is DataStore thrown off by this? It was fixed some time ago and it went away for me (mostly, except for now).
> 
> It looks like the issue occured at the API and AppSync returned the error, which may not be something that DataStore is currently handling correctly.

Thanks for explanation. That makes sense. When I was diving into this, I didn't even notice, that I moved from DataStore to API.

> For iOS team:
> 
> * DataStore should not continue to function properly (should not be in endless cycle) when an item fails be retrieve from API due to missing a belongs-to item. The error can be sent back on the errorHandler.

You mean should continue to function properly, not "not" continue :)

**Comment by lawmicha** [comment] 2021-11-15 18:09
Thanks for the reply! we'll continue to investigate the cascade behavior and orphaned children scenario further and provide an update on this when we can

**Comment by anatomybook** [comment] 2021-11-16 20:51
Thanks for info. I'm looking forward to an update.

**Comment by dsaliberti** [comment] 2021-11-22 23:12
I'm also experiencing the endless cycle of sync
And more info on how detect orphans children issue I appreciate 👍 
Also obvs happy to share more details

**Comment by dsaliberti** [comment] 2021-11-25 12:04
I'm also having this sync restart endless cycle but caused by another issue 
And the only way to get some clue is by using `.verbose` on `Amplify.Logging.logLevel` 

###  The cause

When BE deploys some non-breaking-changes, e.g making some `required` property `optional`, and iOS client builds without pulling, the sync keeps in loop due to 1 broken model 

And it's not considered a `DataStoreErrror` 🤔 
How can I catch/handle such error without filtering log `.verbose`
Is it wrong to say that a serialisation error is also DataStore error? if so, how? 

thanks in advance!

**Comment by lawmicha** [comment] 2022-05-27 19:21
Recently we released a change in how the cascade behavior works, by deleting the children to parent models (previously we would delete the parent to children models), see https://github.com/aws-amplify/amplify-ios/pull/1731 for more details. I believe doing so will avoid orphaning children models, thus sync to an empty local should always have the required items. There is an edge case where there still could be a foreign key constraint issue due to the limit imposed by the total items to sync. When this happens the error is ignored. 

@dsaliberti for schema upgrades, there is also another fix that stopped the system from retrying on non-retryable errors. the bug was to retry indefinitely, fixed in here https://github.com/aws-amplify/amplify-ios/pull/1773 To handle these errors, there is an `errorHandler` on the configuration that you can register a callback to detect these errors. We'll be improving on the errorHandler in upcoming changes.

Please upgrade to the latest library version https://github.com/aws-amplify/amplify-ios/releases/tag/v1.26.0 to get these changes. I'll close this issue for now but please open another issue if you are experiencing any problems with the latest information

**Closed by lawmicha** 2022-05-27 19:21 UTC
Labels: datastore, question, follow up
