### ISSUE TITLE
Xcode simulator warnings when adding Auth plugin in SwiftUI project (Xcode 12.3)

### ISSUE THREAD

**Issue by 3m** [aws-amplify/amplify-ios#1033] opened 2021-01-20 21:56 UTC
**Describe the bug**
When adding the auth category, the Xcode similar shows repeated messages similar to:
"objc[16115]: Class CSAudioFileManager is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x130d1fce8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x12fb67c90). One of the two will be used. Which one is undefined."

**To Reproduce**
Add this line to Xcode project:              try Amplify.add(plugin: AWSCognitoAuthPlugin())

**Expected behavior**
Expect no lodgings related to CoreSpeech.    I am not referencing and using any other frameworks.  This only happens when using the Auth plugin.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Xcode 12.3
 -

**Comment by ruiguoamz** [comment] 2021-01-22 02:42
Hi, @3m 
Thanks for reaching out.

There is one similar(or same) issue here: https://github.com/aws-amplify/amplify-ios/issues/1032
As I replied in the reference issue: I don't see these warnings printed out on my machine. 

I notice that he is running on M1 Mac. What machine are you running on thus seeing these warning message?

**Comment by treystudio3a** [comment] 2021-01-22 15:37
Hi @ruiguoamz ,

I'm sorry that was my issue too.  I didn't realize i was logged in under a different github when I posted that first one, and for some reason I wasn't seeing the post, so I reposted the issue.  So this is the same issue and I'm the same user @3m 

sorry for the confusion.

**Comment by ruiguoamz** [comment] 2021-01-22 20:49
Duplicate of https://github.com/aws-amplify/amplify-ios/issues/1032, closing this one

**Closed by ruiguoamz** 2021-01-22 20:49 UTC
Labels: build, pending triage
