### ISSUE TITLE
Symbol not found: _OBJC_CLASS_$_Reachability: ReachabilitySwift causes symbol conflict with Reachability

### ISSUE THREAD

**Issue by 24601** [aws-amplify/amplify-ios#797] opened 2020-10-02 04:36 UTC
**Describe the bug**
Amplify (through AmplifyPlugins/AWSAPIPlugin) depends on @ashleymills  ReachabilitySwift. This library introduces a conflict with the Objective-C Reachability library used by many other packages as it's author has openly chosen to use a conflicting name and publicly refused to fix the issue (https://github.com/ashleymills/Reachability.swift/issues/348). 

As such, by depending on libraries that introduce a naming conflict AWS Amplify is breaking builds through requiring an essentially broken dependency the author openly refuses to fix. The most obvious symptom is a symbol resolution conflict that results in a compiler warning about multiple targets, that at run time, causes as "Symbol not found: _OBJC_CLASS_$_Reachability" error at app start for any app that includes Amplify and any other library that itself directly or indirectly relies on the original Reachability. 

Consider dropping this dep and finding an alternative way to replicate Reachability's functions in Swift and this problem goes away.

**To Reproduce**
1. Create an iOS project that includes AWS Amplify for iOS and any other library that requires Reachability (the objective C version).
2. Try to build on iOS 14 target on Xcode 12

**Expected behavior**
Compiles without specific warning to this, and runs, no problem. 

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.1.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.3

**Device Information (please complete the following information):**
 - Device: Sim 
 - iOS Version: ios 14
 - Specific to simulators: /.*/

**Comment by palpatim** [comment] 2020-10-02 16:46
Hi @24601 

Thanks for reporting this. We'll add this to our backlog and consider options, and update this issue as we have any information.

**Comment by wooj2** [comment] 2020-12-04 19:17
A preliminary decision (pending an engineering spike) has been made to write a thin layer to replace ReachabilitySwift.  We will update the ticket when we know more about when this work can be started.

**Comment by wooj2** [comment] 2020-12-08 19:31
@24601 ,

I'm trying to reproduce this issue, so that we can be sure we fix this issue correctly.

Can you please suggest a library which "requires Reachability (the objective C version)", so that i can reproduce this issue on my machine?

Thanks

**Comment by 24601** [comment] 2020-12-08 20:48
Hello Mr. Woo,

Thanks for looking into this and moving this issue out of the library! I
know that PusherSwift is one that many people have mentioned on
StackOverflow, and it might even have been responsible for ours as a
transient dependency, but let me go back in our SCM history and get the
branch of our app that had this issue and I'll build you a sample repo
demonstrating the issue if you'd like!

Thanks!

Basit

**Comment by 24601** [comment] 2020-12-08 20:54
@wooj2 - we were using graphql_flutter which depended on connectivity which used ReachabilitySwift, but connectivity has moved away from including ReachabilitySwift for this same reason, so the actual test case from our code won't help much with the new version, but pinning to a backlevel version should still replicate it. 

BUT, I would still be happy to build you one (that is likely more straightforward as it won't involve the Flutter -> iOS portion) that is just native iOS Swift with PusherSwift as an example

**Comment by wooj2** [comment] 2020-12-08 23:55
Hi @24601 ,

I've made a draft PR effectively forking Reachability.swift to AmplifyReachability, but before moving forward with this, I'd feel more comfortable if I was able to reproduce the linker error you are seeing.

When you refer to the "Objective-C Reachability" library, which library are you referring to?

**Comment by wooj2** [comment] 2020-12-14 23:58
Hi @24601 ,

I believe I've been able to reproduce this issue by creating a sample flutter application with `connectivity: ^2.0.2` as suggested by @Rayv1 located [here](https://github.com/aws-amplify/amplify-flutter/issues/235#issuecomment-744681625), so there's no need for you to build me one.

Just to tie up loose ends, I believe I found the reachability library you were referring to, which seems to be: https://cocoapods.org/pods/Reachability, which looks very similar to the Apple Reachability sample code located here: https://developer.apple.com/library/archive/samplecode/Reachability/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007324

**Comment by wooj2** [comment] 2020-12-15 00:48
Code changes have been pushed to the main branch.  I've applied the pending release tag as this code change is scheduled to be in our next release.

**Comment by royjit** [comment] 2020-12-24 17:23
The fix is released in 1.5.2, please take a look https://github.com/aws-amplify/amplify-ios/releases/tag/1.5.2

**Closed by royjit** 2020-12-24 17:23 UTC
Labels: api, build, feature request, pending release
