### ISSUE TITLE
Download URL from existing S3 object won't work and keep crashing with fatal error. Library is still in developer preview.

### ISSUE THREAD

**Issue by ImranRazak1** [aws-amplify/amplify-ios#1768] opened 2022-04-27 10:58 UTC
### Describe the bug

I am trying to get the objects inside my S3 bucket URLs so my iOS app can download them. I do not have a login so I didn't use Cognito, my api URLs right now for the objects are individually coded and are publicly accessible. So I can just download the JSON data to be decoded from the URL but I am trying to use Amplify to do that in code rather than having to input the URL itself.

Here is an example of an API without amplify:

//Healthy and Simple Recipes
@MainActor
class HealthyAPI: ObservableObject {
    @Published var recipes: [Recipe] = []
    
    func fetchRecipes() async {
        guard let healthyAPIURL = URL(string: "https://recipesstore.s3.eu-west-2.amazonaws.com/Healthysimple.json") else {
            
            print("Invalid URL")
            return
            
        }

          do {
              let (data, _) = try await URLSession.shared.data(from: healthyAPIURL)
              let decoder = JSONDecoder()
              recipes = try decoder.decode([Recipe].self, from: data)
          } catch {
              print(error)
          }
      }
    
}
I am now looking to use Amplify to access the S3 bucket and get the correct URL for the recipe category for the API like the class above except call in the URL from my S3 bucket to the Object via Amplify. I have download the Amplify using SPM to the Xcode file. Added an App Delegate as such:

import Foundation
import SwiftUI
import Amplify
import AWSS3StoragePlugin

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        do {
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()
            print("Amplify configured with storage plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }

        return true
    }
}
and a Amplify configuration json as follows from the AWS amplify documentation:

{
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                  "bucket": "recipesstore", //S3 Bucket name
                  "region": "eu-west-2" //Region of Bucket
            }
        }
    }
}
and I have finally added to my App Main file too as the docs said to do:

import SwiftUI

@main
struct WeCookedApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        WindowGroup {
            RecipeContentView()
            
        }
    }
My code is 100% written in Swift and SwiftUI, so I don't really want to stray of it.

The app hasn't got any logins or authentication.

Hope you can help because I am baffled of what to do. It configures in the debug area but then when I replace the URL part to be like this:

//Testing Amplify
class AmplifyAPI: ObservableObject {
    @Published var recipes: [Recipe] = []

    func fetchRecipes() async {
        guard let amplifyAPI = URL(string: "\(Amplify.Storage.getURL(key: "Breakfast.json"))") else {
            
            print("Invalid URL")
            return
            
        }

          do {
              let (data, _) = try await URLSession.shared.data(from: amplifyAPI)
              let decoder = JSONDecoder()
              recipes = try decoder.decode([Recipe].self, from: data)
          } catch {
              print(error)
          }
      }
}
The app just crashes saying "fatal error in StorageCategory.swift at line 19. Storage Category is not configured. Call Amplify.Configure() before using any methods on the category". Which is confusing since the debug said amplify with storage plugin configured.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Download Amplify using SPM.
2. Follow the steps to add the app delegate and configuration json as above.
3. Create a Class to test the API out on Swiftui. 
4.Run the code and it will configure in the debugger but when running the Call with @StateObject for a list view to list out all the recipes for example, it will come back with a fatal error mentioned in the post.
```

### Expected behavior

The JSON download URL to be downloaded and then for the list view to show without a fatal error saying The app just crashes saying "fatal error in StorageCategory.swift at line 19. Storage Category is not configured. Call Amplify.Configure() before using any methods on the category". Which is confusing since the debug said amplify with storage plugin configured.

### Amplify Framework Version

1.23.1

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.6

### CLI version

N/A

### Xcode version

13.1

### Relevant log output

```shell
The app just crashes saying "fatal error in StorageCategory.swift at line 19. Storage Category is not configured. Call Amplify.Configure() before using any methods on the category". Which is confusing since the debug said amplify with storage plugin configured.
```

### Is this a regression?

No

### Device

iPhone 13 Pro Max simulator & Preview

### iOS Version

iOS 15

**Comment by thisisabhash** [comment] 2022-04-29 20:55
Closing this as duplicate of https://github.com/aws-amplify/amplify-ios/issues/1767

**Closed by thisisabhash** 2022-04-29 20:55 UTC
Labels: storage
