### ISSUE TITLE
Called Amplify.Auth.signOut() after webUI signIn does not clear session 

### ISSUE THREAD

**Issue by ravikanhasoft** [aws-amplify/amplify-ios#964] opened 2020-12-11 06:21 UTC
**Describe the bug**
When I am using `Amplify.Auth.signOut()` method for signout locally, it doesn't work. It gives "Successfully signed out" but next time when i called `Amplify.Auth.signInWithWebUI(for: .google.......` application is not asked for sign in details of google account and it automatically gets from preivously signedin user and it goes to successfully sign in.

**To Reproduce**
1. First I am sign in with this method. So application asked me google id and password (Frist time only) then it will successfully sign in.
            
```
        Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window!) { result in
               switch result {
               case .success:
                   print("Google Sign in succeeded")
               case .failure(let error):
                   print("Sign in failed \(error)")
               }
           }
```

2. Now i am calling a sign out locally. Which is also called successfully with signed out block.

```
Amplify.Auth.signOut() { result in
            switch result {
            case .success:
                print("Successfully signed out")
            case .failure(let error):
                print("Sign out failed with error \(error)")
            }
        }
```
3. Now I again sign in with the step #1. it will not asking me to enter google id and password for sign in. Just like the video i attached.

**Expected behavior**
After signout it should asked me a signin details screen again.

**Screenshots**
![Screen_Recording_2020-12-10_at_9 22 40_AM](https://user-images.githubusercontent.com/29453207/101870019-ca535180-3ba6-11eb-9abc-79bc06359536.gif)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8 Plus simulator, iPhone 7plus real device
 - iOS Version: 14
 - Specific to simulators:

**Comment by shikhilnuwal** [comment] 2020-12-11 06:36
Duplicate of #958

**Comment by palpatim** [comment] 2020-12-11 14:37
Resolving this as a dupe, but referencing this issue from #958 to make sure we can see the useful context & code snippets.

**Closed by palpatim** 2020-12-11 14:37 UTC
Labels: auth, bug, pending triage

**Comment by Eric1015** [comment] 2022-08-19 06:58
One thing I would like to know is that why does this ```Amplify.Auth.signOut()``` function opens the web UI with 
```"..." wants to use "..." to sign in```. My expectation is that this webUI is only needed when the user is trying to sign in, but not at the time that the user wants to sign out.

I am currently facing this issue, and want to know if there is an issue already about that, otherwise wants to know if someone knows how to not showing that web UI at the time of sign out.

**Comment by atierian** [comment] 2022-10-06 13:20
@Eric1015 @brandonmaul

You can prevent the web view from being displayed by passing in the option `prefersPrivateSession()`. 
Documentation around this can be found [here](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios/#prefer-private-session-during-signin).

If you have any further questions about this, please open a separate issue. Thanks!
