### ISSUE TITLE
Amplify.Auth.getCurrentUser()  get nil after upgrade to iOS14.5

### ISSUE THREAD

**Issue by softjapan** [aws-amplify/amplify-ios#1188] opened 2021-04-27 15:24 UTC
**Describe the bug**
Xcode12.5 iOS14.5  
Amplify.Auth.getCurrentUser()  get nil  even I have logged in

same source code runing on iOS14.4.2 is all right.

**To Reproduce**

Xcode12.5 iOS14.5  
Amplify.Auth.getCurrentUser()  

**Expected behavior**

get current auth user

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: [Amplify 1.9.0]
 - Dependency Manager: [Cocoapods]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**

**Comment by diegocstn** [comment] 2021-04-29 17:08
Hi @softjapan, can you please provide the following:
- how have you configured the auth category?
- how are your users signing in? (custom UI, web ui, social sign in)
- snippets of code of how you're trigger the sign in flow and calling `Amplify.Auth.getCurrentUser()`

**Comment by softjapan** [comment] 2021-04-30 04:36
Thanks you for response

-  I configure auth by  amplify cli 
amplify add auth  
amplify push

-  snippets
```swift
Amplify.Auth.signIn(username: username, password: password) { result in
            switch result {
            case .success:
                
                print("Sign in succeeded")
               //Here is the problem, subId will always be nil in iOS14.5, and all are right in iOS 14.4.2
                let subId = Amplify.Auth.getCurrentUser()?.userId

            case .failure(let error):
                print("Sign in failed \(error)")

            }
}
```

**Comment by ruiguoamz** [comment] 2021-05-03 20:57
Hi, @softjapan 

Sorry that I could not reproduce it with iOS 14.5.

Could you provide more information? Like:

1. How often does the behavior occur?
2. Which Amplify Framework Version are you using?
3. Which Dependency Manager do you use: CocoaPods or SPM?

**Comment by softjapan** [comment] 2021-05-04 02:03
Hi,Thanks

1. Every time
2. Then latest version with CocoaPods
3. 
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'

**Comment by ruiguoamz** [comment] 2021-05-04 02:53
Hmmm. I really could not reproduce it

Below is the code I use which is the same as yours and it works fine on my side.
```swift
Amplify.Auth.signIn(username: "user", password: "password") { result in
    switch result {
    case .success:
        let currentUser = Amplify.Auth.getCurrentUser()?.userId
        print(currentUser)
    case .failure(let error):
        print(error)
    }
}
```
I wonder if there are some details we are missing.
1. What devices or simulators are you running on.  
        I am running on a iPhone 12 simulator on Xcode 12.5
2. And just be curious, what if you wait 2 seconds and then call `getCurrentUser()`? something like
```swift
Amplify.Auth.signIn(username: "user", password: "password") { result in
    switch result {
    case .success:
        DispatchQueue.main.asyncAfter(.now() = 2) { // manually inject a delay
            let currentUser = Amplify.Auth.getCurrentUser()?.userId
            print(currentUser)
        }
    case .failure(let error):
        print(error)
    }
}
```
See if it still returns nil.

**Comment by softjapan** [comment] 2021-05-05 04:16
Hello, 
1.  Actual machine iPhone Xs , Model Number: MTAX232J/A
2. Tried to wait 2 seconds and then call getCurrentUser() , same result ,  Amplify.Auth.getCurrentUser()?.userId still nil.

**Comment by softjapan** [comment] 2021-05-05 04:18
by the way, same iPhone machine, iOS14.4.2 are all ok.

**Comment by ruiguoamz** [comment] 2021-05-05 21:53
Honestly. I am not sure what is causing the behavior. 

I used a physical iPhone 12 (I don't have a Xs) and failed to reproduce it. 

Could you please try to re-install the App or test it with another machine/simulator?

**Comment by softjapan** [comment] 2021-05-06 09:21
Hello, after I upgrade to iOS 14.5.1 ,  all are right now. Please close this issue, thank you very much.

**Comment by ruiguoamz** [comment] 2021-05-06 14:55
Glad to hear that it's working fine. Closing this issue

**Closed by ruiguoamz** 2021-05-06 14:55 UTC
Labels: auth, pending triage, requesting info
