### ISSUE TITLE
DataStore never starts sync if the App started when device was offline even when invoking DataStore.start

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-ios#1718] opened 2022-04-01 17:31 UTC
### Describe the bug

Original issue: https://github.com/aws-amplify/amplify-flutter/issues/1440

* Condition
  - Turn off network
  - Run App with network turned off
  - Save 3 models say Todo1, Todo2 and Todo3
* Observation
  - DataStore saved all 3 models into local DB
  - DataStore pushed all 3 models into mutationOutBox
  - There was no sign that sync engine was invoked to process mutationOutBox events
  - Turn on network
  - Invoking `Amplify.DataStore.start` , but below logic actually prevented restarting of the sync engine
  https://github.com/aws-amplify/amplify-ios/blob/e66dfbc6265613d98000e0f2eb88fd4df380eb10/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift#L141-L144

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
See above description
```

### Expected behavior

DataStore should start sync in this scenario.

### Amplify Framework Version

1.22.0

### Amplify Categories

API, DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

The latest

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 simulators

### iOS Version

15.2

**Comment by lawmicha** [comment] 2022-04-06 17:31
Hi @HuiSF , thanks for the details, i'll give it a try to reproduce the unexpected behavior with `Amplify.DataStore.start` and provide an update when i can here

**Comment by lawmicha** [comment] 2022-05-10 15:20
@royjit was able to reproduce this on a real device, the issue is the URLError case that is received by DataStore is not handled by the retry handler. When the retry advice is false, the attempt is treated as a non-retryable error and deleted from the outgoing mutation queue

**Comment by lawmicha** [comment] 2022-05-27 19:10
change has been merged and released

**Closed by lawmicha** 2022-05-27 19:10 UTC
Labels: bug, datastore, pending-triage
