### ISSUE TITLE
Unable to mutate graphql relationship created using @hasmany directive.

### ISSUE THREAD

**Issue by louiss98** [aws-amplify/amplify-ios#1742] opened 2022-04-13 22:58 UTC
### Describe the bug

Unable to mutate graphql one-to-many relationship field created with @hasmany directive.

### Steps To Reproduce

```swift
1. Use the following schema
type Story @model @auth(rules: [{allow: public}, {allow: private}, {allow: owner}]) {
  id: ID!
  stories: [StoryPost!] @hasMany(indexName: "byStory", fields: ["id"])
}


type StoryPost @model @auth(rules: [{allow: private}]) {
  id: ID!
  storyID: ID! @index(name: "byStory")
}

2. Create Story and StoryPost

3. Attempt to mutate the story to link to the StoryPost either programmatically or through studio.
```

### Expected behavior

The story post to be added to an array in the story object

### Amplify Framework Version

1.22.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

4.2

### CLI version

7.6.25

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 8 Simulator

### iOS Version

iOS 12.1

### Specific to simulators

no

### Additional context

I noticed the relationship field in studio is named Post instead of StoryPost. Are similar model names an issue?
<img width="1054" alt="Screen Shot 2022-04-13 at 6 33 03 PM" src="https://user-images.githubusercontent.com/30845685/163282905-a13875b5-e607-4029-9986-f03b6e166939.png">

**Comment by lawmicha** [comment] 2022-04-14 19:58
Thanks @louiss98, we'll work on reproducing this through the Studio and provide updates on our findings. 

Capturing the Discord message regarding "Post" vs "StoryPost":
> In the screenshot I shared. Under the stories field, it says link to an existing Post, however it should say link to an existing StoryPost. Unsure why the story part is not there.

**Comment by lawmicha** [comment] 2022-04-15 12:42
From Discord, latest schema looks like this
```
type Story @model @auth(rules: [{allow: public}, {allow: private}, {allow: owner}]) {
  id: ID!
  previewImage: S3Object
  title: String
  caption: String
  owner: User @hasOne
  stories: [StoryPost!] @hasMany(indexName: "byStory", fields: ["id"])
  accessLevel: UserRelationType
}


type StoryPost @model @auth(rules: [{allow: private}]) {
  id: ID!
  image: S3Object
  video: S3Object
  storyID: ID! @index(name: "byStory")
}
```

**Comment by lawmicha** [comment] 2022-04-15 12:51
Ran through Amplify Studio's Data modeling experience and trying to understand how the S3Object properties were created on the schema

**Comment by lawmicha** [comment] 2022-04-15 14:49
Turns out S3Object is 
```
type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```

**Comment by lawmicha** [comment] 2022-04-15 14:58
Asking on Discord for entire schema, including UserRelationType and User

**Comment by lawmicha** [comment] 2022-04-15 15:04
```
type StoryPost @model @auth(rules: [{allow: private}]) {
  id: ID!
  image: S3Object
  video: S3Object
  storyID: ID! @index(name: "byStory")
}

type Album @model @auth(rules: [{allow: public}]) {
  id: ID!
  userAccessLevel: UserRelationType
  title: String
  viewers: [User] @hasMany(indexName: "byAlbum", fields: ["id"])
}

type AlbumComment @model @auth(rules: [{allow: public}]) {
  id: ID!
  text: String
  post: AlbumPost
}

type UserRelationType {
  FRIEND: String
  CLOSE_FRIEND: String
  BLOCKED: String
}

type UserRelation @model @auth(rules: [{allow: public}]) {
  id: ID!
  userRelationType: UserRelationType
  userRelating: String
  userRelated: String
}

type Story @model @auth(rules: [{allow: public}, {allow: private}, {allow: owner}]) {
  id: ID!
  previewImage: S3Object
  title: String
  caption: String
  owner: User @hasOne
  stories: [StoryPost!] @hasMany(indexName: "byStory", fields: ["id"])
  accessLevel: UserRelationType
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type AlbumPost @model @auth(rules: [{allow: public}]) {
  id: ID!
  image: S3Object
  caption: String
  albumID: ID @index(name: "byAlbum")
}

type User @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}]) {
  id: ID!
  name: String!
  username: String!
  profileImage: S3Object
  birthdate: String
  albumID: ID! @index(name: "byAlbum")
}
```

**Comment by lawmicha** [comment] 2022-04-15 16:34
Sync problem with with `owner: User @hasOne` on the Story, when I call `DataStore.start()`, the subscription for Story fails with the following:
```
GraphQLResponseError<MutationSync<AnyModel>>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type SubSelectionRequired: Sub selection required for type User of field owner @ \'onUpdateStory/owner\'", locations: nil, path: nil, extensions: nil)]
```

**Comment by lawmicha** [comment] 2022-08-01 16:25
This issue has been open for awhile now without any responses, which means our schema for replicating the issue could be outdated. Reviewing what we have for auth rules for User, I believe the user needs to be signed in to establish the User subscriptions successfully: `@auth(rules: [{allow: private, operations: [read]}, {allow: owner}])`. I'm closing this issue now that we understand what's happening in this use case, but please feel free to reach out again if you have additional questions

**Closed by lawmicha** 2022-08-01 16:25 UTC
Labels: pending-response, api, datastore, follow up, p1
