### ISSUE TITLE
"One or more errors occurred syncing models"

### ISSUE THREAD

**Issue by pstance** [aws-amplify/amplify-ios#725] opened 2020-08-19 16:08 UTC
**Describe the bug**
When I initialize DataStore, I run into the following issue when my models try to sync. I have not been able to find any documentation of this error or what is causing it. It appears to not be able to sync one of the tables and then unsubscribes from them all. Could you describe the cause of this type of error message? 

![Screen Shot 2020-08-19 at 8 58 49 AM](https://user-images.githubusercontent.com/28552207/90660312-9c628f80-e1fa-11ea-8f91-492a0b839840.png)

**Comment by DongQuanRui** [comment] 2020-08-19 17:50
Hi, @pstance . Could you elaborate on this issue?
Maybe what steps to follow to reproduce it?
And did you change you schema locally and forgot to do `amplify push` to update your backend resource?
Please give us more details, thanks

**Comment by pstance** [comment] 2020-08-19 18:00
```amplify status``` says that all changes are reflected in the cloud. The error identifies the following model as the issue:

![Screen Shot 2020-08-19 at 10 58 30 AM](https://user-images.githubusercontent.com/28552207/90672445-fbc89b80-e20a-11ea-9043-56447ed50584.png)

Is there something wrong with this model definition?

**Comment by DongQuanRui** [comment] 2020-08-19 20:35
Hi, so by looking at your schema:
1. `searchable` directive is not supported and tested in iOS side yet. There might be problem using it.
2. Can you also check if you have `conflict resolution` enabled? As you can find here: https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios#option-2-use-amplify-cli

**Comment by lawmicha** [comment] 2020-08-19 20:41
i think enabling conflict resolution should do the trick here, as @DongQuanRui mentioned. searchable directive can be used to provision the AppSync backend with a search query, and then you can make requests using `Amplify.API.query`  directly to your AppSync service.  DataStore interacts with a local store and would not expose the search functionality you are expecting from the searchable directive. Do you have a particular use case for having the searchable directive when using DataStore?

**Comment by pstance** [comment] 2020-08-19 20:52
Conflict Resolution is enabled and I have removed the searchable directive. DataStore worked on the first build. However, after I stopped and rebuilt the project, the error returns.

**Comment by lawmicha** [comment] 2020-08-19 21:12
is the error still InternalFailure? that looks like an AppSync service issue. I've seen cases where updating the API results in unexpected state of the system, where dynamoDB may still have data in formats that was meant for the previous schema. Could you try `amplify delete` and re-provision the API without searchable directive and conflict resolution enabled?

**Comment by LaszloDev** [comment] 2020-08-20 11:10
> Conflict Resolution is enabled and I have removed the searchable directive. DataStore worked on the first build. However, after I stopped and rebuilt the project, the error returns.

We did ran into a similar issue yesterday after the SDK was updated. Just for testing, could you check a download the iOS SDK and see if that error is still happening?

**Comment by pstance** [comment] 2020-08-20 15:03
@lawmicha I just ran ```amplify delete``` and re-provisioned the API. The error unfortunately is still occuring.

**Comment by enteleca** [comment] 2020-09-30 17:09
Hi, I am having this exact same issue. 
It may or may not have something to do with DynamoDB adding the __typename, _lastChangedAt and _version fields. 
The reason I believe this is because the initial upload to DynamoDB works just fine, and the data appears. Uploading the data with conflict resolution enabled automatically adds the __typename, _lastChangedAt, and _version fields. 

The problem occurs is when we are trying to query for the data again. I believe the DynamoDB table might be returning the __typename, _lastChangedAt, and _version fields, but our application has no idea how to handle that.

How should we proceed? Thank you.


fields

**Comment by drochetti** [comment] 2020-10-10 04:55
@enteleca can you confirm that you had an AppSync backend with data and then later updated it to use DataStore?

**Comment by enteleca** [comment] 2020-10-12 01:12
> @enteleca can you confirm that you had an AppSync backend with data and then later updated it to use DataStore?

Already fixed the issue. 

Not sure if it was a bug, but you might want to open an issue up.

The reason I received that error is because some fields that I defined as lists (such as " listOfStrings: [String]! " ), I inserted in my model as the following:

> User(listOfStrings: [])

The empty [] caused an error in the DynamoDB backend because it was not expecting an list that existed but was empty. In this case, users may not be able to initialize an empty list [] and later adding things in there. I have to create a list with at least one item in it so I just entered in [""]. 

That fixed the issue. It would be great if we could enter in an empty list [] when syncing a new object, but I already made a workaround. It would be good for future development.

**Comment by lochawala** [comment] 2020-10-12 10:41
> > @enteleca can you confirm that you had an AppSync backend with data and then later updated it to use DataStore?
> 
> Already fixed the issue.
> 
> Not sure if it was a bug, but you might want to open an issue up.
> 
> The reason I received that error is because some fields that I defined as lists
> 
> > listOfStrings: [String]!
> 
> and I inserted in my model as the following:
> 
> > User(listOfStrings: [])
> 
> The empty [] caused an error in the DynamoDB backend because it was not expecting an list that existed but was empty. In this case, users may not be able to initialize an empty list [] and later adding things in there. I have to create a list with at least one item in it so I just entered in [""].
> 
> Took me about a week to figure it out.
> 
> That fixed the issue. It would be great if we could enter in an empty list [] when syncing a new object, but I already made a workaround. It would be good for future development.

@enteleca Thanks you save my day

**Comment by lawmicha** [comment] 2020-10-13 20:28
Glad you were able to figure out the issue. To summarize.

Developers starting with DataStore, without API, can enable sync to cloud by provisioning the API with conflict resolution enabled. If the API is configured without conflict resolution, the persisted data will be inconsistent after API is updated with conflict resolution and some APIs will not work as expected due to the expected fields like _version and _deleted.

A workaround here is to delete the DynamoDB data or backfill the data with expected payloads. Ideally in a new application and is currently in development, the easiest way would be to delete the dynamoDB items. You can also clear the local database using `Amplify.DataStore.clear`, run this once in the app and then comment/remove the line if it is just meant to delete the local database once.

You can also update your schema to optional list of strings by removing the `!` that makes it required: `listOfStrings: [String]`. This way, in the code you can set `User(listOfStrings: [])` and will persist successfully. Also there is a known issue for persisting nil for optional lists () so you will have to persist an empty array instead for now.

Feel free to open a new issue if you are seeing other problems

**Comment by lawmicha** [comment] 2020-10-13 21:40
Hi @enteleca 

> The problem occurs is when we are trying to query for the data again. I believe the DynamoDB table might be returning the __typename, _lastChangedAt, and _version fields, but our application has no idea how to handle that.

> Additionally, I tried the query on `amplify api console` and got the same error.
> <img alt="Screen Shot 2020-09-30 at 12 31 45 PM" width="712" src="https://user-images.githubusercontent.com/28682614/94719685-18331a00-0319-11eb-8dad-a7792fd59360.png">


Let me try to reproduce this. 
1. Saving data with `[]` for arrays. this is a valid
2. retrieving data using the sync query.

**Comment by lawmicha** [comment] 2020-10-14 17:20
i've confirmed that for a conflict resolution enabled API, saving a model with an empty list of strings will return Internal Service Failure. In DataStore, it's not obvious because the synchronization is done internally. Even though the Internal Service error occurs, data continues to be persisted in DynamoDB (you can verify this by opening the DataSource for your model from the AppSync Console and listing the items in DynamoDB). Once data is persisted in the table, SyncQuery will start failing with the same "InternalFailure" error

**Comment by lawmicha** [comment] 2020-11-02 16:06
I've confirmed that I am able to pass in empty `[]` and no longer get back Interal Service Failure. Can you try the same calls and let us know if you are still experience issues with your backend?

**Comment by enteleca** [comment] 2020-11-02 16:09
@lawmicha was this patched recently? I don't want to ruin my backend now because now I have my first few users and have not created backups yet. I would test it though if you can confirm some changes have been made due to this issue.

**Comment by lawmicha** [comment] 2020-11-02 16:13
Hi @enteleca, yes I saw that service team has patched it. If your workaround is working, i would suggest to keep it as is until you're more comfortable migrating code changes if you have users running the app on the workaround code. However, if you have a test user you could use that to to confirm through the AppSync console that the operations are working as expected with input containing empty array`[]`

**Comment by enteleca** [comment] 2020-11-10 06:39
@lawmicha I removed my bandaid and implemented the patch. It works! Thanks so much for fixing it!

**Closed** 2020-11-12 14:51 UTC
Labels: datastore
