### ISSUE TITLE
AWSCredentials are nil. Could not retrieve AWS credentials, credential value is nil or empty.. 

### ISSUE THREAD

**Issue by HovhannesPoghosyan** [aws-amplify/amplify-ios#1501] opened 2021-11-01 14:01 UTC
### Describe the bug

I am using Amplify Storage plugin and uploading files to the cloud. During my upload i am sometimes all my uploads starting to fail with the following error message 

`Unexpected error occurred with message: Could not retreive AWS credentials, credential value is nil or empty.. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/apple/Desktop/beyondo-ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift`

and it never recovers until i kill the app and try to upload again. This issue happened after this crash fix https://github.com/aws-amplify/amplify-ios/issues/1373

### Steps To Reproduce

```swift
There are no steps to reproduce this issue. It happens too often but not always so i am not able to tell the steps.
```

### Expected behavior

The upload should work without any issue.

### Amplify Framework Version

1.15.3

### Amplify Categories

Auth, Storage

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

6.1.1

### Xcode version

13.1

### Relevant log output

```shell
Unexpected error occurred with message: Could not retreive AWS credentials, credential value is nil or empty.. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/apple/Desktop/beyondo-ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
```

### Is this a regression?

Yes

### Regression additional context

i had an issue where the app crashes when trying to get credentials , from crash log i was able to see it was forced to get info from nullable value and crashed. It was fixed and after the fix i am crash is gone but i can see the credentials are empty in some cases and my upload is paused because of that. 
Here is the link for that crash https://github.com/aws-amplify/amplify-ios/issues/1373

### Device

any iOS device

### iOS Version

15.1

**Comment by HovhannesPoghosyan** [comment] 2021-11-10 16:35
@lawmicha is there any news about this issue? it is crucial for our app and we need it to be fixed ASAP.

**Comment by HovhannesPoghosyan** [comment] 2021-11-12 11:04
@lawmicha can you at least tell me when you are going to check this issue?

**Comment by HovhannesPoghosyan** [comment] 2021-11-16 08:20
@lawmicha have you looked at this issue?

**Comment by HovhannesPoghosyan** [comment] 2021-11-16 09:22
@lawmicha i can also add the information, that when this issue happens accessKey and secretKey are empty and that is why it throwing error

**Comment by royjit** [comment] 2021-11-19 19:59
@HovhannesPoghosyan do you see the AWS Credentials being updated via API calls? How were you able to see that the  accessKey and secretKey are empty? 

We are trying to root cause the scenario when the accessKey/secretKey get empty values. You can enable logs in your app and check if the values are reaching the SDK.

```swift
        AWSDDLog.sharedInstance.logLevel = .verbose
        AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

When I checked in a sample app I am seeing the right values returned:

```

2021-11-19 11:57:55:935 CognitoUserPool[93152:1694869] Response headers:
{
    "Content-Length" = 1496;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Fri, 19 Nov 2021 19:57:55 GMT";
    "x-amzn-requestid" = "xxxx";
}
2021-11-19 11:57:55:935 CognitoUserPool[93152:1694869] Response body:
{"Credentials":{"AccessKeyId":"xxx","Expiration":1.637355475E9,"SecretKey":"xxx","SessionToken":"xxx"},"IdentityId":"xxx"}

```

**Comment by royjit** [comment] 2021-11-19 20:01
Also, will you be able to check if the issue happens if you disable Storage functionality? So that we can narrow down the issue to the right plugin code.

**Comment by HovhannesPoghosyan** [comment] 2021-11-22 08:43
@royjit yes i can confirm that credentials are being updated, just they are empty for some reason. I have added some functionality for testing here is my code in this file AWSCredentials+Extension.swift

import Foundation
import AWSCore
import Amplify

extension AWSCredentials {

    func toAmplifyAWSCredentials() throws -> AuthAWSCognitoCredentials {

        // Credentials are fetched through Cognito Identity Pool and thus these are temporary credentials
        // so sessionKey and expiration date should not be nil.
        if !accessKey.isEmpty {
            AWSCredentialsManager.shared.accessKey = accessKey
        }
        if !secretKey.isEmpty {
            AWSCredentialsManager.shared.secretKey = secretKey
        }
        
        if let sessionKey = sessionKey {
            AWSCredentialsManager.shared.sessionKey = sessionKey
        }
        
        if let expiration = expiration {
            AWSCredentialsManager.shared.expiration = expiration
        }
        
        let nonNilAccessKey = accessKey.isEmpty ? AWSCredentialsManager.shared.accessKey : accessKey
        let nonNilSecretKey = secretKey.isEmpty ? AWSCredentialsManager.shared.secretKey : secretKey
        let currentSessionKey = (sessionKey == nil) ? AWSCredentialsManager.shared.sessionKey : sessionKey
        let expirationDate = (expiration == nil) ? AWSCredentialsManager.shared.expiration : expiration
        if accessKey.isEmpty || secretKey.isEmpty || sessionKey == nil || expiration == nil {
            print(accessKey.isEmpty, nonNilAccessKey, secretKey.isEmpty, nonNilSecretKey, currentSessionKey == nil, sessionKey == nil, expirationDate == nil, "toAmplifyAWSCredentials", expiration)
        }
        guard let nonNilSessionKey = currentSessionKey,
              let nonNilExpiration = expirationDate,
              !nonNilAccessKey.isEmpty,
              !nonNilSecretKey.isEmpty else {
                  let error = AuthError.unknown("""
                      Could not retreive AWS credentials, credential value is nil or empty.
                      """)
                  throw error
              }

        return AuthAWSCognitoCredentials(accessKey: nonNilAccessKey,
                                         secretKey: nonNilSecretKey,
                                         sessionKey: nonNilSessionKey,
                                         expiration: nonNilExpiration)
    }
}

class AWSCredentialsManager {
    static let shared = AWSCredentialsManager()
    var accessKey: String = ""
    var secretKey: String = ""
    var sessionKey: String?
    var expiration: Date?
}

**Comment by royjit** [comment] 2021-11-27 04:22
I am suspecting that the credentials values in keychain are overwritten from parallel task. I have this PR that might fix the issue - https://github.com/aws-amplify/aws-sdk-ios/pull/3913

**Comment by HovhannesPoghosyan** [comment] 2021-12-01 19:20
@royjit i think it is common issue related to keychain i sow this kind of issue in other cases too. I think when you try to retrieve keychain stored values it is not always working correctly.

**Comment by sachithamh** [comment] 2021-12-27 04:11
any solid temporary solution for this :(

**Comment by torivictoria** [comment] 2022-01-05 01:26
Having the same issue.Is there an update?

**Comment by sachithamh** [comment] 2022-01-05 12:07
under AmplifyPlugins>Auth>AWSCognitoAuthPlugin>Support>Utils>AWSCredentials+Extension.swift
```
extension AWSCredentials {

    func toAmplifyAWSCredentials() -> AuthAWSCognitoCredentials {
        // Credentials are fetched through Cognito Identity Pool and thus these are temporary credentials
        // so sessionKey and expiration date will not be nil.
        let credentials = AuthAWSCognitoCredentials(accessKey: accessKey,
                                                    secretKey: secretKey,
                                                    sessionKey: sessionKey!,
                                                    expiration: expiration!)
        return credentials
    }
}
```
App crash on ``sessionKey: sessionKey!,``  unwrapping an Optional value
👎

**Comment by dsaliberti** [comment] 2022-01-20 12:40
I'm also experiencing this exact same issue. 
Looking forward for any good news and am happy to provide anything else that could help. 
thank you

**Comment by dsaliberti** [comment] 2022-01-20 13:05
I see the fix is included on the `2.27.0` tag released yesterday on the `aws-sdk-ios` 
Do we need to wait a release on the `amplify-ios`?

**Comment by harsh62** [comment] 2022-01-20 19:25
The Amplify 1.19.0 has been released with AWS SDKs updated to 2.27.0. 

Can you validate if this resolves your issues?

**Comment by dsaliberti** [comment] 2022-01-24 10:56
Thank you @harsh62 I'll check that out later today and will let you know the results 👍

**Comment by HovhannesPoghosyan** [comment] 2022-02-15 09:22
Hi @harsh62 , I have updated the latest version and the issue still exists. Here is the log for the file

```
function: recoverySuggestion
line: 80
single file upload Failed: Unexpected error occurred with message: Could not retreive AWS credentials, credential value is nil or empty.. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/hovhannespoghosyan/Documents/projects/beyondo-ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
```

**Comment by harsh62** [comment] 2022-04-18 23:44
@HovhannesPoghosyan there has been some recent refactors to the underlying AWS SDK, can you verify if this is still an issue?

**Closed** 2022-05-02 16:58 UTC
Labels: bug, pending-response, storage, auth, closing soon
