### ISSUE TITLE
Usage of Cognito `id`-token changed in v1.1.0

### ISSUE THREAD

**Issue by LaszloDev** [aws-amplify/amplify-ios#780] opened 2020-09-28 13:20 UTC
**Describe the bug**
The library changed from using the Cognito `id`-token to the `access`-token, this breaks our AppSync backend which relies on a custom user attributes which is only in the id-token. There by our AppSync resolver can not distinguish between clients making the calls to our backed.

This MR did the change
https://github.com/aws-amplify/amplify-ios/pull/690

**To Reproduce**
Try to access `$ctx.identity.claims['custom:orgId']` in an AppSync resolver. `custom:orgId` stand for our specific custom attribute, but can be replaced by your own logic.

**Expected behavior**
Either keep using the `id-token` as default or provide a way to set the library to use the id-token, as it is possible in the JS library.

**Screenshots**
iOS AppSync call made with the `access`-token with out the Cognito claims
![appsync-request-updateLive-ios-log-claims](https://user-images.githubusercontent.com/10655255/94437055-894dc280-019d-11eb-881d-af956932583a.png)

JS AppSync call made with the `id`-token including the Cognito claims
![appsync-request-updateLive-dashboard-log-claims](https://user-images.githubusercontent.com/10655255/94437064-8c48b300-019d-11eb-9531-3eef8d9a1a51.png)

**Additional context**
Our multi-tentant setup relies on the custom attributes to separate between organizations without our application. 

Thanks for you help

**Comment by palpatim** [comment] 2020-10-02 18:30
@LaszloDev 

The change to use `accessToken` was made to bring the iOS Amplify client in line with the other platforms. If your app relies on custom values only present in the `idToken`, you can get to them from a custom interceptor. I'm asking @lawmicha to provide more info on this, in relation to his docs PR https://github.com/aws-amplify/docs/pull/2211

**Comment by lawmicha** [comment] 2020-10-02 19:48
Hi @LaszloDev 

Currently a workaround to add the idToken on iOS is to have a custom interceptor, however we haven't finalized on this design and will be working on a feature request across iOS and Android to build parity for this use case with JS. Please keep this in mind that the mechanism for adding custom request data may change in future versions.

After configuring API and Auth plugins, add your custom interceptor to the interceptor chain for the API
```
try Amplify.add(plugin: AWSCognitoAuthPlugin())
try Amplify.add(plugin: AWSAPIPlugin(modelRegistration: AmplifyModels()))
try Amplify.configure()
try Amplify.API.add(interceptor: CustomRequestInterceptor(), for: "[API_FRIENDLY_NAME]")
```
API_FRIENDLY_NAME corresponds to the API endpoint cofigured in `amplifyconfiguration.json`
```
"[API_FRIENDLY_NAME]": {
    "endpointType": "GraphQL",
   "endpoint": "
   "region": "us-west-2",
   "authorizationType":  ...
},
```
In your custom interceptor, you can retrieve the IdToken from Amplify.Auth and update your request
```
struct CustomRequestInterceptor: URLRequestInterceptor {
    init() { }
    func intercept(_ request: URLRequest) throws -> URLRequest {
        var modifiedRequest = request
        let semaphore = DispatchSemaphore(value: 0)
        Amplify.Auth.fetchAuthSession { result in
            defer {
                semaphore.signal()
            }
            do {
                let session = try result.get()
                if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
                    let tokens = try cognitoTokenProvider.getCognitoTokens().get()
                    modifiedRequest.addValue(tokens.idToken, forHTTPHeaderField: "authorization")
                }
            } catch {
                print("Fetch auth session failed with error - \(error)")
                semaphore.signal()
            }
        }
        semaphore.wait()
        return modifiedRequest
    }
}
```

**Comment by LaszloDev** [comment] 2020-10-07 10:16
> bring the iOS Amplify client in line with the other platforms.

Appreciate your efforts @palpatim @lawmicha 

> Currently a workaround to add the idToken on iOS is to have a custom interceptor

Personally I'm developing on JavaScript only and been working with iOS only to manage the external development firm who builds our iOS app.

In JavaScript changing the header token used for AppSync/GraphQL requests, it's more or less a few lines of code:

```JavaScript
Amplify.configure({
  API: {
    graphql_headers: async () => {
      const session = await Auth.currentSession();
      return {
        Authorization: session.getIdToken().getJwtToken(),
      };
    },
  },
});

```

As I'm not that familiar with the concepts of Swift, my question is, would there be any chance to have an `flag` to switch between the tokens? The logic before version 1.1 did had the code for it and it would make the library much user friendly.
Alternatively an approach like the JS lib for injecting different headers.

Thanks for your work 💪🏼

**Comment by lawmicha** [comment] 2020-10-13 20:43
Hi @LaszloDev, thanks for the feedback, will take the flag option and JS's headers into consideration and will follow up on this and mark as feature request. The code that had the logic before was a mistake on our end and if we go with the flag option, this would be something we add to all platforms

**Comment by LaszloDev** [comment] 2020-10-15 16:16
Thanks @lawmicha. 
I have been only working with Amplify for two months, but the JS version does seams a lot more stable and mature, would love to see that also for the iOS version. Initializing subscriptions with attributes for example is a pain compared to the JS SDK.

What I generally do not get about Amplify with AppSync, is how authorization is done in the resolvers without the `id`-token's user identity claims, if the `access`-token is the default one to use, which does not have that information encoded?

As this is not an edge case but actively referenced in the AWS AppSync dev guide for **Security / Authorization Use Cases** to use the `$context.identity.claims` which are only in the `id`-token:
https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html

Thanks for your work guys 🙏

**Comment by zpodolyak** [comment] 2020-10-25 03:01
I have a slightly different use case. In my iOS app, I simply started receiving 401s for all my requests after upgrading to 1.1.0. I am not using AppSync at all. My API uses a Cognito authorizer (with a user pool) for all protected requests. So I decided to simply change the `getTokenString()` method in AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift from returning the `accessToken` to `idToken` and everything suddenly started working again. So I don't exactly understand how the `accessToken` is supposed to work in my case and it clearly doesn't. I am also not relying on custom values only present in the `idToken`.

The custom interceptor does seem like an acceptable workaround, but that does not really address the issue with using the `accessToken` as intended.

**Comment by lawmicha** [comment] 2020-11-02 15:44
> I have a slightly different use case. In my iOS app, I simply started receiving 401s for all my requests after upgrading to 1.1.0. I am not using AppSync at all. My API uses a Cognito authorizer (with a user pool) for all protected requests. So I decided to simply change the `getTokenString()` method in AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift from returning the `accessToken` to `idToken` and everything suddenly started working again. So I don't exactly understand how the `accessToken` is supposed to work in my case and it clearly doesn't. I am also not relying on custom values only present in the `idToken`.
> 
> The custom interceptor does seem like an acceptable workaround, but that does not really address the issue with using the `accessToken` as intended.

Hi @zpodolyak, the reason why the change in this PR to use accessToken https://github.com/aws-amplify/amplify-ios/pull/690 and released in 1.1.0 was to match what JS and Android platforms were doing. We saw confusion before when customers built their app on multiple platforms against the same backend and iOS was intercepting the requests with idToken while JS and Android used the accessToken. 

> Thanks @lawmicha.
> I have been only working with Amplify for two months, but the JS version does seams a lot more stable and mature, would love to see that also for the iOS version. Initializing subscriptions with attributes for example is a pain compared to the JS SDK.
> 
> What I generally do not get about Amplify with AppSync, is how authorization is done in the resolvers without the `id`-token's user identity claims, if the `access`-token is the default one to use, which does not have that information encoded?
> 
> As this is not an edge case but actively referenced in the AWS AppSync dev guide for **Security / Authorization Use Cases** to use the `$context.identity.claims` which are only in the `id`-token:
> https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html
> 
> Thanks for your work guys 🙏


If the recommendation from AppSync is to use idToken, then perhaps the developers building on JS were simply all using the customHeader mechanism and providing an idToken from their auth provider. There has been some confusion around which one to use and which token has what information. When you said it does not have the information encoded, what information is in the idToken and what is in the accessToken? I read from [here](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) that they are interchangable.

**Comment by lawmicha** [comment] 2020-11-02 15:47
Recently, we released a change to support getting a token from the developer when their use case is any ODIC provider. If you perform to treat your cognito user pool auth provider as an OIDC provider, you can follow this to return the `idToken` and set the API as an ODIC use case: https://github.com/aws-amplify/docs/pull/2613

So the developer would replace their custom request interceptor with their custom OIDC token provider instead

**Comment by LaszloDev** [comment] 2020-11-02 18:39
> I have a slightly different use case. In my iOS app, I simply started receiving 401s for all my requests after upgrading to 1.1.0. I am not using AppSync at all. My API uses a Cognito authorizer (with a user pool) for all protected requests. So I decided to simply change the `getTokenString()` method in AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift from returning the `accessToken` to `idToken` and everything suddenly started working again. So I don't exactly understand how the `accessToken` is supposed to work in my case and it clearly doesn't. I am also not relying on custom values only present in the `idToken`.
> 
> The custom interceptor does seem like an acceptable workaround, but that does not really address the issue with using the `accessToken` as intended.

@zpodolyak Amplify is just a wrapper. When you are using the `Ampilfy.API` from the SDK, in the background your client is using the AppSync GraphQL API. Your API authentication is probably relying on authentication information like Cognito Groups, which are encoded into the `id`-token but not the `access`-token. There are different use cases and yours might be a bit different. But you get the idea.

-----

> If the recommendation from AppSync is to use idToken, then perhaps the developers building on JS were simply all using the customHeader mechanism and providing an idToken from their auth provider.

@lawmicha I would not say that AppSync is specifically recommending the `idToken`, but if you want to utilize the Cognito authentication mechanisms thats the way from my understanding.

It's well documented by this time, how the JS client needs to be configured to use the `idToken` instead of the `accessToken`. As Im mainly a JS developer and not working with iOS directly. See [here for example](https://github.com/aws-amplify/amplify-js/issues/3326#issuecomment-549188797)

The `JS Rest documentation` specifically mentions 
> The ID Token contains claims about the identity of the authenticated user such as name, email, and phone_number. It could have custom claims as well, for example using Amplify CLI. On the Amplify Authentication category you can retrieve the Id Token using:
https://docs.amplify.aws/lib/restapi/authz/q/platform/js#note-related-to-use-access-token-or-id-token

Also the `JS GraphQL documentation`:

![image](https://user-images.githubusercontent.com/10655255/97903587-90896280-1d3f-11eb-9f32-2d77cc6d2974.png)
https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js#api-key

----

> There has been some confusion around which one to use and which token has what information. When you said it does not have the information encoded, what information is in the idToken and what is in the accessToken? I read from [here](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) that they are interchangable.

It took me also bit to understand the differences and I hope my infos will help you also. Both tokens allow the basic authorization regards being valid / not expired, besides its additional claims/properties being different.

I understand that you try to be more aligned with all frameworks, which is really great. Just this change was a breaking change and it seams like just hardcoding&replacing one token with another would not get you in alignment with the JS SDK. Which does provides the flexibility with a configuration API for the header tokens.

We are basically stuck on the v1.0 until the iOS framework has the same configuration APIs as the JS has.

**Comment by palpatim** [comment] 2020-11-07 18:04
We are working on a way to support using idToken for authorizers. We'll update this issue when we have more info

**Comment by lawmicha** [comment] 2020-11-10 00:06
Thanks for all the details and patience. As mentioned, the custom request interceptors (https://github.com/aws-amplify/amplify-ios/issues/780#issuecomment-702926246) has an issue with subscriptions. The chain of request interceptors are not used for subscription connection requests. 

For the use case to use Cognito user pool's ID Token instead of accessToken, you can treat the Cognito user pool as your OIDC provider and update the authorizationType to `OPENID_CONNECT`
```json
{
    "awsAPIPlugin": {
        "<YOUR-GRAPHQLENDPOINT-NAME": {
            "endpointType": "GraphQL",
            "endpoint": "[GRAPHQL-ENDPOINT]",
            "region": "[REGION]",
            "authorizationType": "OPENID_CONNECT",
        }
    }
}
```
Create a subclass of `APIAuthProviderFactory`
```swift
class MyAPIAuthProviderFactory: APIAuthProviderFactory {
    let myAuthProvider = MyOIDCAuthProvider()

    override func oidcAuthProvider() -> AmplifyOIDCAuthProvider? {
        return myAuthProvider
    }
}
```

Create the token provider to return the ID Token:
```swift
class MyOIDCAuthProvider : AmplifyOIDCAuthProvider {
    func getLatestAuthToken() -> Result<String, Error> {
        let semaphore = DispatchSemaphore(value: 0)
        var result: Result<String, Error> = .failure(AuthError.unknown("Could not retrieve Cognito token"))
        Amplify.Auth.fetchAuthSession { (event) in
            defer {
                semaphore.signal()
            }
            switch event {
            case .success(let session):
                if let cognitoTokenResult = (session as? AuthCognitoTokensProvider)?.getCognitoTokens() {
                    switch cognitoTokenResult {
                    case .success(let tokens):
                        result = .success(tokens.idToken)
                    case .failure(let error):
                        result = .failure(error)
                    }
                }
            case .failure(let error):
                result = .failure(error)
            }
        }
        semaphore.wait()
        return result
    }
}
```
Then instantiate it with AWSAPIPlugin
```
try Amplify.add(plugin: AWSAPIPlugin(apiAuthProviderFactory: MyAPIAuthProviderFactory()))
try Amplify.configure()
```

This mechanism also supports GraphQL subscription requests, which is something that when using a custom request interceptor is currently lacking. Although this isn't exactly like how JS does it, you should be able to achieve the same result. Please let me us know if this works for you.

Related documentation update: https://github.com/aws-amplify/docs/pull/2211

**Closed** 2020-11-21 00:42 UTC
Labels: auth, closing soon
