### ISSUE TITLE
[DataStore] web socket does not recover after extended background time

### ISSUE THREAD

**Issue by Tom-RulesCube** [aws-amplify/amplify-ios#702] opened 2020-08-11 13:29 UTC
**Describe the bug**
We have a working Amplify application that uses DataStore.

DataStore is working as expected under normal conditions.

If the app is placed into the background (but not terminated) for a short period of time say < 50 minutes, DataStore (or AppSync) determines that the socket is stale and disconnected, and it successfully re-connects.

If the app is in the background (and does not terminate) for a long period of time, say > 50 minutes, DataStore appears to go through the same recovery procedure but the reconnection is not successful and the app must be restarted.

**To Reproduce**
Run application, place the application in the background by tapping the home button.

Wait for various durations (we haven't got this down to an exact number, but an hour definitely does it), and activate the application

**Expected behavior**
We expect the socket connection to be re-connected and data sync to resume

Also _DESIRED_ behaviour would be hub events that explicitly tell us when the DataStore sync is no longer operating and/or when the web socket connection cannot be established

**Screenshots**

**Environment(please complete the following information):**
```
PODS:
  - Amplify (1.0.0):
    - Amplify/Default (= 1.0.0)
  - Amplify/Default (1.0.0)
  - AmplifyPlugins/AWSAPIPlugin (1.0.0):
    - AppSyncRealTimeClient (~> 1.1.0)
    - AWSPluginsCore (= 1.0.0)
    - ReachabilitySwift (~> 5.0.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.0.0):
    - AWSMobileClient (~> 2.13.4)
    - AWSPluginsCore (= 1.0.0)
  - AmplifyPlugins/AWSDataStorePlugin (1.0.0):
    - AWSPluginsCore (= 1.0.0)
    - SQLite.swift (~> 0.12.0)
  - AmplifyPlugins/AWSPinpointAnalyticsPlugin (1.0.0):
    - AWSPinpoint (~> 2.13.4)
    - AWSPluginsCore (= 1.0.0)
  - AmplifyPlugins/AWSS3StoragePlugin (1.0.0):
    - AWSPluginsCore (= 1.0.0)
    - AWSS3 (~> 2.13.4)
  - AppSyncRealTimeClient (1.1.6):
    - Starscream (= 3.0.6)
  - AWSAppSync (3.1.2):
    - AppSyncRealTimeClient (~> 1.1)
    - AWSCore (~> 2.13.0)
    - ReachabilitySwift (~> 5.0.0)
    - SQLite.swift (~> 0.12.2)
  - AWSAuthCore (2.13.4):
    - AWSCore (= 2.13.4)
  - AWSCognitoIdentityProvider (2.13.4):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.13.4)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.13.4)
  - AWSMobileClient (2.13.4):
    - AWSAuthCore (= 2.13.4)
    - AWSCognitoIdentityProvider (= 2.13.4)
  - AWSPinpoint (2.13.4):
    - AWSCore (= 2.13.4)
  - AWSPluginsCore (1.0.0):
    - Amplify (= 1.0.0)
    - AWSCore (~> 2.13.4)
    - AWSMobileClient (~> 2.13.4)
  - AWSS3 (2.13.4):
    - AWSCore (= 2.13.4)
  - PromisesObjC (1.2.8)
  - PromisesSwift (1.2.8):
    - PromisesObjC (= 1.2.8)
  - ReachabilitySwift (5.0.0)
  - SDWebImage (5.8.0):
    - SDWebImage/Core (= 5.8.0)
  - SDWebImage/Core (5.8.0)
  - Signals (6.1.0)
  - SQLite.swift (0.12.2):
    - SQLite.swift/standard (= 0.12.2)
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.0.6)
```
 - Swift Version : latest

**Device Information (please complete the following information):**
 - Device: iPhone 11 simulator, iPhone XR (real device), and indicated on other test devices
 - iOS Version: 13.6
 - Specific to simulators: 

**Additional context**

We log all the HUB events and indicate when the application is coming out of background with trace messages.

Here is the app starting up, then being placed into the background, then coming out of the background after a short period of time ( ~ 10 minutes) -- logs have been cleaned for anyone sensitive info. The `DATASTORE IS READY` message is a `DataStore.syncStarted` hub event.

```
*** SCENE DID ENTER FOREGROUND ***
*** SCENE DID BECOME ACTIVE ***
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT Amplify.configured
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT API.subscribe
2020-08-10 18:39:57.671315-0400 MyAppDev[18425:835286] Header - Optional("{\"Authorization\":\"...")
2020-08-10 18:39:57.671852-0400 MyAppDev[18425:835281] Connecting to url ...
AMPLIFY EVENT API.subscribe
-- bunch of these ---
AMPLIFY EVENT Auth.fetchUserAttributesAPI
DATASTORE GET DEFERRED Profile(id: "1cc932ae-8a67-4ba9-afd3-ccfa99f7cef3")
2020-08-10 18:39:57.949445-0400 MyAppDev[18425:835282] WebsocketDidConnect
2020-08-10 18:39:57.949563-0400 MyAppDev[18425:835282] WebsocketDidConnect, sending init message...
2020-08-10 18:39:57.949668-0400 MyAppDev[18425:835282] Validating connection
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 18:39:57.957481-0400 MyAppDev[18425:835286] Message type does not need signing - connectionInit("connection_init")
2020-08-10 18:39:57.957688-0400 MyAppDev[18425:835286] Websocket write - {"type":"connection_init"}
2020-08-10 18:39:57.983194-0400 MyAppDev[18425:835286] WebsocketDidReceiveMessage - {"type":"connection_ack","payload":{"connectionTimeoutMs":300000}}
2020-08-10 18:39:57.983860-0400 MyAppDev[18425:835286] WebsocketDidReceiveMessage - {"type":"ka"}
2020-08-10 18:39:57.983936-0400 MyAppDev[18425:835282] Start subscription
--- bunch of these ---
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 18:39:57.991750-0400 MyAppDev[18425:835286] Websocket write - {"id":"9084F35B-B53E-44CE-9AB8-2DD57F66811A","payload":{"data":"{\"query\":\"subscription OnCreateSpendSummary3($username: String!) {\\n  onCreateSpendSummary3(username: $username) {\\n    id\\n    _ttl\\n    day\\n    error\\n    month\\n    numberOfReceipts\\n    state\\n    total\\n    type\\n    username\\n    year\\n    __typename\\n    _version\\n    _deleted\\n    _lastChangedAt\\n  }\\n}\",\"variables\":{\"username\":\"1cc932ae-8a67-4ba9-afd3-ccfa99f7cef3\"}}","extensions":{"authorization":{"Authorization":"..."}}},"type":"start"}
--- bunch of these ---
2020-08-10 18:39:58.218083-0400 MyAppDev[18425:835286] WebsocketDidReceiveMessage - {"id":"1E6F2798-187F-41CA-9729-094B5A7B23BF","type":"start_ack"}
AMPLIFY EVENT API.subscribe
--- bunch of these ---
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT API.query
--- bunch of these ---
DATASTORE IS READY
DATASTORE GET RESOLVED Profile(id: "1cc932ae-8a67-4ba9-afd3-ccfa99f7cef3")
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT Analytics.flushEvents
2020-08-10 18:40:57.949260-0400 MyAppDev[18425:836974] WebsocketDidReceiveMessage - {"type":"ka"}
*** SCENE WILL RESIGN ACTIVE ***
*** SCENE DID ENTER BACKGROUND ***
```
... now coming out of background
```
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 18:59:59.801598-0400 MyAppDev[18425:853132] Validating connection
2020-08-10 18:59:59.801787-0400 MyAppDev[18425:853132] Realtime connection is stale, disconnected.
2020-08-10 18:59:59.801830-0400 MyAppDev[18425:853134] WebsocketDidReceiveMessage - {"type":"ka"}
--- bunch of these ---
2020-08-10 18:59:59.802403-0400 MyAppDev[18425:836263] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
*** SCENE DID ENTER FOREGROUND ***
AMPLIFY EVENT API.subscribe
2020-08-10 18:59:59.811407-0400 MyAppDev[18425:836263] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
AMPLIFY EVENT API.subscribe2020-08-10 18:59:59.812452-0400 MyAppDev[18425:836263] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT API.subscribe
2020-08-10 18:59:59.824698-0400 MyAppDev[18425:836263] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
AMPLIFY EVENT API.subscribe
--- bunch of these ---
2020-08-10 18:59:59.828631-0400 MyAppDev[18425:853136] [AWSModelReconciliationQueue] receiveCompletion: error: DataStoreError: subscription item event failed with error
Caused by:
APIError: subscription item event failed with error
Caused by:
connection
2020-08-10 18:59:59.828627-0400 MyAppDev[18425:837350] [AWSModelReconciliationQueue] receiveCompletion: error: DataStoreError: subscription item event failed with error
--- bunch of these ---
AMPLIFY EVENT API.subscribe
2020-08-10 18:59:59.832345-0400 MyAppDev[18425:853159] Unsubscribe - 4C44A69F-E5AB-4A09-BF14-C8CBA4D18CAC
2020-08-10 18:59:59.832352-0400 MyAppDev[18425:836263] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
2020-08-10 18:59:59.832537-0400 MyAppDev[18425:853159] Unsubscribe - 080F7E47-1547-483D-912B-7E789881BCFF
2020-08-10 18:59:59.832685-0400 MyAppDev[18425:853159] Unsubscribe - 69C225AA-54E1-4371-9CE0-BDE4E5ED7996
--- bunch of these ---
AMPLIFY EVENT API.subscribe
--- bunch of these ---
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 18:59:59.850656-0400 MyAppDev[18425:837350] Message type does not need signing - unsubscribe("stop")
2020-08-10 18:59:59.850779-0400 MyAppDev[18425:837350] Websocket write - {"id":"4C44A69F-E5AB-4A09-BF14-C8CBA4D18CAC","type":"stop"}
AMPLIFY EVENT Auth.fetchSessionAPI
--- bunch of these ---
*** SCENE DID BECOME ACTIVE ***
AMPLIFY EVENT API.subscribe
--- bunch of these ---
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 19:00:00.134511-0400 MyAppDev[18425:853160] Header - Optional("{\"Authorization\":\"..."}")
AMPLIFY EVENT API.subscribe
2020-08-10 19:00:00.134966-0400 MyAppDev[18425:853161] Connecting to url ...
AMPLIFY EVENT API.subscribe
--- bunch of these ---
2020-08-10 19:00:00.542672-0400 MyAppDev[18425:853159] WebsocketDidConnect
2020-08-10 19:00:00.542793-0400 MyAppDev[18425:853159] WebsocketDidConnect, sending init message...
2020-08-10 19:00:00.542946-0400 MyAppDev[18425:853159] Validating connection
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 19:00:00.551280-0400 MyAppDev[18425:836974] Message type does not need signing - connectionInit("connection_init")
2020-08-10 19:00:00.551394-0400 MyAppDev[18425:836974] Websocket write - {"type":"connection_init"}
2020-08-10 19:00:00.576357-0400 MyAppDev[18425:836974] WebsocketDidReceiveMessage - {"type":"connection_ack","payload":{"connectionTimeoutMs":300000}}
2020-08-10 19:00:00.576843-0400 MyAppDev[18425:836974] WebsocketDidReceiveMessage - {"type":"ka"}

2020-08-10 19:00:00.576986-0400 MyAppDev[18425:853159] Start subscription
--- bunch of these ---
```

Here is the app coming out of the background (the initial startup will be the same) after around > 50 minutes... the web socket connection is never recovered
```
2020-08-10 19:57:58.496945-0400 MyAppDev[18710:891059] Validating connection
*** SCENE DID ENTER FOREGROUND ***
2020-08-10 19:57:58.507395-0400 MyAppDev[18710:891060] Realtime connection is stale, disconnected.
2020-08-10 19:57:58.532293-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
AMPLIFY EVENT API.subscribe
2020-08-10 19:57:58.533215-0400 MyAppDev[18710:860903] [AWSModelReconciliationQueue] receiveCompletion: error: DataStoreError: subscription item event failed with error
Caused by:
APIError: subscription item event failed with error
Caused by:
connection
2020-08-10 19:57:58.533452-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
AMPLIFY EVENT API.subscribe
2020-08-10 19:57:58.533800-0400 MyAppDev[18710:891061] Unsubscribe - B14FF4F0-9809-435C-92A9-DA4191E506B3
2020-08-10 19:57:58.533893-0400 MyAppDev[18710:891060] [AWSModelReconciliationQueue] receiveCompletion: error: DataStoreError: subscription item event failed with error
Caused by:
APIError: subscription item event failed with error
Caused by:
connection
2020-08-10 19:57:58.533895-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
2020-08-10 19:57:58.534015-0400 MyAppDev[18710:891061] Unsubscribe - 9069D0DA-8C9C-4546-AD3A-3157B249EC8F
2020-08-10 19:57:58.534162-0400 MyAppDev[18710:891061] Unsubscribe - 10EC4ABB-7A18-425D-BC25-1B4C3A78EB84
AMPLIFY EVENT API.subscribe
2020-08-10 19:57:58.534349-0400 MyAppDev[18710:891061] Unsubscribe - 1D7636A1-308D-427B-BF3E-877CAF973D49
2020-08-10 19:57:58.534475-0400 MyAppDev[18710:860933] [AWSModelReconciliationQueue] receiveCompletion: error: DataStoreError: subscription item event failed with error
Caused by:
APIError: subscription item event failed with error
Caused by:
connection
2020-08-10 19:57:58.534537-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
2020-08-10 19:57:58.534545-0400 MyAppDev[18710:891061] Unsubscribe - 1D2B2479-B7EB-4036-A027-A59D0C5B6AFE
2020-08-10 19:57:58.534740-0400 MyAppDev[18710:891061] Unsubscribe - EDA5A72B-DED0-4CCB-B160-608FDC4C9AD5
AMPLIFY EVENT API.subscribe
--- bunch of these ---
AMPLIFY EVENT API.subscribe
--- bunch of these ---
2020-08-10 19:57:58.540020-0400 MyAppDev[18710:860934] Self is nil, listener is not called.
--- bunch of these ---
AMPLIFY EVENT API.subscribe
*** SCENE DID BECOME ACTIVE ***
--- bunch of these ---
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT Auth.fetchSessionAPI
--- bunch of these ---
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 19:57:58.842256-0400 MyAppDev[18710:891087] Message type does not need signing - unsubscribe("stop")
2020-08-10 19:57:58.842403-0400 MyAppDev[18710:891087] Websocket write - {"id":"B14FF4F0-9809-435C-92A9-DA4191E506B3","type":"stop"}
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 19:57:58.846862-0400 MyAppDev[18710:891088] Header - Optional("{\"Authorization\":\"...")
2020-08-10 19:57:58.847383-0400 MyAppDev[18710:891059] Connecting to url ...
--- bunch of these ---
AMPLIFY EVENT API.subscribe
AMPLIFY EVENT Auth.fetchSessionAPI
--- bunch of these ---
2020-08-10 19:57:58.859359-0400 MyAppDev[18710:891087] Message type does not need signing - unsubscribe("stop")
2020-08-10 19:57:58.859541-0400 MyAppDev[18710:891087] Websocket write - {"id":"9069D0DA-8C9C-4546-AD3A-3157B249EC8F","type":"stop"}
AMPLIFY EVENT Auth.fetchSessionAPI
AMPLIFY EVENT Analytics.flushEvents
AMPLIFY EVENT Auth.fetchSessionAPI
--- bunch of these ---
2020-08-10 19:57:58.937293-0400 MyAppDev[18710:891087] Message type does not need signing - unsubscribe("stop")
2020-08-10 19:57:58.937429-0400 MyAppDev[18710:891087] Websocket write - {"id":"5DCBF6AF-0727-44BC-AE75-4EFFC45A1B45","type":"stop"}
AMPLIFY EVENT Auth.fetchSessionAPI
2020-08-10 19:57:59.289274-0400 MyAppDev[18710:891061] WebsocketDidConnect
2020-08-10 19:57:59.289342-0400 MyAppDev[18710:891061] WebsocketDidConnect, sending init message...
2020-08-10 19:57:59.289406-0400 MyAppDev[18710:891061] Validating connection
2020-08-10 19:57:59.289684-0400 MyAppDev[18710:891088] Realtime connection is stale, disconnected.
2020-08-10 19:57:59.289940-0400 MyAppDev[18710:891102] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
--- and it repeats ---
2020-08-10 19:58:00.042775-0400 MyAppDev[18710:891087] WebsocketDidConnect
2020-08-10 19:58:00.042908-0400 MyAppDev[18710:891087] WebsocketDidConnect, sending init message...
2020-08-10 19:58:00.043000-0400 MyAppDev[18710:891087] Validating connection
2020-08-10 19:58:00.043374-0400 MyAppDev[18710:891087] Realtime connection is stale, disconnected.
2020-08-10 19:58:00.043632-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
--- and again ---
2020-08-10 19:58:01.040277-0400 MyAppDev[18710:891102] WebsocketDidConnect
2020-08-10 19:58:01.040374-0400 MyAppDev[18710:891102] WebsocketDidConnect, sending init message...
2020-08-10 19:58:01.040438-0400 MyAppDev[18710:891102] Validating connection
2020-08-10 19:58:01.040772-0400 MyAppDev[18710:891102] Realtime connection is stale, disconnected.
2020-08-10 19:58:01.041108-0400 MyAppDev[18710:860934] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
--- and again ---
2020-08-10 19:58:06.588616-0400 MyAppDev[18710:891090] WebsocketDidConnect
2020-08-10 19:58:06.588748-0400 MyAppDev[18710:891090] WebsocketDidConnect, sending init message...
2020-08-10 19:58:06.588865-0400 MyAppDev[18710:891090] Validating connection
2020-08-10 19:58:06.589365-0400 MyAppDev[18710:891102] Realtime connection is stale, disconnected.
2020-08-10 19:58:06.589666-0400 MyAppDev[18710:860903] The operation couldn’t be completed. (AppSyncRealTimeClient.ConnectionProviderError error 3.)
... goes on for a while
```

**Comment by wooj2** [comment] 2020-08-11 22:32
Hi @Tom-RulesCube ,

I suspect the issue you are seeing is related to a fix we released in Amplify 1.0.6, which depends on the AppSyncRealTimeClient 1.0.4.

In AppSyncRealTimeClient 1.0.4, we believe addressed this issue here:
https://github.com/aws-amplify/aws-appsync-realtime-client-ios/commit/74c5079ecd67e4cdd47a69d3d5c92c33c9eb84b1

Based on the logs you uploaded, it looks like you are using Amplify 1.0.0.  Would you be able to upgrade your version of Amplify to 1.0.6 and see if this issue is resolved?

**Comment by Tom-RulesCube** [comment] 2020-08-12 17:10
If I delete Podfile.lock and lock and do a naive install, I end up with Amplify 1.0.0 and AppSyncRealTimeClient 1.1.6 ... should I try a pod install directly from the repo?

**Comment by palpatim** [comment] 2020-08-12 17:15
@Tom-RulesCube You need to do a `pod update`, not just a `pod install`, in order to get the latest version of Amplify. Alternately, you can remove the existing Podfile.lock and `pod install --repo-update`

**Comment by Tom-RulesCube** [comment] 2020-08-12 17:16
Sorry I deleted my original response to get some more info ... but I was wondering because my AppSyncRealTimeClient was 1.1.6 not 1.0.6 .. in any case I'll pod update and see where that puts me

**Comment by Tom-RulesCube** [comment] 2020-08-12 17:21
Right so it's AppSyncRealTimeClient 1.4  ... have this installed and will re-test shortly.

**Comment by Tom-RulesCube** [comment] 2020-08-12 19:06
Question though: is there any housekeeping we should or could be doing in the transition to background/foreground that makes sense?

Are operations performed on DataStore while it is validating the socket connection (and potentially re-connecting) valid?

**Comment by wooj2** [comment] 2020-08-14 16:09
Hi @Tom-RulesCube ,

>  is there any housekeeping we should or could be doing in the transition to background/foreground that makes sense?

If you are using DataStore in your application, there is no housekeeping (that I'm aware of) that you are responsible for if the user background/foregrounds the app.

> Are operations performed on DataStore while it is validating the socket connection (and potentially re-connecting) valid?

If you are performing operations on datastore (query, save, delete), while the socket connections and/or subscriptions are being made (or rather, while the sync engine is attempting to come up), it should be fine.  These operations are applied to your local DataStore first (currently implemented as a SQLite3 db), and these changes are eventually sync'ed with the backend once the entire sync engine comes up.

More inforomation can be found here: https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/ios but feel free to let us know if you have specific questions about our documentation.  We are always striving to make our documentation better/clearer/more easier to understand, so any feedback would be greatly appreciated!

**Comment by Tom-RulesCube** [comment] 2020-08-17 14:46
Upgrading to 1.4 Amplify appears to have addressed the issue, although we'll need a little more testing in the field to see how robust this in real world conditions.

**Comment by royjit** [comment] 2020-10-09 23:20
Optimistically closing the issue hoping that the issue is resolved. Feel free to reach back if you are still facing any issue.

**Closed by royjit** 2020-10-09 23:20 UTC
Labels: api, closing soon, datastore, requesting info
