### ISSUE TITLE
Declaration 'resultPublisher' cannot override more than one superclass declaration

### ISSUE THREAD

**Issue by soorinpark** [aws-amplify/amplify-ios#744] opened 2020-08-27 15:23 UTC
**Describe the bug**

Upon adding the Amplify SDK to the Xcode project, it does not build outputting numerous error around:

> Declaration 'resultPublisher' cannot override more than one superclass declaration

and

> Overriding declarations in extensions is not supported

**To Reproduce**

1. Install Amplify v1.1.0 via Cocoapods
2. Build

**Observed Behavior**
Project does not build due to compile errors from the SDK

**Expected behavior**
Project does not build due to compile errors from the SDK

**Screenshots**
![Screen Shot 2020-08-27 at 9 09 23 AM](https://user-images.githubusercontent.com/16075728/91462059-f987c200-e846-11ea-9c5f-0217a9f9b3ac.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.1.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 13.2
 - Specific to simulators: n/a

**Additional context**
n/a

**Comment by palpatim** [comment] 2020-08-27 23:12
Dupe of #717

Solution: Please upgrade to Xcode 11.4 or greater, or install the Swift 5.2 toolchain in a previous version of Xcode.

**Closed by palpatim** 2020-08-27 23:12 UTC
