### ISSUE TITLE
Non model objects cannot be created

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-ios#522] opened 2020-06-04 16:44 UTC
**Describe the bug**
I cannot create models that have a relation to a non model object
**To Reproduce**
Schema
```
type User @model {
  id: ID!
  completedActions: [Action]
}

type Action {
  id: ID!
}
```
Function 1 (API):
```
func createUser() {
        let action = Action(id: UUID().uuidString)
        let user = User(id: UUID().uuidString, completedActions: [action])
        print(user)
        _ = Amplify.API.mutate(request: .create(user)) { event in
            switch event {
            case .success(let result):
                switch result {
                case .success(let resp):
                    print("Successfully created user: \(resp)")
                case .failure(let error):
                    print("Got failed result with \(error.errorDescription)")
                }
            case .failure(let error):
                print("Got failed event with error \(error)")
            }
        }
    }
```
Error for function 1:
```
Got failed event with error APIError: Variables is a not a valid JSON object
```
Function 2 (DataStore):
```
func createUser() {
        let action = Action(id: UUID().uuidString)
        let user = User(id: UUID().uuidString, completedActions: [action])
        print(user)
        _ = Amplify.DataStore.save(user) { event in
            switch event {
            case .success:
                print("Added user")
            case .failure(let error):
                print("Error adding user - \(error.localizedDescription)")
            }
        }
    }
```
Error for function 2:
The logs print `Added user` but I don't see anything in DynamoDB.

**Expected behavior**
A new record to appear in the User table in DynamoDB

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 13.5

**Comment by drochetti** [comment] 2020-06-24 04:44
@amuresia this is a duplicate of https://github.com/aws-amplify/amplify-ios/issues/529 and it was already fixed. It will be released as part of `1.0.2` within the next days.

**Comment by amuresia** [comment] 2020-06-24 07:57
Hi @drochetti, thank you for the update. I was eager to try out the fix but I wasn't too lucky.
I am using the master branch as the source for my Pods and I changed my model manually to
`.field(user.completedActions, is: .optional, ofType: .embeddedCollection(of: Action.self))` (as aws-cli `4.21.4` is not out yet)
but I am experiencing the same error related to `SubSelectionRequired`.

I'll hold fire for a few more days until everything is released because surely I missed something when I tried to get a head start.

**Comment by drochetti** [comment] 2020-06-24 17:08
@lawmicha can you confirm if your fix for #529 also fixes this one? It seems like the same root cause to me.

**Comment by cabeaulac** [comment] 2020-06-24 20:25
I'm hitting this issue with an S3Object model object. Worse yet, I had a non-model object inside an object with a 1:many relationship and hit both of these issues at the same time. https://github.com/aws-amplify/amplify-ios/issues/277
I'm very concerned about waiting for 1.0.2 at this juncture as 1.0.1 has too many show-stoppers in it. Spending 75% of my time debugging Amplify bugs.

**Comment by palpatim** [comment] 2020-06-29 18:37
@amuresia Can you verify whether the 1.0.3 release fixes this? Remember to not only update the CocoaPods, but also the Amplify CLI (`npm install -g @aws-amplify/cli@latest`), and to regenerate the models with either the Amplify Tools build phase, or by manually running `amplify codegen models`.

**Comment by amuresia** [comment] 2020-07-05 14:48
Hi @palpatim, yes. I can confirm that this is working fine with `version 1.0.3`

**Comment by palpatim** [comment] 2020-07-06 21:07
Great to hear! Closing this.

**Closed by palpatim** 2020-07-06 21:07 UTC
Labels: bug, datastore, requesting info
