### ISSUE TITLE
Pod update is not updating to Amplify 1.6.0

### ISSUE THREAD

**Issue by VishnuNCS** [aws-amplify/amplify-ios#1149] opened 2021-04-06 05:54 UTC
Hi,

Not able to update to Amplify iOS version 1.6.0 through pods. It is still updating to 1.5.0. Any suggestions?

```
Analyzing dependencies
Downloading dependencies
Installing AWSAuthCore (2.19.1)
Installing AWSComprehend (2.19.1)
Installing AWSMobileClient (2.19.1)
Installing AWSPluginsCore (1.5.0)
Installing AWSPolly (2.19.1)
Installing AWSPredictionsPlugin (1.5.0)
Installing AWSRekognition (2.19.1)
Installing AWSTextract (2.19.1)
Installing AWSTranscribeStreaming (2.19.1)
Installing AWSTranslate (2.19.1)
Installing Amplify (1.5.0)
Installing AmplifyPlugins (1.5.0)
Installing CoreMLPredictionsPlugin (1.5.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 19 dependencies from the Podfile and 50 total pods installed.
```

**Comment by VishnuNCS** [comment] 2021-04-08 00:50
@palpatim ,

Here is my pod file

```
platform :ios, '12.0'
use_frameworks!

target 'Test' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
```
And I did `pod repo update` and `pod install`  but my `podfile.lock` shows `1.5.0`. Here is the information from lock file

```
PODS:
  - Amplify (1.5.0):
    - Amplify/Default (= 1.5.0)
  - Amplify/Default (1.5.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.5.0):
    - AWSAuthCore (~> 2.19.0)
    - AWSCognitoIdentityProvider (~> 2.19.0)
    - AWSCognitoIdentityProviderASF (~> 2.19.0)
    - AWSCore (~> 2.19.0)
    - AWSMobileClient (~> 2.19.0)
    - AWSPluginsCore (= 1.5.0)
  - AWSAuthCore (2.19.1):
    - AWSCore (= 2.19.1)
  - AWSCognito (2.19.1):
    - AWSCore (= 2.19.1)
  - AWSCognitoIdentityProvider (2.19.1):
    - AWSCognitoIdentityProviderASF (= 2.19.1)
    - AWSCore (= 2.19.1)
  - AWSCognitoIdentityProviderASF (2.19.1)
  - AWSCore (2.19.1)
  - AWSMobileClient (2.19.1):
    - AWSAuthCore (= 2.19.1)
    - AWSCognitoIdentityProvider (= 2.19.1)
    - AWSCognitoIdentityProviderASF (= 2.19.1)
    - AWSCore (= 2.19.1)
  - AWSPluginsCore (1.5.0):
    - Amplify (= 1.5.0)
    - AWSCore (~> 2.19.0)
    - AWSMobileClient (~> 2.19.0)

```

**Comment by palpatim** [comment] 2021-04-09 16:21
Dupe of https://github.com/aws-amplify/amplify-ios/issues/1082

**Closed by palpatim** 2021-04-09 16:21 UTC
Labels: build, question, requesting info
