### ISSUE TITLE
Create mutation fails with datastore - not adding belongsTo parent id to input

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-ios#298] opened 2020-01-22 03:37 UTC
**Describe the bug**
simple schema:

```graphql
type Entry @model {
  id: ID!
  comments: [Comment]
    @connection(name: "EntryComments", sortField: "createdAt")
}

type Comment @model {
  id: ID!
  commentEntryId: String!
  entry: Entry @connection(name: "EntryComments", sortField: "createdAt")
}
```
generates

```graphql
input CreateCommentInput {
  id: ID
  commentEntryId: String!
  _version: Int
}
```
create a comment with
```swift
let comment = Comment(entry: someExistingEntry)
```

then do 

```swift
Amplify.DataStore.save(comment).
```

the resulting generated input variable does not contain commentEntryId; so the mutation fails

this happens because the `entry` field is actually nil in the model at this line

https://github.com/aws-amplify/amplify-ios/blob/461c3cfd8923fbbb6eb10b60495b0f4594879cf4/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model%2BGraphQL.swift#L39

digging into it, it seems like something is off with the Model.from function here:

https://github.com/aws-amplify/amplify-ios/blob/461c3cfd8923fbbb6eb10b60495b0f4594879cf4/Amplify/Categories/DataStore/Model/Model%2BCodable.swift#L39

that is called by

https://github.com/aws-amplify/amplify-ios/blob/461c3cfd8923fbbb6eb10b60495b0f4594879cf4/Amplify/Categories/DataStore/Model/ModelRegistry.swift#L30

You'll notice that the json string being decoded contains all the necessary data to properly reconstruct the model. Also in Modal+codable, if a breakpoint is added, you can do `po try resolvedDecoder.decode(Self.self, from: data)` will show a properly constructed Comment Model with an entry field. However, in ModelRegistry, this field is now nil.

**Expected behavior**
input should be properly created for the mutation to succeed

**Environment(please complete the following information):**
 - Amplify Framework Version: 0.10
 - Dependency Manager: cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iphone 11 pro max simulator
 - iOS Version: ios 13.1

**Comment by rodrigoelp** [comment] 2020-01-25 14:34
I think all of these issues have the same root cause, they haven't implemented in full the specification for `@connection`for `belongsTo`.

Have a look at these issues I created #265, #277, #254. These are all related with different flavours of the same symptom.

**Comment by onlybakam** [comment] 2020-02-08 01:50
hey. need to add the field:

```graphql
type Entry @model {
  id: ID!
  comments: [Comment] @connection(name: "EntryComments", sortField: "createdAt")
}

type Comment @model {
  id: ID!
  createdAt: AWSDateTime
  entry: Entry @connection(name: "EntryComments", sortField: "createdAt")
}
```

**Comment by drochetti** [comment] 2020-03-20 19:06
Hi @onlybakam 

I investigated this one and it looks like an issue in the GraphQL Transformer in the Amplify CLI (https://github.com/aws-amplify/amplify-cli/issues/3702). I opened an issue in their repo and we will continua to investigate this as we move towards a stable release.

**Comment by amuresia** [comment] 2020-05-22 19:01
Issue was closed there but for me the problem was not addressed ...

**Comment by royjit** [comment] 2020-06-04 01:06
Hi @amuresia 

I tried to reproduce the issue, please let me know if these are the steps followed?

1. First I create an entry and save to datastore
2. Use the entry I created just now to create a comment
```swift
 func createEntry(_ sender: Any) {
        let entry = Entry()
        Amplify.DataStore.save(entry) { (result) in
           switch(result) {
           case .success(let savedItem):
               print("Saved entry: \(savedItem.id)")
               self.addComment(entryId: savedItem.id)
           case .failure(let error):
               print("Could not save item to datastore: \(error)")
           }
        }
    }

    func addComment(entryId: String) {
        Amplify.DataStore.query(Entry.self, where: Entry.keys.id.eq(entryId)) { result in
            switch result {
            case .success(let entries):
                guard entries.count == 1, let entry = entries.first else {
                    return
                }
                let comment = Comment(entry: entry)
                Amplify.DataStore.save(comment) { (commentResult) in
                   switch(commentResult) {
                   case .success(let savedItem):
                    print("Saved Comment : \(savedItem.id) \(savedItem.entry?.id)")
                   case .failure(let error):
                       print("Could not save item to datastore: \(error)")
                   }
                }
            case .failure(let error):
                print (error)
            }
        }
    }
```

3. Then when I try to retrieve the items by querying the Datastore

```
        Amplify.DataStore.query(Comment.self) { result in
            switch(result) {
                  case .success(let comments):
                      for comment in comments {
                          print("Comment id: \(comment.id) Entry id \(comment.entry?.id)")

                      }
                  case .failure(let error):
                      print("Could not query: \(error)")
                  }
        }
```
Everything worked as expected.

**Comment by royjit** [comment] 2020-06-04 20:25
Thank you for verifying. Closing this issue.

**Closed by royjit** 2020-06-04 20:25 UTC
Labels: Bug, DataStore, Requesting Feedback
