### ISSUE TITLE
Unable to Sign in with WebUI Cognito

### ISSUE THREAD

**Issue by andrewshivers** [aws-amplify/amplify-ios#1403] opened 2021-08-29 19:13 UTC
### Describe the bug

All of a sudden I am unable to sign in using Cognito webUI. I have no changed anything with the authentication functions in my app or the Cognito setting in the AWS console since the issue started. Now when I click the sign-in button on my app which calls
`Amplify.Auth.signInWithWebUI(presentationAnchor: UIApplication.shared.windows.first!)`

I get the error response: 
```
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/********/Documents/*******/*****Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
```

My Amplify Configuration is as such:
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "**************************************",
                            "Region": "***************"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "********************",
                        "AppClientId": "*************************",
                        "Region": "***********"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "**************",
                            "AppClientId": "*************************",
                            "SignInRedirectURI": "myApp://",
                            "SignOutRedirectURI": "myApp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Run web sign in
2. See error
```

### Expected behavior

Expected to open webUI view of the sign in

### Amplify Framework Version

    "Version": "1.0"

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

4.49.0

### Xcode version

Version 12.5.1 (12E507)

### Device

iPod touch 6th Gen

### iOS Version

iOS 14.7.1

### Specific to simulators

No

**Comment by pooshonk** [comment] 2021-08-31 16:36
I am having the exact same issue as you. This only atarte dhappening a few days ago. Have you found anything else out or are you still in the same position?

**Comment by andrewshivers** [comment] 2021-08-31 16:58
Hi,

Unfortunately no luck, but I haven't really dug that far, and there error message doesn't give you much to go on. I was already planning on converting from the web login to an in app solution using cognito, so I may just move that up my list of things to do and see if that fixes it?

**Comment by harsh62** [comment] 2021-09-24 17:15
@andrewshivers I am unable to reproduce this issue. Could you share the sample app which has this problem? It would help me fast-track my deep dive into the issue.

**Comment by andrewshivers** [comment] 2021-10-16 20:39
@harsh62 unfortunately due to some licensing issues I can't share the source... I had it fixed for a bit but the issue re-emerged. and I haven't had a chance to change the app over from the web Cognito to an in app one.

**Comment by harsh62** [comment] 2021-11-12 20:48
@andrewshivers It would be worth giving it a try. May be try doing it in a demo app and see if you are able to isolate the issue.

**Comment by harsh62** [comment] 2021-12-03 17:18
I will be closing this issue. If you still face issues. Feel free to open it again.

**Closed by harsh62** 2021-12-03 17:18 UTC
Labels: pending-response, auth, closing soon, follow up
