### ISSUE TITLE
warning: Model myModel has auth with authStrategy public of which is not yet supported in DataStore. 

### ISSUE THREAD

**Issue by hbou** [aws-amplify/amplify-ios#1226] opened 2021-05-12 21:30 UTC
hi

my graphql has an entity like this: 
```
type myModel @model @auth(rules: [
    { allow: public, operations: [read] }

]) {
  id: ID!
  aaa: String!
  bbb: Float!
  ccc: AWSJSON
  ddd: AWSDateTime
}
```

I get this message when I try to save something on the server side (I see nothing on server , in admin.amplifyapp.com/)

> warning: Model myModel has auth with authStrategy public of which is not yet supported in DataStore.

my understanding, is I have to add login/password for my users in other to save on amplify for iOS ? I don't want to do this, I just want to let users use the app without logins at first with the possibility to save on server.

is this correct? if yes, is it planed soon to add support for app to "use of api without having user to login"?

thank you in advance for your support

**Comment by palpatim** [comment] 2021-05-14 15:03
Dupe of https://github.com/aws-amplify/amplify-ios/discussions/1221, let's continue the conversation there

**Closed by palpatim** 2021-05-14 15:03 UTC
