### ISSUE TITLE
"Some error occuring retrieving the IdentityId"

### ISSUE THREAD

**Issue by drshre** [aws-amplify/amplify-ios#357] opened 2020-03-13 20:08 UTC
This app is entirely set up using Amplify, and I get this error message when trying to upload a file to S3.

Failed: Unexpected error occurred with message: Some error occuring retrieving the IdentityId.. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: ../Pods/Amplify/Amplify/Categories/Storage/Error/AuthError.swift
function: recoverySuggestion
line: 30

I am uploading a JSON file created on the mobile device, using basically the same function that is used in the Amplify Storage setup documentation.

    func uploadFileToS3(tripId: String) {
        let fileName = tripId + ".json"
        let fileURL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent(fileName)

        _ = Amplify.Storage.uploadFile(key: fileName, local: fileURL) { (event) in
            switch event {
            case .completed(let data):
                print("Completed: \(data)")
            case .failed(let storageError):
                print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
            case .inProcess(let progress):
                print("Progress: \(progress)")
            default:
                break
            }
        }
    }

**Comment by kneekey23** [comment] 2020-03-17 18:47
hi @drshre did you also add the auth category as well (`amplify add auth`)? How are you authenticating your user before making this call?

**Comment by drshre** [comment] 2020-03-25 22:38
hi @kneekey23, I have added the auth category and am not using guest access

**Comment by kneekey23** [comment] 2020-03-28 18:20
Hi @drshe are you using `AWSMobileClient` to authenticate your user?

**Comment by drshre** [comment] 2020-03-29 21:48
@kneekey23, yes I am! Using everything through AWS Amplify

**Comment by lawmicha** [comment] 2020-06-26 18:57
Hi @drshre, thanks for reporting this issue. Since then we have released AWSCognitoAuthPlugin which replaces AWSMobileClient. The new usage looks like this: [storage getting started](https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios#prerequisites)

To reproduce the error, I provisioned the S3 bucket with only authenticated users allowed to perform operations.
```
? Who should have access: `Auth users only`
? What kind of access do you want for Authenticated users? `create/update, read, delete`
```

This means only a signed in user can perform the CRUD operations on the S3 bucket. No unauthenticated/guest access allowed.

When I run the example uploadData, without a signed in user, the error is now:
```
Failed: There is no user signed in to retreive identity id. Call Auth.signIn to sign in a user or enable unauthenticated access in AWS Cognito Identity Pool
```

You can now handle this correctly by checking that the error is the `.authError` case, ie.
```
case .failure(let storageError):
    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    if case .authError = storageError {
        // Auth error
    }
```

For more details on [Auth.signIn](https://docs.amplify.aws/lib/auth/signin/q/platform/ios)

I will optimiscally close this issue, feel free to open another issue if you are still seeing a problem

**Closed by lawmicha** 2020-06-26 18:57 UTC
Labels: auth, bug, follow up, storage
