### ISSUE TITLE
Adding AWSCognitoAuthPlugin to Xcode project causes repeated warnings in output console when running on simulator

### ISSUE THREAD

**Issue by treystudio3a** [aws-amplify/amplify-ios#1032] opened 2021-01-21 21:34 UTC
**Describe the bug**
When you add the AWSCognitoAuthPlugin to the Podfile, and update the project properly, when running, Xcode outputs a ton of repeated "warnings/errors", most of which are complaining that a class X is implemented in both the SpeakerRecognition framework and the CoreSpeech framework (neither of which are added to my project in any way).

**To Reproduce**
1. Follow normal steps to create an iOS amplify project
2. Add  pod 'AmplifyPlugins/AWSCognitoAuthPlugin' to PodFile
3. run pod install --repo-update
4. Compile Xcode and run in simulator
5. See the output window as it complains 

**Expected behavior**
Expect no warning or erorr logs.

**Screenshots**
<img width="2512" alt="Screen Shot 2021-01-21 at 3 33 56 PM" src="https://user-images.githubusercontent.com/75962490/105415216-19f15800-5bfe-11eb-9a0a-ae86700e1dfd.png">

Environment(please complete the following information):

Amplify Framework Version: 4.41.2
Dependency Manager: [Cocoapods]
Swift Version : version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) Target: x86_64-apple-darwin20.2.0
Xcode 12.3 (12C33)
Simulator: happens on any, i was trying iPhone 12 Pro Max (if I remove the models the project compiles)

**Comment by ruiguoamz** [comment] 2021-01-21 22:57
Hi, @treystudio3a 
Thanks for reaching out.

Which Amplify version are you using? `The Amplify Framework Version: 4.41.2` is the Amplify CLI version not the Amplify iOS Library version.

I tried it out on Amplify 1.5.4 and 1.5.3, I don't see these repeated warning message printed out. I don't see enough info to infer what could happen. Could you please try again or elaborate on this issue?

**Comment by treystudio3a** [comment] 2021-01-22 00:38
This is my podfile -- is this what you're referring to?  I'm not sure how to pull the Amplify iOS Library version?

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'StudioAppDesigner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Amplify'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
   
end

**Comment by treystudio3a** [comment] 2021-01-22 00:41
Here is contents of Podfile.lock

PODS:
  - Amplify (1.5.3):
    - Amplify/Default (= 1.5.3)
  - Amplify/Default (1.5.3)
  - AmplifyPlugins/AWSAPIPlugin (1.5.3):
    - AppSyncRealTimeClient (~> 1.4.0)
    - AWSCore (~> 2.22.0)
    - AWSPluginsCore (= 1.5.3)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.5.3):
    - AWSAuthCore (~> 2.22.0)
    - AWSCognitoIdentityProvider (~> 2.22.0)
    - AWSCognitoIdentityProviderASF (~> 2.22.0)
    - AWSCore (~> 2.22.0)
    - AWSMobileClient (~> 2.22.0)
    - AWSPluginsCore (= 1.5.3)
  - AmplifyPlugins/AWSDataStorePlugin (1.5.3):
    - AWSCore (~> 2.22.0)
    - AWSPluginsCore (= 1.5.3)
    - SQLite.swift (~> 0.12.0)
  - AppSyncRealTimeClient (1.4.2):
    - Starscream (~> 3.1.0)
  - AWSAuthCore (2.22.0):
    - AWSCore (= 2.22.0)
  - AWSCognitoIdentityProvider (2.22.0):
    - AWSCognitoIdentityProviderASF (= 2.22.0)
    - AWSCore (= 2.22.0)
  - AWSCognitoIdentityProviderASF (2.22.0)
  - AWSCore (2.22.0)
  - AWSMobileClient (2.22.0):
    - AWSAuthCore (= 2.22.0)
    - AWSCognitoIdentityProvider (= 2.22.0)
    - AWSCognitoIdentityProviderASF (= 2.22.0)
    - AWSCore (= 2.22.0)
  - AWSPluginsCore (1.5.3):
    - Amplify (= 1.5.3)
    - AWSCore (~> 2.22.0)
  - SQLite.swift (0.12.2):
    - SQLite.swift/standard (= 0.12.2)
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.1.1)

DEPENDENCIES:
  - Amplify
  - AmplifyPlugins/AWSAPIPlugin
  - AmplifyPlugins/AWSCognitoAuthPlugin
  - AmplifyPlugins/AWSDataStorePlugin

SPEC REPOS:
  trunk:
    - Amplify
    - AmplifyPlugins
    - AppSyncRealTimeClient
    - AWSAuthCore
    - AWSCognitoIdentityProvider
    - AWSCognitoIdentityProviderASF
    - AWSCore
    - AWSMobileClient
    - AWSPluginsCore
    - SQLite.swift
    - Starscream

SPEC CHECKSUMS:
  Amplify: 48c0d81972469bec6743685f1fae6e34b1ad29f9
  AmplifyPlugins: fcbe0f03d980db2f31b7d5bcf580092dfe4931a3
  AppSyncRealTimeClient: 7fb160294d067b6c0c4b3c4ab91e953fd4cfba30
  AWSAuthCore: b54e2008da479e5a6ffdb6b482821d8f5a9afaa4
  AWSCognitoIdentityProvider: 32a91ad644e49e40235a408a8fbb96ea74891f19
  AWSCognitoIdentityProviderASF: 8b92721c17f2951ecd5bcfb749d5534f2851c2c7
  AWSCore: 8bd1def9cb0b6770c65b6d394f1c1cbc0a5562b7
  AWSMobileClient: bba690cc09c6569cc1111141beaa4e2f789f536b
  AWSPluginsCore: ccd588bdf701106f9ba6f255d95c43b84b7632a2
  SQLite.swift: d2b4642190917051ce6bd1d49aab565fe794eea3
  Starscream: 4bb2f9942274833f7b4d296a55504dcfc7edb7b0

PODFILE CHECKSUM: 104644f1328720c56a8ca4a41f1b0d034e5906ab

COCOAPODS: 1.10.1

**Comment by treystudio3a** [comment] 2021-01-22 00:49
Also for what it's worth, it happens on any iPhone or iPad simulator, but when I change the target to "My Mac (Designed for iPad)" it does not output the additional "CoreSpeech.framework" complaints.

I'm also running on Apple's new 13 inch M1.

**Comment by ruiguoamz** [comment] 2021-01-22 20:51
We appreciate it if you can provide a sample app that reproduces this issue?

**Comment by treystudio3a** [comment] 2021-01-23 00:30
Here is a project I just created from scratch following the steps to reproduce above:

[SimulatorWarningsExample.zip](https://github.com/aws-amplify/amplify-ios/files/5859274/SimulatorWarningsExample.zip)

This is a screenshot of what I see in my simulator... there are many more repetitive warnings (which make it difficult to see any logging of my own).

<img width="1747" alt="Screen Shot 2021-01-22 at 6 28 53 PM" src="https://user-images.githubusercontent.com/75962490/105562483-ebe44480-5cdf-11eb-939e-a5bd9a2e62c5.png">

**Comment by ruiguoamz** [comment] 2021-01-25 02:33
Thanks for the sample app, but I do not see these output even with your app. I would try to run it on a M1 Mac. 

At the same time, can you also try to run it on Intel Mac and see if these output are there? Thanks

**Comment by palpatim** [comment] 2021-06-21 18:53
Closing as we're not able to reproduce this issue. If you're able to provide some additional information or repro steps, please feel free to re-open and we'll continue to investigate.

**Closed by palpatim** 2021-06-21 18:53 UTC
Labels: auth, build, not-reproducible
