### ISSUE TITLE
Multiple Authentication doesn't work with API and Function 

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#993] opened 2020-12-27 20:56 UTC
**Describe the bug**
We are using API/Datastore and Function together with Auth. In Auth we configured Cognito User Pools as default and IAM as additional config.
The calls with API/Datastore works now as expected, but our Functions in Lambda getting authentication errors. When we switch the defaults, so IAM is default and Cognito is the additional auth, the lambda function is working as expected and the calls doesn't anymore.
We tried many things, like setting the auth directives in our schema, setting iam and Cognito to public, etc. etc. but nothing worked. How can we use both authentications like expected? 

In our app we use Cognito user pools with authenticated and unauthenticated users, in our Lambda we are only using IAM with aws4auth

**To Reproduce**
1. Create API,Function and Auth
2. Set multiple Auth with Cognito User Pools and IAM
3. Set the default Auth to IAM
4. Get error, when calling API

**Expected behavior**
API with Cognito and Function/Lambda with IAM should both work simultaneously

 - Amplify Framework Version: 4.39.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.3

**Comment by chris-mds** [comment] 2020-12-28 01:50
Edit:
Found nearly the same issue [here](https://github.com/aws-amplify/amplify-cli/issues/4733#issue-650094369). With this solution I get a warning from the CLI `Model User has auth with authStrategy private of which is not yet supported in DataStore.`

But in the [docs](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios#public-authorization), private is mentioned and should be supported?

**Comment by wooj2** [comment] 2021-01-15 01:21
@chris-mds -

Sounds like you want your iOS application to use Cognito User Pools as an auth provider to authenticate with AppSync services, while having your lambda use IAM to access AppSync.  It sounds like you do not intend to have your iOS application use IAM to access AppSync.  Similarly, you do not intend to have your lambda use Cognito to access AppSync.  Is this correct?

In attempts to reproduce this issue, can you provide an example of a schema that is not working as intended?

Thank you!

**Comment by chris-mds** [comment] 2021-01-20 12:57
Yes this is correct. 

```
type Document @model
    @auth(rules: [
    {allow: private},
    {allow: private, provider: iam}
    ])
    {
    id: ID!
    name: String!
    filePath: String!
    createdAt: AWSDateTime!
}
```

As I mentioned I get an error inside our app, when IAM is default auth provider, while I get an error inside our lambda, when CognitoUserPools is default auth provider

**Comment by palpatim** [comment] 2021-06-21 18:54
We are working on a fix for this and will update when we have more info

**Comment by diegocstn** [comment] 2021-07-12 20:23
@chris-mds we've recently [released](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.12.0) support for [multiple authorization types](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios#configure-multiple-authorization-types) in DataStore that might be helpful to your use case

**Comment by palpatim** [comment] 2021-07-19 16:54
@chris-mds I'm optimistically flagging this as "closing soon", but please let us know if this does not solve your issue.

**Closed** 2021-09-10 03:46 UTC
Labels: pending-response, api, datastore, auth, closing soon
