### ISSUE TITLE
Using AWSMobileClient pod breaks build

### ISSUE THREAD

**Issue by frankiesimon** [aws-amplify/amplify-ios#2298] opened 2022-09-13 11:39 UTC
My Podfile has:

```
    pod 'Amplify'
    pod 'AWSCore', :modular_headers => true
    pod 'AWSAuthCore', :modular_headers => true
    pod 'AWSCognitoIdentityProvider', :modular_headers => true
    pod 'AWSCognitoIdentityProviderASF', :modular_headers => true
    pod 'AWSPinpoint', :modular_headers => true
    pod 'AWSS3', :modular_headers => true
    pod 'AWSMobileClient', :modular_headers => true
```

`pod install` works but when trying to build the project I'm failing when the AWSMoblieClient pod is buildling -- with this error:
```
/Users/frankie/MyProject/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Helpers/UserPoolHelper/AWSMobileClient+UserPoolAuthHelperCallbacks.swift:22:69: error: cannot find type 'AWSTaskCompletionSource' in scope
                            passwordAuthenticationCompletionSource: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>) {
```

This happens even without `import Amplify` anywhere in the code.

My `Podfile.lock` has these:
```
- Amplify (1.28.0):
    - Amplify/Default (= 1.28.0)
  - Amplify/Default (1.28.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.28.0):
    - AWSAuthCore (~> 2.27.0)
    - AWSCognitoIdentityProvider (~> 2.27.0)
    - AWSCognitoIdentityProviderASF (~> 2.27.0)
    - AWSCore (~> 2.27.0)
    - AWSMobileClient (~> 2.27.0)
    - AWSPluginsCore (= 1.28.0)
  - AmplifyPlugins/AWSPinpointAnalyticsPlugin (1.28.0):
    - AWSCore (~> 2.27.0)
    - AWSPinpoint (~> 2.27.0)
    - AWSPluginsCore (= 1.28.0)
  - AWSAuthCore (2.27.15):
    - AWSCore (= 2.27.15)
  - AWSCognitoIdentityProvider (2.27.15):
    - AWSCognitoIdentityProviderASF (= 2.27.15)
    - AWSCore (= 2.27.15)
  - AWSCognitoIdentityProviderASF (2.27.15):
    - AWSCore (= 2.27.15)
  - AWSCore (2.27.15)
  - AWSMobileClient (2.27.15):
    - AWSAuthCore (= 2.27.15)
    - AWSCognitoIdentityProvider (= 2.27.15)
    - AWSCognitoIdentityProviderASF (= 2.27.15)
    - AWSCore (= 2.27.15)
  - AWSPinpoint (2.27.15):
    - AWSCore (= 2.27.15)
  - AWSPluginsCore (1.28.0):
    - Amplify (= 1.28.0)
    - AWSCore (~> 2.27.0)
  - AWSS3 (2.27.15):
    - AWSCore (= 2.27.15)
```

I do find the file/definition in AWSCore pod in my environment so I'm not sure what's going on. Any tips?

**Comment by frankiesimon** [comment] 2022-09-19 13:44
Update:

I tried updating the versions but still getting the same issue.

Podfile:

```
   # Note - I got warnings telling me to add the modular_headers so added them like this:
    pod 'Amplify', '1.28.1'
    pod 'AWSCore', '2.28.0', :modular_headers => true
    pod 'AWSAuthCore', '2.28.0', :modular_headers => true
    pod 'AWSCognitoIdentityProvider', '2.28.0', :modular_headers => true
    pod 'AWSCognitoIdentityProviderASF', '2.28.0', :modular_headers => true
    pod 'AWSMobileClient', '2.28.0', :modular_headers => true
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', '1.28.1'
```

Podfile.lock has this:

```
PODS:
  - Amplify (1.28.1):
    - Amplify/Default (= 1.28.1)
  - Amplify/Default (1.28.1)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.28.1):
    - AWSAuthCore (~> 2.28.0)
    - AWSCognitoIdentityProvider (~> 2.28.0)
    - AWSCognitoIdentityProviderASF (~> 2.28.0)
    - AWSCore (~> 2.28.0)
    - AWSMobileClient (~> 2.28.0)
    - AWSPluginsCore (= 1.28.1)
  - AWSAuthCore (2.28.0):
    - AWSCore (= 2.28.0)
  - AWSCognitoIdentityProvider (2.28.0):
    - AWSCognitoIdentityProviderASF (= 2.28.0)
    - AWSCore (= 2.28.0)
  - AWSCognitoIdentityProviderASF (2.28.0):
    - AWSCore (= 2.28.0)
  - AWSCore (2.28.0)
  - AWSMobileClient (2.28.0):
    - AWSAuthCore (= 2.28.0)
    - AWSCognitoIdentityProvider (= 2.28.0)
    - AWSCognitoIdentityProviderASF (= 2.28.0)
    - AWSCore (= 2.28.0)
  - AWSPluginsCore (1.28.1):
    - Amplify (= 1.28.1)
    - AWSCore (~> 2.28.0)
```

Error is the same:

```
/Users/frankie/MyProject/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Helpers/UserPoolHelper/AWSMobileClient+UserPoolAuthHelperCallbacks.swift:22:69: error: cannot find type 'AWSTaskCompletionSource' in scope
                            passwordAuthenticationCompletionSource: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>) {
```

**Comment by atierian** [comment] 2022-09-20 17:16
Closing based on discussion on discord. There was an issue with the app's scheme name that caused this and it's not attributable to Amplify. Please comment here if you experience this issue again @frankiesimon, and I'll reopen.

**Closed by atierian** 2022-09-20 17:16 UTC
Labels: build

**Comment by 3ph** [comment] 2022-11-28 06:26
@atierian @frankiesimon I'm having the same issue but couldn't find any resolution on Discord. Can you tell me how to fix it?

**Comment by frankiesimon** [comment] 2022-11-30 11:10
> @atierian @frankiesimon I'm having the same issue but couldn't find any resolution on Discord. Can you tell me how to fix it?

I ended up using Swift Package Manager instead of cocoapods.

**Comment by 3ph** [comment] 2022-12-01 03:32
I actually had a great help on Discord so was able to sort it out - it was caused by not using `use_frameworks!` in the Podfile which was a leftover from OneSignal integration.
